### PR TITLE
Make sure circular `export * from X` does not stack overflow

### LINKED ISSUE #2815: circular `export * from` leads to infinite recursion
- Rollup Version: 1.10
- Operating System (or Browser): arch, firefox
- Node Version: 11.14

### How Do We Reproduce?

```ts
// a:
export * from "./b";
// b:
export * from "./a";
```

[REPL Link](https://rollupjs.org/repl?version=1.10.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZhJyUzQiU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGYiclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJTVDJTIyLiUyRmIlNUMlMjIlM0IlNUNuaW1wb3J0JTIwJTdCJTIwQjElMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmIlNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGNsYXNzJTIwQTElMjAlN0IlNUNuJTIwJTIwYigpJTIwJTdCJTIwcmV0dXJuJTIwQjElM0IlMjAlN0QlNUNuJTdEJTVDbmV4cG9ydCUyMGNsYXNzJTIwQTIlMjAlN0IlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAqJTIwZnJvbSUyMCU1QyUyMi4lMkZhJTVDJTIyJTNCJTVDbmltcG9ydCUyMCU3QiUyMEExJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZhJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBjbGFzcyUyMEIxJTIwJTdCJTVDbiUyMCUyMGEoKSUyMCU3QiUyMHJldHVybiUyMEExJTNCJTIwJTdEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY2xhc3MlMjBCMiUyMCU3QiUyMCU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) with complete example.

Found this while working on https://github.com/Swatinem/rollup-plugin-dts/issues/13#issuecomment-484656703 but as the REPL example shows, this also fails without any plugins.

The adapted testcase is from here:
https://github.com/Microsoft/web-build-tools/tree/master/build-tests/api-extractor-scenarios/src/circularImport2

### Expected Behavior

It should correctly bundle all the code :-)

### Actual Behavior

The REPL fails with `InternalError: too much recursion`

Locally I get an infinite recursion error.

### PR DESCRIPTION
**Pull request by Swatinem**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

closes #2815

### Description

Circular `export * from X` used to lead to a stack overflow. This Fix avoids that by keeping track of already walked modules. Not sure if this is the right place for such a fix?

### CODE REVIEW

**Comment by lukastaegert** [comment]
Looks great on first glance, unfortunately I have to quit working for today, hope to continue some time tomorrow

File: src/Module.ts [hunk 1]
```diff
@@ -308,20 +308,28 @@ export default class Module {
...
+	getReexports(walkedModuleIds = new Set<string>()) {
 		const reexports = Object.create(null);
 
 		for (const name in this.reexports) {
 			reexports[name] = true;
 		}
 
+		// avoid infinite recursion when using circular `export * from X`
+		if (walkedModuleIds.has(this.id)) {
+			return Object.keys(reexports);
```
Comment (lukastaegert) [inline src/Module.ts]: Instead of the `Object.keys`, couldn't you just return `this.reexports`? Then you could move the bail-out condition to the first line of the method. I even think that returning an empty array instead of `this.reexports` should work as well as the reexports of this module are already handled.

Comment (Swatinem) [reply src/Module.ts]: Good catch! I updated the commit.
