### PR TITLE
Fix namespace reexports bugs

### LINKED ISSUE #2156: Code splitting not working with default export/import
When using [`experimentalCodeSplitting`](https://github.com/caub/color-tf/blob/a6f15062587f8b273f6ae04e0addf3ba9235b650/rollup.config.js#L25), I get this erroneous generated content: https://unpkg.com/color-tf@5.0.0-beta1/dist/cjs/index-9f2891df.js

It should be `var hsl2hsv = require('./hsl2hsv.js');` instead of just `require('./hsl2hsv.js');`

**rollup version**: 0.58.2

------

You can probably reproduce with: (I couldn't put a different config in https://rollupjs.org/repl)

rollup.config.js
```js
export default {
  input: ['main.js', 'hsl2hsv.js', 'index.js'],
  output: {
    format: 'cjs',
    dir: 'dist/cjs',
  },
  experimentalCodeSplitting: true,
};
```

main.js
```js
import * as lib from './index';
export default new Map(Object.entries(lib))
```
hsl2hsv.js
```js
export default (h, s, l) => {
  const t = s * (l < 0.5 ? l : 1 - l),
    V = l + t,
    S = l > 0 ? 2 * t / V : 0;
  return [h, S, V];
};
```

index.js
```js
export { default as hsl2hsv } from './hsl2hsv';
```

### PR DESCRIPTION
**Pull request by guybedford**
This fixes #2156, which actually turned out to expose quite a few separate bugs:

1. src/Chunk.ts:193 needs to trace the full export through reexports, not just the variable trace. This stops a bug where Rollup would render `undefined` where a module specifier string name should be.
2. Namespace object reexports not working at all in Rollup, which seems to have always been an issue - https://rollupjs.org/repl?version=0.58.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMG0lMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKE9iamVjdC5rZXlzKG0pKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjB4JTIwJTdEJTIwZnJvbSUyMCdleHRlcm5hbDInJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

The fix for (1) is that one-liner, while the fix for (2) is to have namespaces being included populate an import for all reexported modules, and update the linkage graph to ensure this is handled for modules and chunks.

In the process of working on (2) I discovered and resolved two more bugs:

3. Hashes were being cached between different renders, so weren't being calculated correctly for module formats other than the "es" format being rendered first. The fix here is to clear the `chunk.renderHash` value on each render.

4. Generated imported module names for chunks are not currently being deshadowed - `import x from 'chunk2'` would not properly deshadow against a local `x` variable. This fix for this was to change the `isExternal` check on this deshadowing of `module.name` to include both externals and other chunk names (src/Chunk.ts:513).

### CODE REVIEW

File: src/Module.ts [hunk 1]
```diff
@@ -590,12 +590,32 @@ export default class Module {
...
+		return (this.declarations['*'] = new NamespaceVariable(this.astContext));
+	}
+
+	private includeNamespace() {
+		const namespace = this.getOrCreateNamespace();
+		if (namespace.needsNamespaceBlock) return;
+
+		let hasReexports = false;
+		for (const importName in this.reexports) {
+			if (importName in this.exports) continue;
```
Comment (lukastaegert) [inline src/Module.ts]: Removing this line does not produce any red tests. What is the condition in which this can happen and can we add this to a test?

File: src/Module.ts [hunk 2]
```diff
@@ -47,7 +45,7 @@ export interface CommentDescription {
 
 export interface ImportDescription {
 	source: string;
-	specifier: ImportSpecifier | ImportNamespaceSpecifier | ImportDefaultSpecifier;
+	start: number;
```
Comment (lukastaegert) [inline src/Module.ts]: This removes some unnecessary API 👍

File: src/Module.ts (hunk 1 above)
Comment (guybedford) [reply src/Module.ts]: You're completely right - this check is unnecessary as exports shadowing reexports throw an early error.

Comment (lukastaegert) [reply src/Module.ts]: 👍

**Comment by caub** [comment]
@guybedford Excuse me to ping you, I've found this other, maybe related bug

I'm using [latest rollup](https://github.com/caub/color-tf/blob/master/package.json#L38) and a default export like: https://github.com/caub/color-tf/blob/master/src/hsl2hsv.js
becomes this as `cjs`: https://unpkg.com/color-tf@5.0.2/hsl2hsv.js, it looks fine, but maybe `export.default = ..` was more expected as the bug arises in `proxy.js` where I import this file https://unpkg.com/color-tf@5.0.2/proxy.js and where default is used, which is undefined
