### PR TITLE
workaround for various object literal mutation bugs

### LINKED ISSUE #2345: Track object modifications via "this"
Taken from https://github.com/rollup/rollup/issues/2306#issuecomment-406612021:

In situations where an object is modified via accessing `this` in a function, the modification is not tracked properly. Example:

https://rollupjs.org/repl?version=0.63.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTVDbiUyMCUyMG1vZGlmeSgpJTIwJTdCJTVDbiU1Q3QlMjAlMjB0aGlzLm1vZGlmaWVkJTIwJTNEJTIwdHJ1ZSUzQiU1Q24lNUN0JTdEJTVDbiU3RCU1Q24lNUNub2JqLm1vZGlmeSgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwaXMlMjBtaXNzaW5nISU1Q25pZiUyMChvYmoubW9kaWZpZWQpJTIwY29uc29sZS5sb2coJ01PRElGSUVEJyklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Note that the use of `.call` or `.apply` is handled correctly:
https://rollupjs.org/repl?version=0.63.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25mdW5jdGlvbiUyMG1vZGlmeSgpJTIwJTdCJTVDbiUyMCUyMHRoaXMubW9kaWZpZWQlMjAlM0QlMjB0cnVlJTNCJTVDbiU3RCU1Q24lNUNubW9kaWZ5LmNhbGwob2JqKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGlzJTIwcmV0YWluZWQlMjBhcyUyMG9iaiUyMHdhcyUyMGElMjBjYWxsJTIwcGFyYW1ldGVyJTVDbmlmJTIwKG9iai5tb2RpZmllZCklMjBjb25zb2xlLmxvZygnTU9ESUZJRUQnKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

The modification-tracking needs to consider how a function is called:
https://rollupjs.org/repl?version=0.63.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25vYmoubW9kaWZ5JTIwJTNEJTIwbW9kaWZ5JTNCJTVDbiU1Q25mdW5jdGlvbiUyMG1vZGlmeSgpJTIwJTdCJTVDbiUyMCUyMHRoaXMubW9kaWZpZWQlMjAlM0QlMjB0cnVlJTNCJTVDbiU3RCU1Q24lNUNub2JqLm1vZGlmeSgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwaXMlMjBtaXNzaW5nISU1Q25pZiUyMChvYmoubW9kaWZpZWQpJTIwY29uc29sZS5sb2coJ01PRElGSUVEJyklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Closes #3093 
Closes #2473 
Closes #3027

### PR DESCRIPTION
**Pull request by kzc**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [x] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

#2345 #2473 #3027 #3093 #3192 #3264

### Description

Workaround for various object literal mutation bugs.

Some necessary minor regressions related to previously unsafe object literal optimizations.

Fixes #2345 #2473 #3027 #3093 #3192 #3264

### CODE REVIEW

**Comment by kzc** [comment]
This PR does indeed fix the third test case in #2345 as seen here:

input:

https://github.com/rollup/rollup/pull/3266/files#diff-e327407bfb6a2951b6ffb6e99b6b6dbdR31-R37

output:

https://github.com/rollup/rollup/pull/3266/files#diff-f9e32e571549a0ee3077bed0c7b2d828R21-R27

It's a slight variation the test case in question, but it also runs correctly on the original test case:

```
$ cat 2345c.js
const obj = {};

obj.modify = modify;

function modify() {
  this.modified = true;
}

obj.modify();

// This is missing!
if (obj.modified) console.log('MODIFIED');
```
with this PR:
```
$ dist/bin/rollup 2345c.js -f es --silent | node
MODIFIED
```
without this PR:
```
$ node_modules/.bin/rollup -v
rollup v1.27.6

$ node_modules/.bin/rollup 2345c.js -f es --silent | node
$ # no output
```
Feel free to modify this PR or ignore. I just wanted to demonstrate a workaround. The `CallExpression.ts` change relates to invalidating the object for member calls (the `this` issue), and the `MemberExpression.ts` change addresses #2345 test case 3 and #3264 which you mentioned was fixed through other means. The latter change can be dropped if it's no longer required.

**Comment by lukastaegert** [comment]
My bad, I only copied over the CallExpression change but did not check that it fixes the last case only together with the other change. I will modify this and merge it in, thanks!

File: src/ast/nodes/CallExpression.ts [hunk 1]
```diff
@@ -66,6 +67,9 @@ export default class CallExpression extends NodeBase implements DeoptimizableEnt
 				this
 			);
 		}
+		if (this.callee instanceof MemberExpression && !this.callee.variable) {
```
Comment (kzc) [inline src/ast/nodes/CallExpression.ts]: Funny - I had this initially but dismissed it due the higher number of test regressions. But it's the safer route.

Comment (lukastaegert) [reply src/ast/nodes/CallExpression.ts]: Well, if we gonna fix it, we might just as well fix it all the way down. I kept the tests because I REALLY hope to get in a proper solution soon.
