### PR TITLE
Do not entirely move else branch if another else branch might accidentally be referenced.

### LINKED ISSUE #3716: Else branch follows the wrong if statement
- Rollup Version: 2.23.1
- Operating System (or Browser):
- Node Version (if applicable):
- Link to reproduction: https://rollupjs.org/repl/?version=2.23.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKG91dGVyQ29uZGl0aW9uKSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChpbm5lckNvbmRpdGlvbiklMjAlN0IlNUNuJTVDdCU1Q3QlNUN0JTVDdCU1Q3RhY3Rpb24xKCklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTIwZWxzZSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBmYWxzZSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0YlMjB3YXJuaW5nKCklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNBJTIwdm9pZCUyMDAlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwZWxzZSUyMGFjdGlvbjIoKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

I got this bug after upgrade to history v5 (cc @mjackson). Pop state cannot be called in production because rollup breaks else branch here https://github.com/ReactTraining/history/blob/master/packages/history/index.ts#L427-L459

### Expected Behavior

warning() should be fired according to outer condition not the inner one

### Actual Behavior

Else branch follows the wrong if statement

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3716

### Description
In case an if statement is nested within another if statement with no block statement in between and the outer if statement has an `else` branch, then any else branch of the inner if statement will not be entirely removed to avoid accidentally catching the `else` branch of the outer if statement.

### CODE REVIEW

File: test/function/samples/simplified-nested-if/main.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+else throw new Error("Shouldn't be reached");
+
+if (unknown) {
+	for (var x = 1; x--; x > 0)
+		if (!unknown) console.log('effect');
+		else 'Side effect free code to be dropped';
+} else throw new Error("Shouldn't be reached");
+
+if (unknown)
+	for (var x = 1; x--; x > 0)
```
Comment (kzc) [inline test/function/samples/simplified-nested-if/main.js:20]: Not that it matters, but the `x > 0` expressions in the 4 loops are superfluous. Perhaps you intended to swap the for loops' test with update.

Comment (lukastaegert) [reply test/function/samples/simplified-nested-if/main.js:20]: Makes sense
