### PR TITLE
Track deep literal reassignments and improve performance

### LINKED ISSUE #2237: Rollup v59 breaks application logic
Hi

Rollup v59+ removes function calls from object literals that are used by external code.

I have created small piece of code to reproduce the problem.
[Rollup v59](https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmNyZWF0ZURldlRvb2xzQnJpZGdlJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMnJTNCJTVDbiU1Q253aW5kb3cuZGV2dG9vbHMlMjAlM0QlMjBjcmVhdGVEZXZUb29sc0JyaWRnZSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3JlYXRlRGV2VG9vbHNCcmlkZ2UoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBNb3VudCUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBfaW5zdGFuY2VzQnlSZWFjdFJvb3RJRCUzQSUyMCU1QiU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkYlMjB0c2xpbnQlM0FkaXNhYmxlLW5leHQtbGluZSUzQW5vLWVtcHR5JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMF9yZW5kZXJOZXdSb290Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjBfcmVuZGVyTmV3Um9vdENvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCUyMHZhciUyMFJlY29uY2lsZXIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBtb3VudENvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwbW91bnRDb21wb25lbnQoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcGVyZm9ybVVwZGF0ZUlmTmVjZXNzYXJ5JTNBJTIwZnVuY3Rpb24lMjBwZXJmb3JtVXBkYXRlSWZOZWNlc3NhcnkoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmVjZWl2ZUNvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwcmVjZWl2ZUNvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB1bm1vdW50Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjB1bm1vdW50Q29tcG9uZW50KGluc3RhbmNlKSUyMCU3QiUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwJTJGKiolMjBOb3RpZnklMjBkZXZ0b29scyUyMHRoYXQlMjBhJTIwbmV3JTIwY29tcG9uZW50JTIwaW5zdGFuY2UlMjBoYXMlMjBiZWVuJTIwbW91bnRlZCUyMGludG8lMjB0aGUlMjBET00uJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBjb21wb25lbnRBZGRlZCUyMCUzRCUyMGZ1bmN0aW9uJTIwKHZOb2RlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBpbnN0YW5jZSUyMCUzRCUyMHVwZGF0ZVJlYWN0Q29tcG9uZW50KHZOb2RlJTJDJTIwbnVsbCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaXNSb290Vk5vZGUodk5vZGUpKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpbnN0YW5jZS5fcm9vdElEJTIwJTNEJTIwbmV4dFJvb3RLZXkocm9vdHMpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcm9vdHMlNUJpbnN0YW5jZS5fcm9vdElEJTVEJTIwJTNEJTIwaW5zdGFuY2UlM0IlNUNuJTVDdCU1Q3QlNUN0JTVDdCU1Q3QlMkYlMkYlMjBUaGlzJTIwY29tbWVudCUyMGlzJTIwYWxzbyUyMHJlbW92ZWQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQuX3JlbmRlck5ld1Jvb3RDb21wb25lbnQoaW5zdGFuY2UpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZpc2l0Tm9uQ29tcG9zaXRlQ2hpbGRyZW4oaW5zdGFuY2UlMkMlMjBmdW5jdGlvbiUyMChjaGlsZEluc3QpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNoaWxkSW5zdC5faW5EZXZUb29scyUyMCUzRCUyMHRydWUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChjaGlsZEluc3QpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChpbnN0YW5jZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwQ29tcG9uZW50VHJlZSUzQSUyMENvbXBvbmVudFRyZWUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQlM0ElMjBNb3VudCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBSZWNvbmNpbGVyJTNBJTIwUmVjb25jaWxlciUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb21wb25lbnRBZGRlZCUzQSUyMGNvbXBvbmVudEFkZGVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFJlbW92ZWQlM0ElMjBjb21wb25lbnRSZW1vdmVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFVwZGF0ZWQlM0ElMjBjb21wb25lbnRVcGRhdGVkJTVDbiUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

And in v58 this is working correctly [LINK](https://rollupjs.org/repl?version=0.58.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmNyZWF0ZURldlRvb2xzQnJpZGdlJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMnJTNCJTVDbiU1Q253aW5kb3cuZGV2dG9vbHMlMjAlM0QlMjBjcmVhdGVEZXZUb29sc0JyaWRnZSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3JlYXRlRGV2VG9vbHNCcmlkZ2UoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBNb3VudCUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBfaW5zdGFuY2VzQnlSZWFjdFJvb3RJRCUzQSUyMCU1QiU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkYlMjB0c2xpbnQlM0FkaXNhYmxlLW5leHQtbGluZSUzQW5vLWVtcHR5JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMF9yZW5kZXJOZXdSb290Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjBfcmVuZGVyTmV3Um9vdENvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCUyMHZhciUyMFJlY29uY2lsZXIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBtb3VudENvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwbW91bnRDb21wb25lbnQoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcGVyZm9ybVVwZGF0ZUlmTmVjZXNzYXJ5JTNBJTIwZnVuY3Rpb24lMjBwZXJmb3JtVXBkYXRlSWZOZWNlc3NhcnkoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmVjZWl2ZUNvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwcmVjZWl2ZUNvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB1bm1vdW50Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjB1bm1vdW50Q29tcG9uZW50KGluc3RhbmNlKSUyMCU3QiUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwJTJGKiolMjBOb3RpZnklMjBkZXZ0b29scyUyMHRoYXQlMjBhJTIwbmV3JTIwY29tcG9uZW50JTIwaW5zdGFuY2UlMjBoYXMlMjBiZWVuJTIwbW91bnRlZCUyMGludG8lMjB0aGUlMjBET00uJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBjb21wb25lbnRBZGRlZCUyMCUzRCUyMGZ1bmN0aW9uJTIwKHZOb2RlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBpbnN0YW5jZSUyMCUzRCUyMHVwZGF0ZVJlYWN0Q29tcG9uZW50KHZOb2RlJTJDJTIwbnVsbCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaXNSb290Vk5vZGUodk5vZGUpKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpbnN0YW5jZS5fcm9vdElEJTIwJTNEJTIwbmV4dFJvb3RLZXkocm9vdHMpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcm9vdHMlNUJpbnN0YW5jZS5fcm9vdElEJTVEJTIwJTNEJTIwaW5zdGFuY2UlM0IlNUNuJTVDdCU1Q3QlNUN0JTVDdCU1Q3QlMkYlMkYlMjBUaGlzJTIwY29tbWVudCUyMGlzJTIwYWxzbyUyMHJlbW92ZWQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQuX3JlbmRlck5ld1Jvb3RDb21wb25lbnQoaW5zdGFuY2UpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZpc2l0Tm9uQ29tcG9zaXRlQ2hpbGRyZW4oaW5zdGFuY2UlMkMlMjBmdW5jdGlvbiUyMChjaGlsZEluc3QpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNoaWxkSW5zdC5faW5EZXZUb29scyUyMCUzRCUyMHRydWUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChjaGlsZEluc3QpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChpbnN0YW5jZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwQ29tcG9uZW50VHJlZSUzQSUyMENvbXBvbmVudFRyZWUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQlM0ElMjBNb3VudCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBSZWNvbmNpbGVyJTNBJTIwUmVjb25jaWxlciUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb21wb25lbnRBZGRlZCUzQSUyMGNvbXBvbmVudEFkZGVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFJlbW92ZWQlM0ElMjBjb21wb25lbnRSZW1vdmVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFVwZGF0ZWQlM0ElMjBjb21wb25lbnRVcGRhdGVkJTVDbiUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

See how valid code gets removed inside `componentAdded` method

### PR DESCRIPTION
**Pull request by lukastaegert**
This resolves #2237.

The issue was that when tracking reassignments of variables, only the top most keys were considered while in fact reassignments of nested keys needed to be considered as well.

As first thought this increased amount of reassignments would have a heavy performance impact, I first refactored the way infinite recursions are prevented when tracking reassignments to use a mutable shared map structure. This had a noticeably positive effect on the performance of the node binding phase.

I also played around with replacing immutableJS for literal recursion tracking with a custom solution (here, immutability was important as otherwise, many literals would be treated as unknown needlessly) but it turns out the internal optimizations of immutableJS are not to be underestimated.

The actual fix turned out to be rather small and focused, solely happening in ObjectExpression and LocalVariable.

### CODE REVIEW

**Comment by guybedford** [comment]
Amazing work. Just starting to play around with this and get an idea of what's going on, so please bear with me.

As far as I can gather, what is being done is to track all reassignments so that the set of all possible assignments per subpath of an object is known?

I will being with my extremely naive questions:
1. What are the use cases for having both EntityPathTracker and ImmutableEntityPathTracker? At a glance it seems like ImmutableEntityPathTracker is used to track values, while entity path tracker handles the reassignments of objects themselves?
2. Once we have an unknown value in a given path assignment, surely an optimization would be to stop tracking further assignments to that path at that point given that the whole path is deopted then? Is this being done?
3. If we are tracking subpath reassignments comprehensively now, how come the following case isn't supported for treeshaking:

```js
const x = {
  a: false,
  b: false
};

function p (y) {
  y.a = true;
}

p(x);

if (x.b)
  console.log('bad');
else
  console.log('good');
```

**Comment by lukastaegert** [comment]
Thanks for taking a look already!

> As far as I can gather, what is being done is to track all reassignments so that the set of all possible assignments per subpath of an object is known?

Yes and no. This tracking is primarily used to prevent infinite recursions and is only used by LocalVariables for normal reassignments and CallExpressions for return value reassignments. As such, the intention is to track which reassignment requests happen a these two places.

This, however, is not the complete reassignment information. The core of the bug at hand was that when for instance `foo` is exported, all keys of `foo` as well as all keys of all `members` of foo etc. need to be treated as reassigned. The reassignment tracker, however, will only track that an "unknown key" of foo was reassigned. All other reassignments are tracked directly at the definition of `foo` (at least if `foo` is an object literal).

> Once we have an unknown value in a given path assignment, surely an optimization would be to stop tracking further assignments to that path at that point given that the whole path is deopted then? Is this being done?

Yes, this is exactly why there is now a reassignment tracker on module level so that this information is shared. Now if a reassignment request reaches a LocalVariable, the tracker is checked and if it has already tracked such a request, we abort the request. Due to this optimization, **the "analyze dependency graph" phase is now about 25% faster** in my experiments bundling (mainly) the TypeScript compiler.

> What are the use cases for having both EntityPathTracker and ImmutableEntityPathTracker? At a glance it seems like ImmutableEntityPathTracker is used to track values, while entity path tracker handles the reassignments of objects themselves?

The EntityPathTracker is much faster and/but will deoptimize much more easily in situations where results matter (as is the case for `getLiteralValue`). I first tried to use the EntityPathTracker for literal values as well but then it would deoptimize e.g. these situations:

```js
const a = 'key';
const obj = {[a]: false};

// this would be retained as the value of `a` needs to be looked up twice to get
// the value of `obj[a]`
if (obj[a]) console.log('not happening');

const b = false;

// again this would be retained as `b` is looked up twice to get the value of `b || b`
if (b || b) console.log('not happening');
```

However for future optimizations, the faster `EntityPathTracker` could be used e.g. to check if we have already called a function when checking if a function call has a side effect.

> If we are tracking subpath reassignments comprehensively now, how come the following case isn't supported for treeshaking

Reassignment tracking is not capable of tracking through function calls yet (mostly due to performance reasons). Thus if you pass an object to a function (*any* function really), a deoptimization will kick in that marks all keys as reassigned because "something bad might happen inside the function" (as it does in fact for `x.a`)

File: src/ast/ExecutionPathOptions.ts [hunk 1]
```diff
@@ -17,15 +17,14 @@ export enum OptionTypes {
...
 }
 
-export interface RESULT_KEY {}
-export const RESULT_KEY: RESULT_KEY = {};
-export type KeyTypes = OptionTypes | Entity | RESULT_KEY;
+interface RESULT_KEY {}
+const RESULT_KEY: RESULT_KEY = {};
+type KeyTypes = OptionTypes | Entity | RESULT_KEY;
 
 export class ExecutionPathOptions {
```
Comment (guybedford) [inline src/ast/ExecutionPathOptions.ts]: Can `NEW_EXECUTION_PATH` be removed from this file with all these refactorings of it?

File: src/ast/nodes/ArrowFunctionExpression.ts [hunk 2]
```diff
@@ -17,18 +17,21 @@ export default class ArrowFunctionExpression extends NodeBase {
...
 	preventChildBlockScope: true;
 
+	bind() {
+		super.bind();
+		this.scope.bind();
+	}
+
 	createScope(parentScope: Scope) {
-		this.scope = new ReturnValueScope({ parent: parentScope });
+		this.scope = new ReturnValueScope(parentScope);
```
Comment (guybedford) [inline src/ast/nodes/ArrowFunctionExpression.ts]: Much nicer.

File: src/ast/nodes/BinaryExpression.ts [hunk 3]
```diff
@@ -37,12 +38,15 @@ export default class BinaryExpression extends NodeBase {
 	right: ExpressionNode;
 	operator: keyof typeof binaryOperators;
 
-	getLiteralValueAtPath(path: ObjectPath, options: ExecutionPathOptions): LiteralValueOrUnknown {
+	getLiteralValueAtPath(
+		path: ObjectPath,
+		getValueTracker: ImmutableEntityPathTracker
```
Comment (guybedford) [inline src/ast/nodes/BinaryExpression.ts]: `getValue` makes it sound like this will be a function. How about just calling this `tracker` or even `recursionTracker`? As someone not familiar with the approach, I only finally got the "recursion" part properly when you explained it in the last comment, as otherwise there was nothing in the code to indicate this is what it's for.

File: src/ast/nodes/ConditionalExpression.ts [hunk 4]
```diff
@@ -21,28 +26,45 @@ export default class ConditionalExpression extends NodeBase {
 		path: ObjectPath,
 		callOptions: CallOptions,
 		callback: ForEachReturnExpressionCallback,
-		options: ExecutionPathOptions
+		calledPathTracker: EntityPathTracker
```
Comment (guybedford) [inline src/ast/nodes/ConditionalExpression.ts]: Again, it is probably obvious that the tracker is for this "called path", so perhaps just `tracker` or `recursionTracker`?

File: src/Module.ts [hunk 5]
```diff
@@ -266,6 +267,7 @@ export default class Module {
 			nodeConstructors,
 			propertyReadSideEffects:
 				!this.graph.treeshake || this.graph.treeshakingOptions.propertyReadSideEffects,
+			reassignmentTracker: new EntityPathTracker(),
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/Module.ts]: Good point, some wrong conceptions I had in my head while designing this.

File: src/ast/ExecutionPathOptions.ts (hunk 1 above)
Comment (lukastaegert) [reply src/ast/ExecutionPathOptions.ts]: Even though it is only used once in code, using the same variable would still provide some benefit. But I will move it to the proper location.

File: src/ast/nodes/BinaryExpression.ts (hunk 3 above)
Comment (lukastaegert) [reply src/ast/nodes/BinaryExpression.ts]: Yes, `recursionTracker` is probably much clearer to outsiders. Thanks for looking into this that deeply, this really helps to make the code a lot easier to understand!

File: src/ast/nodes/ConditionalExpression.ts (hunk 4 above)
Comment (lukastaegert) [reply src/ast/nodes/ConditionalExpression.ts]: 👍

**Comment by lukastaegert** [comment]
Ok, I have tried tracking literal value recursions via a counter and the result was rather disappointing: With my test code base (which contained the notoriously demanding TypeScript compiler itself as a worthy bundling target), there was hardly any measurable performance change, no matter how often I tried.

In this light, I would stick with the immutable tracker for now as it promises to provide optimal results. Optimal means that we only deoptimize if, while determining a literal value, we need to know this very literal value. 

That doesn't mean there isn't a lot of potential for the ExecutionPathOptions left as in many cases here, a mutable tracker might provide better results. But I would leave this for another PR as this could also mean changing the way, other information about the execution path is forwarded. So this is again ready for another review.

File: src/Module.ts [hunk 6]
```diff
@@ -267,7 +263,7 @@ export default class Module {
 			nodeConstructors,
 			propertyReadSideEffects:
 				!this.graph.treeshake || this.graph.treeshakingOptions.propertyReadSideEffects,
-			reassignmentTracker: new EntityPathTracker(),
+			reassignmentTracker,
```
Comment (guybedford) [inline src/Module.ts]: We already read things off graph here, so I would suggest just setting this as `reassignmentTracker: graph.reassignmentTracker` instead of a new argument, unless we switch all to being provided as arguments.

File: src/ast/nodes/CallExpression.ts [hunk 7]
```diff
@@ -135,15 +136,15 @@ export default class CallExpression extends NodeBase {
 		});
 	}
 
-	reassignPath(path: ObjectPath, options: ExecutionPathOptions) {
-		!options.hasReturnExpressionBeenAssignedAtPath(path, this) &&
+	reassignPath(path: ObjectPath) {
+		if (path.length > 0 && !this.context.reassignmentTracker.track(this, path)) {
```
Comment (guybedford) [inline src/ast/nodes/CallExpression.ts]: So reassignment is basically a deoptimization, and the reassignment tracker allows us to track this globally? Or is it again about managing recursion here?

File: src/Module.ts (hunk 6 above)
Comment (lukastaegert) [reply src/Module.ts]: Done

File: src/ast/nodes/CallExpression.ts (hunk 7 above)
Comment (lukastaegert) [reply src/ast/nodes/CallExpression.ts]: Yes, reassignments are a global deoptimization but basically, it is still only about recursion tracking. The reason I had to add this here is in addition to the usages in `LocalVariable` is this situation:

```js
const foo = () => foo();
foo().bar = 'baz';
```

The second assigment will trigger a "forEachReturnExpression"  with a reassignment for `foo`. This again will try to reassign the return expression `foo()` where we loose the recursion tracker of "forEachReturnExpression" and then another cycle starts. To break this cycle, one way was to extend the active tracking to call expressions.
