### PR TITLE
fix: generate the separate chunk for the entry module with explicated chunk filename or name

### LINKED ISSUE #5906: Some entry chunks are not generated
### Rollup Version

4.39.0

### Operating System (or Browser)

Ubuntu 24.04

### Node Version (if applicable)

20.18.1

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-m1gg7wth?file=README.md

The following command will not generate the set of expected output files (`index.js` _and_ `entryA.js`):

```bash
$ npx rollup@4.39.0 -i index.js -i entryA.js -d dist --format esm --preserveEntrySignatures=allow-extension
```

For more details, see reproduction link above.

### Expected Behaviour

All entry points configured via `-i` (CLI) or `InputOptions.input` (JS API) should be present in the output.

### Actual Behaviour

In the reproduction, `index.js` is no longer present since 4.39.0. Looks like the optimization in #5891 might also be applied to entry chunks?

### Note

The reproduction uses `--preserveEntrySignatures=allow-extension`, which seems to trigger this behavior.
We can easily work around this by using `--preserveEntrySignatures=strict` instead. But this is still highly surprising.

### LINKED ISSUE #5907: [Regression `4.39.0`] The "paths[1]" argument must be of type string. Received undefined
### Rollup Version

rollup@4.39.0

### Operating System (or Browser)

Linux

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://github.com/brillout/rollup-placeholder-bug

### Expected Behaviour

No error.

### Actual Behaviour

Error:

```
Error during build:
The "paths[1]" argument must be of type string. Received undefined
    at resolve (node:path:1101:7)
    at writeOutputFile (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:23189:22)
    at file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:23139:104
    at Queue.work (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:22266:38)
    at file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:22255:18
    at new Promise (<anonymous>)
    at Queue.run (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:22253:16)
    at file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:23139:94
    at Array.map (<anonymous>)
    at file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:23139:56
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at catchUnfinishedHookActions (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/rollup@4.39.0/node_modules/rollup/dist/es/shared/node-entry.js:22508:16)
    at buildEnvironment (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/vite@6.2.5_@types+node@22.14.0/node_modules/vite/dist/node/chunks/dep-Pj_jxEzN.js:51500:16)
    at Object.buildApp (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/vike@0.4.228_vite@6.2.5_@types+node@22.14.0_/node_modules/vike/dist/esm/node/plugin/plugins/build/pluginBuildApp.js:23:29)
    at Module.build (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/vike@0.4.228_vite@6.2.5_@types+node@22.14.0_/node_modules/vike/dist/esm/node/api/build.js:22:9)
    at cmdBuild (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/vike@0.4.228_vite@6.2.5_@types+node@22.14.0_/node_modules/vike/dist/esm/node/cli/entry.js:51:9)
    at cli (file:///home/rom/tmp/template-vike-solid-daisyui-hono/node_modules/.pnpm/vike@0.4.228_vite@6.2.5_@types+node@22.14.0_/node_modules/vike/dist/esm/node/cli/entry.js:14:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}
 ELIFECYCLE  Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

resolves #5907 
resolves #5906 

### Description
If an entry module has a specified filename or name in `this.emitFile()` call or input options, we should generate a separate chunk for it

### CODE REVIEW

File: src/Chunk.ts [hunk 1]
```diff
@@ -414,7 +414,7 @@ export default class Chunk {
 			if (module.preserveSignature === 'allow-extension') {
 				const canPreserveExports = this.canPreserveModuleExports(module);
 
-				if (canPreserveExports) {
+				if (canPreserveExports && !module.chunkFileNames.size && !module.chunkNames.length) {
```
Comment (lukastaegert) [inline src/Chunk.ts:417]: While having entries in module.chunkFileNames is definitely a condition to create a separate chunk, I am not 100% sure about module.chunkNames. Essentially, chunkNames are just hints how to build the name. What I would have expected is `module.chunkNames.every(name => name.!isUserDefined)`. This is false if any of the chunk names is set in package.json. On the other hand, maybe your fix is needed for #5907?

Comment (TrickyPi) [reply src/Chunk.ts:417]: For #5907, the condition `module.chunkFileNames.size` could solve it. I added the condition `!module.chunkNames.length` for #5906. You're right, for this specific case, we should check `isUserDefined`.

**Review by lukastaegert — APPROVED** [review]
