### PR TITLE
Ignore invalid trailing pure annotations

### LINKED ISSUE #4062: pure annotation bug
- Rollup Version: rollup v2.45.2
- Operating System (or Browser): n/a
- Node Version (if applicable): n/a

Repro:
```
$ cat test.js
/*@__PURE__*/ drop1();
/*@__PURE__*/
drop2();
keep1() /*@__PURE__*/ ; keep2();
keep3() ; /*@__PURE__*/
drop3();
keep4() /*@__PURE__*/ ; /* other comment */ keep5();
keep6() /*@__PURE__*/ ; // other comment
keep7();
```

Expected:
```
$ cat test.js | uglify-js -c
keep1(),keep2(),keep3(),keep4(),keep5(),keep6(),keep7();
```
```
$ cat test.js | terser -c
keep1(),keep2(),keep3(),keep4(),keep5(),keep6(),keep7();
```
```
$ cat test.js | esbuild --minify
keep1(),keep2(),keep3(),keep4(),keep5(),keep6(),keep7();
```

Actual:
```
$ cat test.js | rollup --silent
keep1()  ;keep3() ; 
keep4()  ;keep6()  ; // other comment
```

Notice that calls to `keep2`, `keep5` and `keep7` have been incorrectly dropped.

This bug is actually present in the test suite in a few places such as:

https://github.com/rollup/rollup/blob/7927f3d0ca51b8346a0bedf09eb8746821fd651e/test/form/samples/pure-comment-line-break/main.js#L9-L11

but it was masked by the coincidental tree shaking of `(() => {})();`.

Possible fix:

```patch
diff --git a/src/Graph.ts b/src/Graph.ts
index 847b9b6..9afb0fd 100644
--- a/src/Graph.ts
+++ b/src/Graph.ts
@@ -138,3 +138,3 @@ export default class Graph {
 
-		markPureCallExpressions(comments, ast);
+		markPureCallExpressions(comments, ast, code);
 
diff --git a/src/utils/pureComments.ts b/src/utils/pureComments.ts
index f6c681d..b16ac13 100644
--- a/src/utils/pureComments.ts
+++ b/src/utils/pureComments.ts
@@ -21,2 +21,3 @@ basicWalker.PropertyDefinition = function (node: any, st: any, c: any) {
 interface CommentState {
+	code: string;
 	commentIndex: number;
@@ -32,3 +33,4 @@ function handlePureAnnotationsOfNode(
 	while (commentNode && node.start >= commentNode.end) {
-		markPureNode(node, commentNode);
+		const between = state.code.substring(commentNode.end, node.start);
+		if (/^\s*$/.test(between)) markPureNode(node, commentNode);
 		commentNode = state.commentNodes[++state.commentIndex];
@@ -64,4 +66,5 @@ const isPureComment = (comment: acorn.Comment) => pureCommentRegex.test(comment.
 
-export function markPureCallExpressions(comments: acorn.Comment[], esTreeAst: acorn.Node) {
+export function markPureCallExpressions(comments: acorn.Comment[], esTreeAst: acorn.Node, code: string) {
 	handlePureAnnotationsOfNode(esTreeAst, {
+		code,
 		commentIndex: 0,
```

With fix:

```
$ cat test.js | rollup --silent
keep1() /*@__PURE__*/ ; keep2();
keep3() ; 
keep4() /*@__PURE__*/ ; /* other comment */ keep5();
keep6() /*@__PURE__*/ ; // other comment
keep7();
```

Anyone feel free to put together a PR for this issue and test it further.

### PR DESCRIPTION
**Pull request by kzc**
Ignore invalid trailing pure annotations that were incorrectly associated with subsequent calls.

This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

fixes #4062

### Description

Ignore invalid trailing pure annotations that were incorrectly associated with subsequent calls causing those calls to be erroneously dropped.

A valid pure annotation comment must precede a call or new expression and only whitespace characters may appear between the annotation comment and the following call.

### CODE REVIEW

**Comment by kzc** [comment]
@lukastaegert Can you please take over this PR?

I have no idea why `npm audit` would fail on only `Tests / Node 12 + Extra Tests (Linux)` as this PR did not change or introduce any packages:
```
npm ERR! rollup@2.47.0 security: `npm audit`
npm ERR! Exit status 1
```
Nor do I understand why coverage would decrease when both code paths of the newly introduced `if` statement are exercised by the tests.

File: test/form/samples/pure-comment-line-break/_expected.js [hunk 1]
```diff
@@ -6,17 +6,17 @@ console.log('should remain impure');
 console.log('code');
 console.log('should remain impure');
 
-console.log('code');
+console.log('code')/*@__PURE__*/;
 console.log('should remain impure');
 console.log('should remain impure');
 
-console.log('code');
+console.log('code');/*@__PURE__*///@__PURE__
```
Comment (lukastaegert) [inline test/form/samples/pure-comment-line-break/_expected.js:13]: This looks wrong

**Review by lukastaegert — CHANGES_REQUESTED** [review]
> I have no idea why npm audit would fail on only Tests / Node 12 + Extra Tests (Linux) as this PR did not change or introduce any packages

Well, that is the nature of security alerts: They pop up even though you did not change anything just because you triggered the test pipeline. I will see what I can do to fix this on master.

> I have no idea why npm audit would fail on only Tests / Node 12 + Extra Tests (Linux) as this PR did not change or introduce any packages

Your changes apparently removed coverage for the case where a Node has more than one annotation.

It seems your code breaks the existing logic to remove trailing annotations if a subsequent node is removed, see my other comment.

**Comment by lukastaegert** [comment]
Dependencies are now fixed on master

**Comment by kzc** [comment]
> It seems your code breaks the existing logic to remove trailing annotations if a subsequent node is removed, see my other comment.

Ah, okay. I missed that.

In addition, a proper fix ought to remove all invalid pure annotations, such as the ones introduced in the additional tests in this PR, as well as cases like the first annotation in the example below:

```
$ cat example.js 
var a = /*@__PURE__*/console.log;
var b = /*@__PURE__*/bar();
a(42, b);
```
```
$ cat example.js | rollup --silent
var a = /*@__PURE__*/console.log;
var b = /*@__PURE__*/bar();
a(42, b);
```
```
$ cat example.js | esbuild
var a = console.log;
var b = /* @__PURE__ */ bar();
a(42, b);
```
```
$ cat example.js | uglify-js -mc --annotations
var a=console.log,b=/*@__PURE__*/bar();a(42,b);
```
Notice the invalid pure annotation before a non-call was not emitted by esbuild and uglify.

My intention was to also remove such invalid pure annotations, but I was not familiar enough with the comment removal logic.

I just put together the original patch to advance the bug fix and don't have the desire to pursue it further. If you could take over this PR, that'd be great.

**Comment by kzc** [comment]
> It seems your code breaks the existing logic to remove trailing annotations if a subsequent node is removed, see my other comment.

As noted in #4062, in some cases invalid annotations trailing a call incorrectly removed the following call which coincidentally [would have been tree shaken anyway](https://github.com/rollup/rollup/blob/7927f3d0ca51b8346a0bedf09eb8746821fd651e/test/form/samples/pure-comment-line-break/main.js#L9-L11) and the previous tests masked that issue. Further reason to just remove all invalid annotations in the input.

File: test/form/samples/pure-comment-line-break/_expected.js (hunk 1 above)
Comment (kzc) [reply test/form/samples/pure-comment-line-break/_expected.js]: Fixed in latest PR by parsing the gap between the pure comment and the call with `acorn.parse` instead of just relying on whitespace being there. If it's just whitespace or comments, then there will be zero statements.

**Comment by kzc** [comment]
I didn't plan to refine the patch, but I had an epiphany to use `acorn.parse` to solve the problem rather easily.

The PR still does not remove invalid pure annotations however. Perhaps this could be done in a future PR.

**Comment by kzc** [comment]
Unrelated issue in 2.47.0 discovered when adding more tests: [repl](https://rollupjs.org/repl/?version=2.47.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolNDBfX1BVUkVfXyolMkYlMjBhKCklMkMlNUNuJTJGKiU0MF9fUFVSRV9fKiUyRiUyMGIoKSUyQyU1Q24lMkYqJTQwX19QVVJFX18qJTJGJTIwYygpJTJDJTVDbiUyRiolNDBfX1BVUkVfXyolMkYlMjBkKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

```
$ cat main.js
/*@__PURE__*/ a(),
/*@__PURE__*/ b(),
/*@__PURE__*/ c(),
/*@__PURE__*/ d();
```
```
$ cat main.js | rollup --silent
/*@__PURE__*/ a(),
/*@__PURE__*/ d();
```
```
$ cat main.js | uglify-js -c
$
```
```
$ cat main.js | esbuild --minify
$
```

**Comment by kzc** [comment]
This PR is good to merge. 

The unrelated suboptimal tree shaking [issue above](https://github.com/rollup/rollup/pull/4068#issuecomment-835649514) and removing pure comments not associated with function calls and `new` can be addressed in a future PR.

**Review by lukastaegert — APPROVED** [review]
I like your comprehensive tests! Interesting idea with the acorn parse. My naive approach would have been to use "findFirstOccurrenceOutsideComment", but that one can only search for strings and would not have been able to handle sequence expressions as well with a single call.

**Comment by lukastaegert** [comment]
Ok, seems GitHub Actions is.. broken? Going to ignore this for now as the previous run was successful.

**Comment by kzc** [comment]
https://www.githubstatus.com shows:
```
May 14, 2021
Unresolved incident: Incident with GitHub Actions.
```
