### PR TITLE
Class method effects

### LINKED ISSUE #3250: Static method calls always considered have side effect
- Rollup Version: 1.27.3
- Operating System (or Browser): macOS 10.15.1
- Node Version: v12.12.0

### How Do We Reproduce?

https://rollupjs.org/repl/?version=1.27.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwQSUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU3RCU1Q24lNUN0c3RhdGljJTIwbSgpJTIwJTdCJTdEJTVDbiU3RCU1Q24lNUNubmV3JTIwQSgpJTNCJTVDbkEubSgpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior

Both call exprs are removed.

### Actual Behavior

The call to the empty static method is kept.

### LINKED ISSUE #3989: Tree shaking not work when static method in class was used
- Link to Reproduce https://rollupjs.org/repl/?version=2.41.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmV4cG9ydCUyMCU3QiUyMHRlc3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGUuanMnJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjBGaWJlclRhc2tRdWV1ZSUyMCU3RCUyMGZyb20lMjAnLiUyRm1vZHVsZTIuanMnJTNCJTVDbmV4cG9ydCUyMCU3QiUyMHRlc3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGUzJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGUyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMEZpYmVyVGFza1F1ZXVlJTIwJTNEJTIwKGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwZnVuY3Rpb24lMjBGaWJlclRhc2tRdWV1ZSgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRoaXMudGFza1F1ZXVlJTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lNUN0JTVDbiU1Q3QlNUN0RmliZXJUYXNrUXVldWUuYWRkJTIwJTNEJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lNUN0JTVDdCU3RCU1Q24lNUN0JTVDbiUyMCUyMCUyMCUyMEZpYmVyVGFza1F1ZXVlLnByb3RvdHlwZS5jbGVhciUyMCUzRCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTVDdCU1Q3QlNUN0JTIwJTIwRmliZXJUYXNrUXVldWUuYWRkKCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdGhpcy50YXNrUXVldWUlMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMEZpYmVyVGFza1F1ZXVlJTNCJTVDbiU3RCgpKSUzQiU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwRmliZXJUYXNrUXVldWUlMjAlN0QlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlMy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMHRlc3QoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwJ2EnJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

### Expected Behavior
only have 
```
function test() {
	return 'a';
}

export { test };
```
### Actual Behavior
not only test function but also class 

if static method is replaced with instance method(or if static method in class was not used), it works right.  Anybody knows why?

### LINKED ISSUE #4016: Assignments to side-effecting getters in class prototypes can be incorrectly tree-shaken
- Rollup Version: 2.42.4
- Operating System (or Browser): Any
- Node Version (if applicable): Any
- Link to reproduction (IMPORTANT, read below): [link](https://605c3fa99677b800085f7f45--rollup.netlify.app/repl/?version=2.42.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMGdldCUyMGJhcigpJTIwJTdCJTIwY29uc29sZS5sb2coJTVDJTIyV09PJTVDJTIyKSUyMCU3RCU1Q24lN0QlNUNuRm9vLnByb3RvdHlwZS5iYXIlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

### Expected Behavior

The code should exhibit a side effect (running `console.log`).

### Actual Behavior

Rollup removes the entire program and emits an empty chunk.

This is caused by `ClassNode.hasEffectsWhenAccessedAtPath` being too liberal, but I expect just tightening that up the obvious way will cause significant regressions in tree-shaking on some code. We may have to start tracking class instance properties to properly fix this without regressing.

### PR DESCRIPTION
**Pull request by marijnh**
This PR contains:
- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers: 
Resolves #3989 
Resolves #3250 
Resolves #4016

### Updated Description

**To try out this PR before it is released, use `npm install rollup@beta`.**

#### Core Changes

After being taken over, this PR has been very much extended beyond the original scope. Under the hood, two core changes have been introduced:
* All AST nodes, variables and virtual entities now inherit from a basic `ExpressionEntity` that follows a "conservative by default" approach. I.e. a node that does not implement any methods of its own will behave identical to an "unknown expression" meaning any call, assignment or even access to this node is a side-effect and we treat it as an "unknown value" in conditionals.
* There is now a shared `ObjectEntity` that implements object-like behaviour with regard to property access that is used by object literals, array literals, classes and virtual object and arrays generated by builtin methods. In the future, I hope to extend this to functions as well. This means that improving the behaviour of objects means just working on the ObjectEntity.
* All deoptimization now happens lazily, e.g. assignments in dead code will no longer mess up the analysis.

#### New Features
* Static-effect free methods and properties of classes can now be detected: [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMG5vRWZmZWN0KCklN0IlN0QlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdCgpJTIwJTdCJTVDbiU1Q3QlMjAlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuJTVDdCU3RCU1Q24lNUN0c3RhdGljJTIwbm9FZmZlY3RQcm9wJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlM0IlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdFByb3AlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCdlZmZlY3QnKSUzQiU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTVDbkZvby5ub0VmZmVjdCgpJTNCJTVDbkZvby5ub0VmZmVjdFByb3AoKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q25Gb28uZWZmZWN0UHJvcCgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwY2xhc3MlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwZW50aXJlbHklNUNuY2xhc3MlMjBCYXIlMjAlN0IlNUNuJTIwJTIwc3RhdGljJTIwbm9FZmZlY3QoKSU3QiU3RCU1Q24lN0QlNUNuJTVDbkJhci5ub0VmZmVjdCgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMG5vRWZmZWN0KCklN0IlN0QlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdCgpJTIwJTdCJTVDbiU1Q3QlMjAlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuJTVDdCU3RCU1Q24lNUN0c3RhdGljJTIwbm9FZmZlY3RQcm9wJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlM0IlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdFByb3AlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCdlZmZlY3QnKSUzQiU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTVDbkZvby5ub0VmZmVjdCgpJTNCJTVDbkZvby5ub0VmZmVjdFByb3AoKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q25Gb28uZWZmZWN0UHJvcCgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwY2xhc3MlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwZW50aXJlbHklNUNuY2xhc3MlMjBCYXIlMjAlN0IlNUNuJTIwJTIwc3RhdGljJTIwbm9FZmZlY3QoKSU3QiU3RCU1Q24lN0QlNUNuJTVDbkJhci5ub0VmZmVjdCgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
* This also extends to super classes. To that end, we included a concept of prototypes into the new `ObjectEntity` [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBzdGF0aWMlMjBub0VmZmVjdCgpJTdCJTdEJTVDbiU1Q3RzdGF0aWMlMjBlZmZlY3QoKSU3QmNvbnNvbGUubG9nKCdlZmZlY3QnKSU3RCU1Q24lN0QlNUNuY2xhc3MlMjBGb28lMjBleHRlbmRzJTIwU3VwZXJDbGFzcyUyMCU3QiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25Gb28ubm9FZmZlY3QoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBzdGF0aWMlMjBub0VmZmVjdCgpJTdCJTdEJTVDbiU1Q3RzdGF0aWMlMjBlZmZlY3QoKSU3QmNvbnNvbGUubG9nKCdlZmZlY3QnKSU3RCU1Q24lN0QlNUNuY2xhc3MlMjBGb28lMjBleHRlbmRzJTIwU3VwZXJDbGFzcyUyMCU3QiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25Gb28ubm9FZmZlY3QoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
* Side-effect free array elements can now be detected as well [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTdCJTVDbiU1Q3RlZmZlY3QoKSU3QiU1Q24lNUN0JTIwJTIwY29uc29sZS5sb2coJ2VmZmVjdCcpJTNCJTVDbiU1Q3QlN0QlMkMlNUNuJTVDdG5vRWZmZWN0KCklN0IlN0QlNUNuJTdEJTVEJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vJTVCMCU1RC5lZmZlY3QoKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2hpbGUlMjB0aGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25mb28lNUIwJTVELm5vRWZmZWN0KCklNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwYWx0b2dldGhlciU1Q25jb25zdCUyMGJhciUyMCUzRCUyMCU1QigpJTIwJTNEJTNFJTIwJTdCJTdEJTJDJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlNUQlM0IlNUNuYmFyJTVCMCU1RCgpJTNCJTVDbmJhciU1QiU1QyUyMjElNUMlMjIlNUQoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTdCJTVDbiU1Q3RlZmZlY3QoKSU3QiU1Q24lNUN0JTIwJTIwY29uc29sZS5sb2coJ2VmZmVjdCcpJTNCJTVDbiU1Q3QlN0QlMkMlNUNuJTVDdG5vRWZmZWN0KCklN0IlN0QlNUNuJTdEJTVEJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vJTVCMCU1RC5lZmZlY3QoKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2hpbGUlMjB0aGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25mb28lNUIwJTVELm5vRWZmZWN0KCklNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwYWx0b2dldGhlciU1Q25jb25zdCUyMGJhciUyMCUzRCUyMCU1QigpJTIwJTNEJTNFJTIwJTdCJTdEJTJDJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlNUQlM0IlNUNuYmFyJTVCMCU1RCgpJTNCJTVDbmJhciU1QiU1QyUyMjElNUMlMjIlNUQoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
* Getter and setter handling has been greatly expanded. The new "conservative by default" approach will even handle getters that are created within unknown functions  [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHVua25vd24lMjBmcm9tJTIwJ2V4dGVybmFsJyUzQiU1Q24lNUNuY29uc3QlMjBmb28lMjAlM0QlMjAlN0IlN0QlM0IlNUNuT2JqZWN0LmRlZmluZVByb3BlcnR5KGZvbyUyQyUyMCdwcm9wJyUyQyUyMCU3QiU1Q24lNUN0Z2V0KCklN0IlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklMjAlN0QlNUNuJTdEKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vLnByb3AlM0IlNUNuJTVDbmNvbnN0JTIwYmFyJTIwJTNEJTIwJTdCJTdEJTNCJTVDbnVua25vd24oYmFyKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlMjBhcyUyMHdlbGwlMjBiZWNhdXNlJTIwd2UlMjBkbyUyMG5vdCUyMGtub3clMjB3aGF0JTIwJTVDJTIydW5rbm93biU1QyUyMiUyMGRvZXMlNUNuYmFyLnByb3AlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHVua25vd24lMjBmcm9tJTIwJ2V4dGVybmFsJyUzQiU1Q24lNUNuY29uc3QlMjBmb28lMjAlM0QlMjAlN0IlN0QlM0IlNUNuT2JqZWN0LmRlZmluZVByb3BlcnR5KGZvbyUyQyUyMCdwcm9wJyUyQyUyMCU3QiU1Q24lNUN0Z2V0KCklN0IlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklMjAlN0QlNUNuJTdEKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vLnByb3AlM0IlNUNuJTVDbmNvbnN0JTIwYmFyJTIwJTNEJTIwJTdCJTdEJTNCJTVDbnVua25vd24oYmFyKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlMjBhcyUyMHdlbGwlMjBiZWNhdXNlJTIwd2UlMjBkbyUyMG5vdCUyMGtub3clMjB3aGF0JTIwJTVDJTIydW5rbm93biU1QyUyMiUyMGRvZXMlNUNuYmFyLnByb3AlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)
* Rollup is now able to precisely track mutations in methods, getters and setters via their "this" context [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqMSUyMCUzRCUyMCU3QiU1Q24lMjAlMjBmbGFnMSUzQSUyMGZhbHNlJTJDJTVDbiU1Q3RmbGFnMiUzQSUyMGZhbHNlJTJDJTVDbiU1Q3R0b2dnbGUoKSUyMCU3QiU1Q24lNUN0JTIwJTIwdGhpcy5mbGFnMSUyMCUzRCUyMHRydWUlM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwb25seSUyMGRlb3B0aW1pemUlMjB0aGUlMjAlNUMlMjJmbGFnMSU1QyUyMiUyMHByb3BlcnR5JTVDbm9iajEudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMS5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajEuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwJTVDJTIydGhpcyU1QyUyMiUyMGhhbmRsaW5nJTIwaXMlMjBub3QlMjB0aWVkJTIwdG8lMjB0aGUlMjBvcmlnaW5hbCUyMG9iamVjdCU1Q25jb25zdCUyMG9iajIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwZmxhZzElM0ElMjBmYWxzZSUyQyU1Q24lNUN0ZmxhZzIlM0ElMjBmYWxzZSUyQyU1Q24lNUN0dG9nZ2xlJTNBJTIwb2JqMS50b2dnbGUlNUNuJTdEJTNCJTVDbm9iajIudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMi5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajIuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2UlMjBjYW4lMjBhbHNvJTIwZG8lMjB0aGlzJTIwZm9yJTIwZ2V0dGVycyUyMGFuZCUyMHNldHRlcnMlNUNuY29uc3QlMjBvYmozJTIwJTNEJTIwJTdCJTVDbiUyMCUyMGZsYWcxJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWcyJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWczJTNBJTIwZmFsc2UlMkMlNUNuJTVDdHNldCUyMHNldHRlcih2YWx1ZSklMjAlN0J0aGlzLmZsYWcxJTIwJTNEJTIwdmFsdWUlN0QlMkMlNUNuJTVDdGdldCUyMGdldHRlcigpJTIwJTdCdGhpcy5mbGFnMiUyMCUzRCUyMHRydWUlN0QlNUNuJTdEJTNCJTVDbiU1Q25vYmozLnNldHRlciUyMCUzRCUyMHRydWUlM0IlNUNub2JqMy5nZXR0ZXIlM0IlNUNuaWYlMjAob2JqMy5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajMuZmxhZzIpJTIwY29uc29sZS5sb2coJ211dGF0aW9uJTIwZGV0ZWN0ZWQnKSUzQiU1Q25pZiUyMChvYmozLmZsYWczKSUyMGNvbnNvbGUubG9nKCdyZW1vdmVkJyklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqMSUyMCUzRCUyMCU3QiU1Q24lMjAlMjBmbGFnMSUzQSUyMGZhbHNlJTJDJTVDbiU1Q3RmbGFnMiUzQSUyMGZhbHNlJTJDJTVDbiU1Q3R0b2dnbGUoKSUyMCU3QiU1Q24lNUN0JTIwJTIwdGhpcy5mbGFnMSUyMCUzRCUyMHRydWUlM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwb25seSUyMGRlb3B0aW1pemUlMjB0aGUlMjAlNUMlMjJmbGFnMSU1QyUyMiUyMHByb3BlcnR5JTVDbm9iajEudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMS5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajEuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwJTVDJTIydGhpcyU1QyUyMiUyMGhhbmRsaW5nJTIwaXMlMjBub3QlMjB0aWVkJTIwdG8lMjB0aGUlMjBvcmlnaW5hbCUyMG9iamVjdCU1Q25jb25zdCUyMG9iajIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwZmxhZzElM0ElMjBmYWxzZSUyQyU1Q24lNUN0ZmxhZzIlM0ElMjBmYWxzZSUyQyU1Q24lNUN0dG9nZ2xlJTNBJTIwb2JqMS50b2dnbGUlNUNuJTdEJTNCJTVDbm9iajIudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMi5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajIuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2UlMjBjYW4lMjBhbHNvJTIwZG8lMjB0aGlzJTIwZm9yJTIwZ2V0dGVycyUyMGFuZCUyMHNldHRlcnMlNUNuY29uc3QlMjBvYmozJTIwJTNEJTIwJTdCJTVDbiUyMCUyMGZsYWcxJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWcyJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWczJTNBJTIwZmFsc2UlMkMlNUNuJTVDdHNldCUyMHNldHRlcih2YWx1ZSklMjAlN0J0aGlzLmZsYWcxJTIwJTNEJTIwdmFsdWUlN0QlMkMlNUNuJTVDdGdldCUyMGdldHRlcigpJTIwJTdCdGhpcy5mbGFnMiUyMCUzRCUyMHRydWUlN0QlNUNuJTdEJTNCJTVDbiU1Q25vYmozLnNldHRlciUyMCUzRCUyMHRydWUlM0IlNUNub2JqMy5nZXR0ZXIlM0IlNUNuaWYlMjAob2JqMy5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajMuZmxhZzIpJTIwY29uc29sZS5sb2coJ211dGF0aW9uJTIwZGV0ZWN0ZWQnKSUzQiU1Q25pZiUyMChvYmozLmZsYWczKSUyMGNvbnNvbGUubG9nKCdyZW1vdmVkJyklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
* Handling for builtin array methods has been extended to track mutations of the original array through methods that return the original array again [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyMFRoaXMlMjBoYXMlMjBubyUyMHNpZGUtZWZmZWN0cyU1Q25mb28uc29ydCgpLmpvaW4oKSUzQiU1Q24lNUNuY29uc3QlMjBiYXIlMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTJGJTJGJTIwQnklMjBvdmVycmlkaW5nJTIwJTVDJTIyam9pbiU1QyUyMiUyQyUyMHdlJTIwaW50cm9kdWNlJTIwYSUyMHNpZGUtZWZmZWN0JTIwdGhhdCUyMGlzJTVDbiUyRiUyRiUyMHZpc2libGUlMjBvbiUyMHRoZSUyMHJldHVybiUyMHZhbHVlJTIwb2YlMjAlNUMlMjJzb3J0JTVDJTIyJTVDbmJhci5qb2luJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmFyLnNvcnQoKS5qb2luKCklM0IlNUNuJTVDbmNvbnN0JTIwYmF6JTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyME90aGVyJTIwcmVhc3NpZ25tZW50cyUyMGRvJTIwbm90JTIwY2F1c2UlMjBzaWRlLWVmZmVjdHMlMkMlMjB0aG91Z2glNUNuYmF6Lm90aGVyJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmF6LnNvcnQoKS5qb2luKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyMFRoaXMlMjBoYXMlMjBubyUyMHNpZGUtZWZmZWN0cyU1Q25mb28uc29ydCgpLmpvaW4oKSUzQiU1Q24lNUNuY29uc3QlMjBiYXIlMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTJGJTJGJTIwQnklMjBvdmVycmlkaW5nJTIwJTVDJTIyam9pbiU1QyUyMiUyQyUyMHdlJTIwaW50cm9kdWNlJTIwYSUyMHNpZGUtZWZmZWN0JTIwdGhhdCUyMGlzJTVDbiUyRiUyRiUyMHZpc2libGUlMjBvbiUyMHRoZSUyMHJldHVybiUyMHZhbHVlJTIwb2YlMjAlNUMlMjJzb3J0JTVDJTIyJTVDbmJhci5qb2luJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmFyLnNvcnQoKS5qb2luKCklM0IlNUNuJTVDbmNvbnN0JTIwYmF6JTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyME90aGVyJTIwcmVhc3NpZ25tZW50cyUyMGRvJTIwbm90JTIwY2F1c2UlMjBzaWRlLWVmZmVjdHMlMkMlMjB0aG91Z2glNUNuYmF6Lm90aGVyJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmF6LnNvcnQoKS5qb2luKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

Possible extensions for future PRs:
* Also use `ObjectEntity` for functions and arrow functions. For now, those will deoptimize completely when properties are assigned.
* Handle assignments to `__proto__` and uses of `Object.setPrototypeOf`/`Object.getPrototypeOf`. In some situations, mutations may still not be detected here. This is a tricky one as technically, passing an object to an unknown method could mutate the object prototype. We will need to think what assumptions we keep in the system, e.g. "builtins always behave as expected". Maybe we add a flag here.
* Track function parameter mutations the same way we track "this" mutations. This will be an important one.

### Original Description (outdated)

Track static class fields and improve handling of class getters/setters

This aims to improve tree-shaking of code that uses static class properties (#3989) and to improve detection of side effects through class getters/setters (#4016).

The first part works by keeping a map of positively known static properties (methods and simple getters) in
`ClassNode.staticPropertyMap`, along with a flag (`ClassNode.deoptimizedStatic`) that indicates that something happened that  removed our confidence that we know anything about the class object.

Access and calls to these known static properties are handled by routing the calls to `getLiteralValueAtPath`, `getReturnExpressionWhenCalledAtPath`, and `hasEffectsWhenCalledAtPath` to the known values in the properties. In contrast to `ObjectExpression`, this class does not try to keep track of multiple expressions associated with a property, since that doesn't come up a lot on classes.

The handling of side effect detection through getters and setters is done by, _if_ the entire class object (or its prototype in case of access to the prototype) hasn't been deoptimized, scanning through the directly defined getters and setters to see if one exists (calling through to superclasses as appropriate). I believe that this is solid because any code that would be able to change the set of getters and setters on a class would cause the entire object to be deoptimized.

### CODE REVIEW

**Comment by marijnh** [comment]
#4011 was merged. I'll tweak tests to improve coverage and push again.

**Comment by marijnh** [comment]
I was unable to create tests that run `deoptimizeCache` on a `ClassNode`. It also seems like, at least in this context, `hasEffectsWhenAssignedAtPath` is not called when `hasEffectsWhenAccessedAtPath` returns true for a given assignment. Thus there are a bunch of non-covered lines in the new code. Let me know if I can do something reasonable about them.

File: src/ast/nodes/shared/ClassNode.ts [hunk 1]
```diff
@@ -1,47 +1,242 @@
...
+		if (!definition || this.deoptimizedStatic) return true;
+		return definition.mayModifyThisWhenCalledAtPath(path.slice(1));
+	}
+
+	private getStaticPropertyMap(): {[name: string]: ExpressionNode} {
+		if (this.staticPropertyMap) return this.staticPropertyMap;
+
+		const propertyMap = this.staticPropertyMap = Object.create(null);
+		const seen: {[name: string]: boolean} = Object.create(null);
+		for (const definition of this.body.body) {
```
Comment (lukastaegert) [inline src/ast/nodes/shared/ClassNode.ts:200]: Can this be done by building an up-front lookup table similar to how we do this for object expression? For classes with many definitions, this will scale badly as `mayModifyThisWhenCalledAtPath` is called during tree-shaking with potentially many passes (dozens in larger code bases) with potentially many calls per pass. This is a highly performance critical code path.
Maybe some code can be even extracted from/shared with object expression. The object expression logic is indeed very powerful as it will also pre-resolve computed properties if possible, handle quoted properties, handle multiple definitions of the same name and handle unknown computed properties that might overwrite previous properties.

File: src/ast/nodes/shared/ClassNode.ts [hunk 2]
```diff
@@ -1,47 +1,242 @@
...
+		return this.staticPropertyMap = propertyMap;
+	}
+}
+
+function mayHaveGetterSetterEffect(
+	body: ClassBody,
+	kind: 'get' | 'set', isStatic: boolean, name: string,
+	context: HasEffectsContext
+) {
+	for (const definition of body.body) {
```
Comment (lukastaegert) [inline src/ast/nodes/shared/ClassNode.ts:230]: Again this could benefit from a pre-built lookup table.

File: src/ast/nodes/shared/ClassNode.ts [hunk 3]
```diff
@@ -1,47 +1,242 @@
...
-		return path.length > 2 || path[0] !== 'prototype';
+	deoptimizeAllStatics() {
+		for (const name in this.staticPropertyMap) {
+			this.deoptimizeStatic(name);
+		}
+		this.deoptimizedStatic = this.deoptimizedPrototype = true;
+	}
+
+	deoptimizeCache() {
+		this.deoptimizeAllStatics();
```
Comment (lukastaegert) [inline src/ast/nodes/shared/ClassNode.ts:43]: I do not believe this is necessary unless you rely on retrieving literal values for computed properties. That is also why you cannot test it.

So it works like this:
When you perform a `getLiteralValueAtPath` or a `getReturnExpressionWhenCalledAtPath` you pass a `DeoptimizableEntity` as the last parameter (which is usually the Node requesting the literal/return value). The reason is that it is possible a literal/return value might be deoptimized at a later time when binding/tree-shaking progresses. If that happens, then some Node down the chain that is responsible for the deoptimization will call `deoptimizeCache` on this entity. At this point in time, the entity is responsible for "forgetting" the cached value and also deoptimize the cache of all dependent entities that may rely on that value.

Admittedly it is kind of difficult to describe such deoptimization scenarios. Ideally I would just put a breakpoint into "deoptimizeCache" of ObjectExpression and see what test triggers it.

This will become even more important in the future as one goal is to move more and more of the initial deoptimizations to "on demand late deoptimization" i.e. only deoptimize when as reassignment is included.

File: src/ast/nodes/shared/ClassNode.ts (hunk 1 above)
Comment (marijnh) [reply src/ast/nodes/shared/ClassNode.ts:200]: I decided against sharing code with ObjectExpression because there's a lot of small differences between how this works and how objects work (in syntax tree shape, handling of builtin properties, static/prototype distinction, and so on) and the helper functions would become monsters with a list of boolean parameters, and I prefer some vague duplication over that most of the time.

Building up a table is probably a good idea. Looking into that.

Comment (marijnh) [reply src/ast/nodes/shared/ClassNode.ts:200]: Wait, the thing you're commenting on here _is_ building up a table. The suggestions holds for `mayHaveGetterSetterEffect`, but, as far as I can see, only there.

File: src/ast/nodes/shared/ClassNode.ts (hunk 3 above)
Comment (marijnh) [reply src/ast/nodes/shared/ClassNode.ts:43]: > I do not believe this is necessary unless you rely on retrieving literal values for computed properties.

You mean this is only necessary for nodes that themselves retrieve literal values? Do I understand correctly that the call-throughs to definition nodes in the class' own `getLiteralValueAtPath` and `getReturnExpressionWhenCalledAtPath` don't count because they just pass through their argument instead of passing themselves?

**Comment by marijnh** [comment]
Attached patches drop the `deoptimizeCache` method and optimize getter/setter lookup with a table.

**Comment by marijnh** [comment]
Rebased onto current master branch and added the new argument to `mayModifyThisWhenCalledAtPath`.

**Comment by lukastaegert** [comment]
Sorry the review takes some time, but I want to test it thoroughly. It is very capable, here are some of my findings so far (The REPL is using your PR via its CircleCI build number):

Reassigning the prototype of a class throws in strict mode, which means it should likely be retained even if the class is not used (but I do not think this is critical):
https://rollupjs.org/repl/?circleci=14744&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTdEJTVDbiUyRiUyRiUyMFRoaXMlMjB3b3VsZCUyMHRocm93JTIwaW4lMjBhJTIwbW9kdWxlJTVDbkZvby5wcm90b3R5cGUlMjAlM0QlMjBudWxsJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

While the logic is able to trace values through class properties, it still thinks reading those values has a side-effect. I would think this can be fixed by relaying the check to the actual property method definition. Of course it would mean extending `PropertyDefinition` to support that.
https://rollupjs.org/repl/?circleci=14744&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMGZvbyUyMCUzRCUyMCU3QmJhciUzQSUyMHRydWUlN0QlM0IlNUNuJTdEJTVDbiU1Q24lMkYlMkYlMjBUaGVyZSUyMGlzJTIwbm8lMjByZWFzb24lMjB0byUyMHJldGFpbiUyMHRoZSUyMGNvbmRpdGlvbiUyMGhlcmUlNUNuaWYlMjAoRm9vLmZvby5iYXIpJTIwY29uc29sZS5sb2coJ3ZhbHVlJTIwaXMlMjB0cnVlJyklNUNuZWxzZSUyMGNvbnNvbGUubG9nKCd2YWx1ZSUyMGlzJTIwZmFsc2UnKSUzQiU1Q24lNUNuJTJGJTJGJTIwT3IlMjB0aGUlMjByaWdodC1oYW5kJTIwc2lkZSUyMGhlcmUlNUNuY29uc3QlMjB1bnVzZWQxJTIwJTNEJTIwRm9vLmZvby5wcm9wZXJ0eSUzQiU1Q24lNUNuY2xhc3MlMjBCYXIlMjAlN0IlNUNuJTIwJTIwc3RhdGljJTIwZm9vJTIwJTNEJTIwJTdCYmFyJTNBJTIwdHJ1ZSU3RCUzQiU1Q24lN0QlNUNuJTVDbkJhci5mb28lMjAlM0QlMjBudWxsJTNCJTVDbiU1Q24lMkYlMkYlMjBIZXJlJTIwdGhlJTIwcmlnaHQtaGFuZCUyMHNpZGUlMjBzaG91bGQlMjBiZSUyMHJldGFpbmVkJTVDbmNvbnN0JTIwdW51c2VkMiUyMCUzRCUyMEJhci5mb28ucHJvcGVydHklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

In general with regard to getter/setter handling, I wonder if we could not build a single table to handle everything just like ObjectExpression does it? I know it moves complexity a little, but it also makes it easier to compare the logic of the two, and it might even be faster as it only does a single iteration (if you think the logic in ObjectExpression could be made easier to understand e.g. by choosing better names or a better table layout, that would be welcome as well).

Will continue later.

**Comment by marijnh** [comment]
> In general with regard to getter/setter handling, I wonder if we could not build a single table to handle everything just like ObjectExpression does it?

I'm open to that, but there's so much going on there that I couldn't figure out what the system used there works like. If you could do a quick rundown of that logic, I'll take a look.

**Comment by lukastaegert** [comment]
As I often find myself looking up the logic again, I pushed a comment explaining the logic to `ObjectExpression` on your branch. I hope this helps. If you have an idea for better names or a better algorithm, let me know.

As a matter of fact, I just discovered that the implementation has a bug because apparently

```js
var obj = {
  foo: 'value',
  set foo(value) {}
}
console.log(obj.foo);
```

will not log `value` but `undefined` (but it does not throw! Even if the first property were missing). Only if the first property is a getter it actually logs `value`. Not yet sure how to adapt the algorithm to accommodate that. If there is a regular property followed by a getter it works correctly though. In that case, writing the property does not throw, but the value is lost anyway.

**Comment by marijnh** [comment]
Thanks for those clarifications. Unfortunately, I still find the `ObjectExpression` property tracking very daunting, with lots of subtle corner cases, and I'm just not confident I could reproduce (or share) that logic in the class property tracking without introducing a bunch of new bugs.

And since I also found out that, even with the extensions proposed in this PR, Rollup still won't remove the calls that motivated this work (due to dereferencing an object parameter), I'm not really motivated to continue on this. Feel free to close it or to keep it around for future reference. Sorry for wasting your time.

(As a general—probably quite unhelpful—observation, I think the library would benefit from a more rigorous abstract interpretation framework, as the current approach, which I assume grew organically as new requirements come up, doesn't really seem to be up to the complicated uses that are being made of it. But of course that kind of overhaul would be a huge amount of work, and who has time for that.)

**Comment by lukastaegert** [comment]
Yes I understand. Please leave this PR open, I will try to take it over in the next days.

> As a general—probably quite unhelpful—observation, I think the library would benefit from a more rigorous abstract interpretation framework

Probably, and there will be larger refactorings in the future as there have been in the past. However for the sake of continuous improvement in smaller steps, one takeaway from this story would be that we would benefit from an abstract "JavaScript object" data type/class/... where nodes like `ObjectExpression` or `ClassNode` just build a common data structure with the necessary information while a shared logic handles side effect detection. This could then be reused for all object-like types there are, e.g. `FunctionNode`, `ArrayExpression` etc.

**Comment by lukastaegert** [comment]
Breaking with the rule of "keeping a PR minimal and to the point", I have abused this PR now to also fix quite a few issues in Rollup around the use of getters and setters. I also released a pre-release version you can try via `npm install rollup@beta`.

This is now ready for release, but I will keep it open for a few days before doing so to let people give it a spin.

#### Core Changes

After being taken over, this PR has been very much extended beyond the original scope. Under the hood, two core changes have been introduced:
* All AST nodes, variables and virtual entities now inherit from a basic `ExpressionEntity` that follows a "conservative by default" approach. I.e. a node that does not implement any methods of its own will behave identical to an "unknown expression" meaning any call, assignment or even access to this node is a side-effect and we treat it as an "unknown value" in conditionals.
* There is now a shared `ObjectEntity` that implements object-like behaviour with regard to property access that is used by object literals, array literals, classes and virtual object and arrays generated by builtin methods. In the future, I hope to extend this to functions as well. This means that improving the behaviour of objects means just working on the ObjectEntity.

#### New Features
* Static-effect free methods and properties of classes can now be detected: [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMG5vRWZmZWN0KCklN0IlN0QlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdCgpJTIwJTdCJTVDbiU1Q3QlMjAlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuJTVDdCU3RCU1Q24lNUN0c3RhdGljJTIwbm9FZmZlY3RQcm9wJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlM0IlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdFByb3AlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCdlZmZlY3QnKSUzQiU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTVDbkZvby5ub0VmZmVjdCgpJTNCJTVDbkZvby5ub0VmZmVjdFByb3AoKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q25Gb28uZWZmZWN0UHJvcCgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwY2xhc3MlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwZW50aXJlbHklNUNuY2xhc3MlMjBCYXIlMjAlN0IlNUNuJTIwJTIwc3RhdGljJTIwbm9FZmZlY3QoKSU3QiU3RCU1Q24lN0QlNUNuJTVDbkJhci5ub0VmZmVjdCgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMG5vRWZmZWN0KCklN0IlN0QlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdCgpJTIwJTdCJTVDbiU1Q3QlMjAlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuJTVDdCU3RCU1Q24lNUN0c3RhdGljJTIwbm9FZmZlY3RQcm9wJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlM0IlNUNuJTVDdHN0YXRpYyUyMGVmZmVjdFByb3AlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKCdlZmZlY3QnKSUzQiU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTVDbkZvby5ub0VmZmVjdCgpJTNCJTVDbkZvby5ub0VmZmVjdFByb3AoKSUzQiU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q25Gb28uZWZmZWN0UHJvcCgpJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwY2xhc3MlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwZW50aXJlbHklNUNuY2xhc3MlMjBCYXIlMjAlN0IlNUNuJTIwJTIwc3RhdGljJTIwbm9FZmZlY3QoKSU3QiU3RCU1Q24lN0QlNUNuJTVDbkJhci5ub0VmZmVjdCgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
* This also extends to super classes. To that end, we included a concept of prototypes into the new `ObjectEntity` [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBzdGF0aWMlMjBub0VmZmVjdCgpJTdCJTdEJTVDbiU1Q3RzdGF0aWMlMjBlZmZlY3QoKSU3QmNvbnNvbGUubG9nKCdlZmZlY3QnKSU3RCU1Q24lN0QlNUNuY2xhc3MlMjBGb28lMjBleHRlbmRzJTIwU3VwZXJDbGFzcyUyMCU3QiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25Gb28ubm9FZmZlY3QoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwU3VwZXJDbGFzcyUyMCU3QiU1Q24lMjAlMjBzdGF0aWMlMjBub0VmZmVjdCgpJTdCJTdEJTVDbiU1Q3RzdGF0aWMlMjBlZmZlY3QoKSU3QmNvbnNvbGUubG9nKCdlZmZlY3QnKSU3RCU1Q24lN0QlNUNuY2xhc3MlMjBGb28lMjBleHRlbmRzJTIwU3VwZXJDbGFzcyUyMCU3QiU3RCU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMHdpbGwlMjBiZSUyMHJldGFpbmVkJTVDbkZvby5lZmZlY3QoKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25Gb28ubm9FZmZlY3QoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
* Side-effect free array elements can now be detected as well [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTdCJTVDbiU1Q3RlZmZlY3QoKSU3QiU1Q24lNUN0JTIwJTIwY29uc29sZS5sb2coJ2VmZmVjdCcpJTNCJTVDbiU1Q3QlN0QlMkMlNUNuJTVDdG5vRWZmZWN0KCklN0IlN0QlNUNuJTdEJTVEJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vJTVCMCU1RC5lZmZlY3QoKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2hpbGUlMjB0aGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25mb28lNUIwJTVELm5vRWZmZWN0KCklNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwYWx0b2dldGhlciU1Q25jb25zdCUyMGJhciUyMCUzRCUyMCU1QigpJTIwJTNEJTNFJTIwJTdCJTdEJTJDJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlNUQlM0IlNUNuYmFyJTVCMCU1RCgpJTNCJTVDbmJhciU1QiU1QyUyMjElNUMlMjIlNUQoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTdCJTVDbiU1Q3RlZmZlY3QoKSU3QiU1Q24lNUN0JTIwJTIwY29uc29sZS5sb2coJ2VmZmVjdCcpJTNCJTVDbiU1Q3QlN0QlMkMlNUNuJTVDdG5vRWZmZWN0KCklN0IlN0QlNUNuJTdEJTVEJTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vJTVCMCU1RC5lZmZlY3QoKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2hpbGUlMjB0aGlzJTIwd2lsbCUyMGJlJTIwcmVtb3ZlZCU1Q25mb28lNUIwJTVELm5vRWZmZWN0KCklNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwYmUlMjByZW1vdmVkJTIwYWx0b2dldGhlciU1Q25jb25zdCUyMGJhciUyMCUzRCUyMCU1QigpJTIwJTNEJTNFJTIwJTdCJTdEJTJDJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlNUQlM0IlNUNuYmFyJTVCMCU1RCgpJTNCJTVDbmJhciU1QiU1QyUyMjElNUMlMjIlNUQoKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
* Getter and setter handling has been greatly expanded. The new "conservative by default" approach will even handle getters that are created within unknown functions  [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHVua25vd24lMjBmcm9tJTIwJ2V4dGVybmFsJyUzQiU1Q24lNUNuY29uc3QlMjBmb28lMjAlM0QlMjAlN0IlN0QlM0IlNUNuT2JqZWN0LmRlZmluZVByb3BlcnR5KGZvbyUyQyUyMCdwcm9wJyUyQyUyMCU3QiU1Q24lNUN0Z2V0KCklN0IlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklMjAlN0QlNUNuJTdEKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vLnByb3AlM0IlNUNuJTVDbmNvbnN0JTIwYmFyJTIwJTNEJTIwJTdCJTdEJTNCJTVDbnVua25vd24oYmFyKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlMjBhcyUyMHdlbGwlMjBiZWNhdXNlJTIwd2UlMjBkbyUyMG5vdCUyMGtub3clMjB3aGF0JTIwJTVDJTIydW5rbm93biU1QyUyMiUyMGRvZXMlNUNuYmFyLnByb3AlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHVua25vd24lMjBmcm9tJTIwJ2V4dGVybmFsJyUzQiU1Q24lNUNuY29uc3QlMjBmb28lMjAlM0QlMjAlN0IlN0QlM0IlNUNuT2JqZWN0LmRlZmluZVByb3BlcnR5KGZvbyUyQyUyMCdwcm9wJyUyQyUyMCU3QiU1Q24lNUN0Z2V0KCklN0IlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklMjAlN0QlNUNuJTdEKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlNUNuZm9vLnByb3AlM0IlNUNuJTVDbmNvbnN0JTIwYmFyJTIwJTNEJTIwJTdCJTdEJTNCJTVDbnVua25vd24oYmFyKSUzQiU1Q24lMkYlMkYlMjBUaGlzJTIwd2lsbCUyMGJlJTIwcmV0YWluZWQlMjBhcyUyMHdlbGwlMjBiZWNhdXNlJTIwd2UlMjBkbyUyMG5vdCUyMGtub3clMjB3aGF0JTIwJTVDJTIydW5rbm93biU1QyUyMiUyMGRvZXMlNUNuYmFyLnByb3AlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)
* Rollup is now able to precisely track mutations in methods, getters and setters via their "this" context [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqMSUyMCUzRCUyMCU3QiU1Q24lMjAlMjBmbGFnMSUzQSUyMGZhbHNlJTJDJTVDbiU1Q3RmbGFnMiUzQSUyMGZhbHNlJTJDJTVDbiU1Q3R0b2dnbGUoKSUyMCU3QiU1Q24lNUN0JTIwJTIwdGhpcy5mbGFnMSUyMCUzRCUyMHRydWUlM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwb25seSUyMGRlb3B0aW1pemUlMjB0aGUlMjAlNUMlMjJmbGFnMSU1QyUyMiUyMHByb3BlcnR5JTVDbm9iajEudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMS5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajEuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwJTVDJTIydGhpcyU1QyUyMiUyMGhhbmRsaW5nJTIwaXMlMjBub3QlMjB0aWVkJTIwdG8lMjB0aGUlMjBvcmlnaW5hbCUyMG9iamVjdCU1Q25jb25zdCUyMG9iajIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwZmxhZzElM0ElMjBmYWxzZSUyQyU1Q24lNUN0ZmxhZzIlM0ElMjBmYWxzZSUyQyU1Q24lNUN0dG9nZ2xlJTNBJTIwb2JqMS50b2dnbGUlNUNuJTdEJTNCJTVDbm9iajIudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMi5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajIuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2UlMjBjYW4lMjBhbHNvJTIwZG8lMjB0aGlzJTIwZm9yJTIwZ2V0dGVycyUyMGFuZCUyMHNldHRlcnMlNUNuY29uc3QlMjBvYmozJTIwJTNEJTIwJTdCJTVDbiUyMCUyMGZsYWcxJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWcyJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWczJTNBJTIwZmFsc2UlMkMlNUNuJTVDdHNldCUyMHNldHRlcih2YWx1ZSklMjAlN0J0aGlzLmZsYWcxJTIwJTNEJTIwdmFsdWUlN0QlMkMlNUNuJTVDdGdldCUyMGdldHRlcigpJTIwJTdCdGhpcy5mbGFnMiUyMCUzRCUyMHRydWUlN0QlNUNuJTdEJTNCJTVDbiU1Q25vYmozLnNldHRlciUyMCUzRCUyMHRydWUlM0IlNUNub2JqMy5nZXR0ZXIlM0IlNUNuaWYlMjAob2JqMy5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajMuZmxhZzIpJTIwY29uc29sZS5sb2coJ211dGF0aW9uJTIwZGV0ZWN0ZWQnKSUzQiU1Q25pZiUyMChvYmozLmZsYWczKSUyMGNvbnNvbGUubG9nKCdyZW1vdmVkJyklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqMSUyMCUzRCUyMCU3QiU1Q24lMjAlMjBmbGFnMSUzQSUyMGZhbHNlJTJDJTVDbiU1Q3RmbGFnMiUzQSUyMGZhbHNlJTJDJTVDbiU1Q3R0b2dnbGUoKSUyMCU3QiU1Q24lNUN0JTIwJTIwdGhpcy5mbGFnMSUyMCUzRCUyMHRydWUlM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjB3aWxsJTIwb25seSUyMGRlb3B0aW1pemUlMjB0aGUlMjAlNUMlMjJmbGFnMSU1QyUyMiUyMHByb3BlcnR5JTVDbm9iajEudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMS5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajEuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwJTVDJTIydGhpcyU1QyUyMiUyMGhhbmRsaW5nJTIwaXMlMjBub3QlMjB0aWVkJTIwdG8lMjB0aGUlMjBvcmlnaW5hbCUyMG9iamVjdCU1Q25jb25zdCUyMG9iajIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwZmxhZzElM0ElMjBmYWxzZSUyQyU1Q24lNUN0ZmxhZzIlM0ElMjBmYWxzZSUyQyU1Q24lNUN0dG9nZ2xlJTNBJTIwb2JqMS50b2dnbGUlNUNuJTdEJTNCJTVDbm9iajIudG9nZ2xlKCklM0IlNUNuaWYlMjAob2JqMi5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajIuZmxhZzIpJTIwY29uc29sZS5sb2coJ3JlbW92ZWQnKSUzQiU1Q24lNUNuJTJGJTJGJTIwV2UlMjBjYW4lMjBhbHNvJTIwZG8lMjB0aGlzJTIwZm9yJTIwZ2V0dGVycyUyMGFuZCUyMHNldHRlcnMlNUNuY29uc3QlMjBvYmozJTIwJTNEJTIwJTdCJTVDbiUyMCUyMGZsYWcxJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWcyJTNBJTIwZmFsc2UlMkMlNUNuJTVDdGZsYWczJTNBJTIwZmFsc2UlMkMlNUNuJTVDdHNldCUyMHNldHRlcih2YWx1ZSklMjAlN0J0aGlzLmZsYWcxJTIwJTNEJTIwdmFsdWUlN0QlMkMlNUNuJTVDdGdldCUyMGdldHRlcigpJTIwJTdCdGhpcy5mbGFnMiUyMCUzRCUyMHRydWUlN0QlNUNuJTdEJTNCJTVDbiU1Q25vYmozLnNldHRlciUyMCUzRCUyMHRydWUlM0IlNUNub2JqMy5nZXR0ZXIlM0IlNUNuaWYlMjAob2JqMy5mbGFnMSklMjBjb25zb2xlLmxvZygnbXV0YXRpb24lMjBkZXRlY3RlZCcpJTNCJTVDbmlmJTIwKG9iajMuZmxhZzIpJTIwY29uc29sZS5sb2coJ211dGF0aW9uJTIwZGV0ZWN0ZWQnKSUzQiU1Q25pZiUyMChvYmozLmZsYWczKSUyMGNvbnNvbGUubG9nKCdyZW1vdmVkJyklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)
* Handling for builtin array methods has been extended to track mutations of the original array through methods that return the original array again [Updated REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyMFRoaXMlMjBoYXMlMjBubyUyMHNpZGUtZWZmZWN0cyU1Q25mb28uc29ydCgpLmpvaW4oKSUzQiU1Q24lNUNuY29uc3QlMjBiYXIlMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTJGJTJGJTIwQnklMjBvdmVycmlkaW5nJTIwJTVDJTIyam9pbiU1QyUyMiUyQyUyMHdlJTIwaW50cm9kdWNlJTIwYSUyMHNpZGUtZWZmZWN0JTIwdGhhdCUyMGlzJTVDbiUyRiUyRiUyMHZpc2libGUlMjBvbiUyMHRoZSUyMHJldHVybiUyMHZhbHVlJTIwb2YlMjAlNUMlMjJzb3J0JTVDJTIyJTVDbmJhci5qb2luJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmFyLnNvcnQoKS5qb2luKCklM0IlNUNuJTVDbmNvbnN0JTIwYmF6JTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyME90aGVyJTIwcmVhc3NpZ25tZW50cyUyMGRvJTIwbm90JTIwY2F1c2UlMjBzaWRlLWVmZmVjdHMlMkMlMjB0aG91Z2glNUNuYmF6Lm90aGVyJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmF6LnNvcnQoKS5qb2luKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE), [v2.48.0 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZm9vJTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyMFRoaXMlMjBoYXMlMjBubyUyMHNpZGUtZWZmZWN0cyU1Q25mb28uc29ydCgpLmpvaW4oKSUzQiU1Q24lNUNuY29uc3QlMjBiYXIlMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTJGJTJGJTIwQnklMjBvdmVycmlkaW5nJTIwJTVDJTIyam9pbiU1QyUyMiUyQyUyMHdlJTIwaW50cm9kdWNlJTIwYSUyMHNpZGUtZWZmZWN0JTIwdGhhdCUyMGlzJTVDbiUyRiUyRiUyMHZpc2libGUlMjBvbiUyMHRoZSUyMHJldHVybiUyMHZhbHVlJTIwb2YlMjAlNUMlMjJzb3J0JTVDJTIyJTVDbmJhci5qb2luJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmFyLnNvcnQoKS5qb2luKCklM0IlNUNuJTVDbmNvbnN0JTIwYmF6JTIwJTNEJTIwJTVCJTVEJTNCJTVDbiUyRiUyRiUyME90aGVyJTIwcmVhc3NpZ25tZW50cyUyMGRvJTIwbm90JTIwY2F1c2UlMjBzaWRlLWVmZmVjdHMlMkMlMjB0aG91Z2glNUNuYmF6Lm90aGVyJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZygnZWZmZWN0JyklM0IlNUNuYmF6LnNvcnQoKS5qb2luKCklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Review by lukastaegert — APPROVED** [review]

**Comment by marijnh** [comment]
Thanks for continuing this after I gave up. The changes sound like they address a number of the pain points I ran into. I tried bundling a bunch of my projects with the beta and ran their tests without seeing any regressions.

**Comment by lukastaegert** [comment]
One improvement I forgot to list is that now all deoptimization happens lazily, i.e. all assignments in dead code will no longer mess up the analysis. Before, these kinds of deoptimizations were happening during the "bind" phase, which was causing its own bunch of issues. Now, the "bind" phase is solely for binding variables to nodes as it was originally intended :)

**Comment by dasa** [comment]
I think I've found a regression in this PR where it's not tracking the items pushed to an array.

[2.48 REPL](https://rollupjs.org/repl/?version=2.48.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwdGVzdChudW0xJTJDJTIwbnVtMiklMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBudW1UeXBlcyUyMCUzRCUyMCU1QiU1RCUzQiU1Q24lMjAlMjBsZXQlMjBlcnJvciUyMCUzRCUyMG51bGwlM0IlNUNuJTVDbiUyMCUyMGNvbnN0JTIwdmFsaWROdW1zJTIwJTNEJTIwJTVCbnVtMSUyQyUyMG51bTIlNUQuZXZlcnkoKG51bSklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBudW1UeXBlJTIwJTNEJTIwbnVtJTIwJTNFJTIwMCUyMCUzRiUyMCU1QyUyMnAlNUMlMjIlMjAlM0ElMjBudW0lMjAlM0MlMjAwJTIwJTNGJTIwJTVDJTIybiU1QyUyMiUyMCUzQSUyMDAlM0IlNUNuJTVDbiUyMCUyMCUyMCUyMGlmJTIwKG51bVR5cGUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG51bVR5cGVzLnB1c2gobnVtVHlwZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAhIW51bVR5cGUlM0IlNUNuJTIwJTIwJTdEKSUzQiU1Q24lNUNuJTIwJTIwaWYlMjAoIXZhbGlkTnVtcyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwZXJyb3IlMjAlM0QlMjAlNUMlMjJmb28lNUMlMjIlM0IlNUNuJTIwJTIwJTdEJTIwZWxzZSUyMGlmJTIwKG51bVR5cGVzJTVCMCU1RCUyMCUzRCUzRCUzRCUyMG51bVR5cGVzJTVCMSU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwZXJyb3IlMjAlM0QlMjAlNUMlMjJiYXIlNUMlMjIlM0IlNUNuJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjByZXR1cm4lMjBlcnJvciUzQiU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKHRlc3QoMSUyQyUyMDIpKSUzQiU1Q24lNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

[PR REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwdGVzdChudW0xJTJDJTIwbnVtMiklMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBudW1UeXBlcyUyMCUzRCUyMCU1QiU1RCUzQiU1Q24lMjAlMjBsZXQlMjBlcnJvciUyMCUzRCUyMG51bGwlM0IlNUNuJTVDbiUyMCUyMGNvbnN0JTIwdmFsaWROdW1zJTIwJTNEJTIwJTVCbnVtMSUyQyUyMG51bTIlNUQuZXZlcnkoKG51bSklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBudW1UeXBlJTIwJTNEJTIwbnVtJTIwJTNFJTIwMCUyMCUzRiUyMCU1QyUyMnAlNUMlMjIlMjAlM0ElMjBudW0lMjAlM0MlMjAwJTIwJTNGJTIwJTVDJTIybiU1QyUyMiUyMCUzQSUyMDAlM0IlNUNuJTVDbiUyMCUyMCUyMCUyMGlmJTIwKG51bVR5cGUpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG51bVR5cGVzLnB1c2gobnVtVHlwZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAhIW51bVR5cGUlM0IlNUNuJTIwJTIwJTdEKSUzQiU1Q24lNUNuJTIwJTIwaWYlMjAoIXZhbGlkTnVtcyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwZXJyb3IlMjAlM0QlMjAlNUMlMjJmb28lNUMlMjIlM0IlNUNuJTIwJTIwJTdEJTIwZWxzZSUyMGlmJTIwKG51bVR5cGVzJTVCMCU1RCUyMCUzRCUzRCUzRCUyMG51bVR5cGVzJTVCMSU1RCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwZXJyb3IlMjAlM0QlMjAlNUMlMjJiYXIlNUMlMjIlM0IlNUNuJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjByZXR1cm4lMjBlcnJvciUzQiU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKHRlc3QoMSUyQyUyMDIpKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

It's dropping the array push inside the `every` callback and breaking the logic.

**Comment by kzc** [comment]
Simplified test case:
```js
let a = [];
[1].forEach(() => a.push("pass"));
console.log(a[0] || "fail");
```
[PR REPL](https://rollupjs.org/repl/?pr=4018&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmxldCUyMGElMjAlM0QlMjAlNUIlNUQlM0IlNUNuJTVCMSU1RC5mb3JFYWNoKCgpJTIwJTNEJTNFJTIwYS5wdXNoKCU1QyUyMnBhc3MlNUMlMjIpKSUzQiU1Q25jb25zb2xlLmxvZyhhJTVCMCU1RCUyMCU3QyU3QyUyMCU1QyUyMmZhaWwlNUMlMjIpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==):
```js
console.log("fail");
```

**Comment by lukastaegert** [comment]
Thanks a lot, great catch! There was a bug in the array deoptimization tracking that did not consider mutations via builtins in one of the places. Fixed now. Also released another beta.
