### PR TITLE
augmentChunkHash plugin hook

### LINKED ISSUE #2739: File hash is not updated when changing code in renderChunk
- Rollup Version: 1.4.1
- Operating System (or Browser): Linux
- Node Version: 10.10.0

### How Do We Reproduce?

Follow the steps on https://github.com/isidrok/rollup-hashing-bug

### Expected Behavior

When code changes in a plugin hook, the file hash should be updated to match the new content.

### Actual Behavior

The file hash is not updated with the new content, instead keeps the hash of the original one which can lead to incorrect hashes when modifying the build process but not the source  or when some plugin in the build process modifies the source due to external factors.

Note that renaming `chunkInfo.fileName` from within the plugin will not work since dependent chunks will keep referencing the old `fileName`.

Let me know if you could use some help for a PR!

### PR DESCRIPTION
**Pull request by isidrok**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

closes #2739
related #2839

### Description

Introduce a new plugin hook `augmentChunkHash` in order to give plugins the ability to augment chunk hashes depending on implicit dependencies or explicit ones that the plugin takes into account in the `renderChunk` hook in order to change the code.

For example:

```js
// rollup-plugin-babel
{
  agumentChunkHash(){
    const pkgPath = path.join(require.resolve('rollup-plugin-babel'), 'package.json')
    const version = require(pkgPath).version;
    const config = fs.readFileSync(options.babelrc);
    return version + config;
  }
}
``` 
This would invalidate chunk hashes whenever the plugin is updated or the babel config file changes.

Alternatively plugins can decide to augment the hash only of certain chunks:
```js
// rollup-plugin-whatever-css
{
  agumentChunkHash(chunk){
    const sheets = chunk.imports.filter(isCss);
    if(!sheets.length) {
        return;
    }
    return Promise.all(sheets.map((sheet)=>fs.readFile(sheet))
         .then(sheets => sheets.join(':'));
  }
}
```
### TODO

- [x] Don't use `hookSeqSync` in favour of `hookReduceValue`, or alternatively a new `hookReduceValueSync`: I think this hook should definitely be async but introducing async code on the `getRenderedHash` requires a great refactor (could be mitigated if using async/await).

- [x] Pass chunk information to the hook, at least its dependencies since those would be the ones impacting the final hash apart from the plugin options and implicit dependencies.

- [x] Write docs once the previous points are solved.

### CODE REVIEW

**Comment by isidrok** [comment]
One possible way to make this hook async and parallel without major changes would be to call it on the `generate` phase and pass its value to [assignChunkIds](https://github.com/rollup/rollup/blob/07b3686f49e3f6f6f035cdf4877ac6c60d83c49a/src/rollup/index.ts#L214)

**Comment by lukastaegert** [comment]
Thanks for your work on this, hope to find a little more time to look into your suggestions in detail.

> One possible way to make this hook async and parallel without major changes would be to call it on the generate phase and pass its value to assignChunkIds

It should definitely be called on the generate and not the build phase as changes in `renderChunk` can vary between outputs (e.g. different output formats etc.).

File: src/rollup/types.d.ts [hunk 1]
```diff
@@ -446,11 +447,10 @@ export interface RenderedModule {
 	renderedLength: number;
 }
 
-export interface RenderedChunk {
+export interface PreRenderedChunk {
```
Comment (isidrok) [inline src/rollup/types.d.ts]: I'm not sure about this but passing the fileName to augmentChunkHash hook seemed wrong since its not yet computed so I created a reduced interface with all the other info

**Comment by isidrok** [comment]
> Thanks for your work on this, hope to find a little more time to look into your suggestions in detail.

We can discuss the API whenever you have time and I'll update the docs once its reviewed.

Also will need some help with failing tests since I can't relate them with the PR changes.

File: src/rollup/index.ts [hunk 2]
```diff
@@ -211,45 +212,81 @@ export default function rollup(rawInputOptions: GenericConfigObject): Promise<Ro
...
-										outputChunk.code = rendered.code;
-										outputChunk.map = rendered.map;
-
-										return graph.pluginDriver.hookParallel('ongenerate', [
-											{ bundle: outputChunk, ...outputOptions },
-											outputChunk
-										]);
-									});
+									const facadeModule = chunk.facadeModule;
+									const chunkInfo = {
```
Comment (lukastaegert) [inline src/rollup/index.ts]: I do not like calculating this information twice. Besides performance considerations, this information will need to be maintained and synced in more than one place which is always problematic.

One way forward might be to first create a Map of Chunk -> PreRenderedChunk info and use this map in the second usage.

File: src/rollup/index.ts [hunk 3]
```diff
@@ -211,45 +212,81 @@ export default function rollup(rawInputOptions: GenericConfigObject): Promise<Ro
...
+											outputChunk.map = rendered.map;
+
+											return graph.pluginDriver.hookParallel('ongenerate', [
+												{ bundle: outputChunk, ...outputOptions },
+												outputChunk
+											]);
+										});
+									})
+								).then(() => {});
+							});
```
Comment (lukastaegert) [inline src/rollup/index.ts]: I am not sure what exactly causes the test failures, e.g.  misc/'handles different import paths for different outputs', but it is definitely caused by some of the changes in this file. Maybe it becomes clearer once the code is deduplicated. My guess is that there is something that has a side effect that does not look side-effectful here.

File: src/rollup/index.ts (hunk 2 above)
Comment (isidrok) [reply src/rollup/index.ts]: Sure, could also do it in an array and just match positions.

File: src/rollup/index.ts (hunk 3 above)
Comment (isidrok) [reply src/rollup/index.ts]: I have found what's causing the errors and its pretty strange:

```js
return graph.pluginDriver
  .hookParallel('renderStart', [])
  .then(() => createAddons(graph, outputOptions))
  .then(addons => {
    // ...
    return Promise.all(
      chunks.map(chunk => {
        const outputChunk = outputBundle[chunk.id] as OutputChunk;
        return chunk.render(outputOptions, addons, outputChunk).then(rendered => {
          // ...  
          return graph.pluginDriver.hookParallel('ongenerate', [
            { bundle: outputChunk, ...outputOptions },
           outputChunk
          ]);
        });
      })
    ).then(() => {});
})
```
Works fine and test pass whereas if I move the `Promise.all` block into another promise:

```js
return graph.pluginDriver
  .hookParallel('renderStart', [])
  .then(() => createAddons(graph, outputOptions))
  .then(addons => {
    // ...
    const augmentChunkHashes = Promise.resolve();
    return augmentChunkHash.then( () => {
      return Promise.all(
        chunks.map(chunk => {
          const outputChunk = outputBundle[chunk.id] as OutputChunk;
          return chunk.render(outputOptions, addons, outputChunk).then(rendered => {
            // ...  
            return graph.pluginDriver.hookParallel('ongenerate', [
              { bundle: outputChunk, ...outputOptions },
              outputChunk
            ]);
          });
        })
      ).then(() => {});
   })
})
```
Some tests break but if I understand correctly:

```js
Promise.all(promises)
  .then(()=>{}) 
=== 
Promise.resolve()
  .then(()=>Promise.all(promises).then(()=>{}))

File: src/rollup/index.ts (hunk 2 above)
Comment (lukastaegert) [reply src/rollup/index.ts]: I think that would be fine as well.

File: src/rollup/index.ts (hunk 3 above)
Comment (lukastaegert) [reply src/rollup/index.ts]: There is a slight difference in that errors thrown synchronously when generating the promises will be caught and reject the Promise in the second case while in the first case, they will be thrown synchronously. But I do not think this is the issue here.

I cannot seem to be able to confirm your finding, will do some digging myself.

Comment (lukastaegert) [reply src/rollup/index.ts]: Also in the second case, execution will be one micro-tick slower, which would point to a possible race condition. But I really hope this is not the issue.

Comment (lukastaegert) [reply src/rollup/index.ts]: Ok, I understand the issue now. It could be argued that this is a bug in Rollup but it is actually only a bug with your modification.
The problem is that the core part of chunk rendering is stateful, i.e. you cannot just interleave the renderings of two different chunks as they leave information about the current rendering process at variables etc. I know this is not ideal but for the time being, I fear we will need to live with this.

The state only needs to be preserved between `chunk.preRender` and `chunk.render`. Previously, this was guaranteed but with your modification, there is now an asynchronous micro-tick between those two calls where another output rendering can sneak in. Which is a problem as the CLI does indeed use `Promise.all` to render outputs.

Comment (lukastaegert) [reply src/rollup/index.ts]: Honestly not sure what a good solution is except forbidding `augmentChunkHash` to be asynchronous for now.

Comment (isidrok) [reply src/rollup/index.ts]: Thanks for looking into this, I was loosing my mind. So if I get it correctly the correct order of events would be to `preRender` and then `render` the chunk for each chunk but with the constraint that this sequence has to be completed before another output goes in. Moving the rendering to another micro-task makes it possible for some sequences when several outputs are generated to go `preRender-ChunkA-OutA` `preRender-ChunkA-OutB ` `render-ChunkA-OutA` or something among those lines breaking the sequence since they are generated inside a `Promise.all` in parallel.

Another possible solution could be running this hook before just before `generate` but I would rather have the information generated during `preRender` and make this `syncrhonous` with a new `hookReduceValueSync` hook for example.

**Comment by shellscape** [comment]
@isidrok @lukastaegert what do we need to get some traction on this PR?

**Comment by shellscape** [comment]
@isidrok thanks so much for jumping on this one.

File: src/rollup/index.ts [hunk 4]
```diff
@@ -147,14 +148,44 @@ export function setWatcher(watcher: RollupWatcher) {
...
+
 function assignChunksToBundle(
 	chunks: Chunk[],
 	outputBundle: OutputBundleWithPlaceholders
 ): OutputBundle {
 	for (let i = 0; i < chunks.length; i++) {
 		const chunk = chunks[i];
 		const facadeModule = chunk.facadeModule;
-
 		outputBundle[chunk.id as string] = {
```
Comment (isidrok) [inline src/rollup/index.ts]: In the end I ended up duplicating this info since a great part of it must be recalculated since internal Ids change from `augmentChunkHashes` to `assignChunksToBundle` and I thought it would be messier to keep track of what should/shouldn't be updated.

File: test/hooks/index.js [hunk 5]
```diff
@@ -1328,4 +1328,157 @@ module.exports = input;
...
+			})
+			.then(bundle =>
+				bundle.generate({
+					format: 'esm',
+					dir: 'dist',
+					entryFileNames: '[name]-[hash].js'
+				})
+			)
+			.then(output => {
+				assert.equal(augmentChunkHashCalls, 1);
```
[the remark this answers is not in the document]
Comment (isidrok) [reply test/hooks/index.js]: In the end I left this one inside hook tests and created a file-hashes one with tests the rest of them

File: test/hooks/index.js [hunk 6]
```diff
@@ -1328,4 +1328,157 @@ module.exports = input;
 				]);
 			});
 	});
+	it('supports augmentChunkHash hook', () => {
```
[the remark this answers is not in the document]
Comment (isidrok) [reply test/hooks/index.js]: done

**Comment by isidrok** [comment]
There are two files with linting changes due to autoformat, which I cannot easily revert due to git hooks,  will checkout them from the upstream and commit with no-verify if needed

File: bin/rollup [hunk 7]
```diff
@@ -0,0 +1,1566 @@
+#!/usr/bin/env node
```
Comment (lukastaegert) [inline bin/rollup]: This file was probably checked in accidentally and should be removed. The reason this happened is probably that the bin file has been moved and the .gitignore was changed accordingly.

File: bin/rollup.map [hunk 8]
```diff
@@ -0,0 +1 @@
...AS,MAAM,CAAE,GAAG,EAAE,IAAI,EAAE,KAAK;QAC7B,IAAI,CAAC,GAAG,GAAG,CAAC;QACZ,IAAI,CAAC,KAAK,CAAC,CAAC,EAAC,CAAC,CAAC,CAAC,CAAC,OAAO,CAAC,UAAU,GAAG;YAClC,IAAI,CAAC,CAAC,GAAG,CAAC,KAAK,SAAS;gBAAE,CAAC,CAAC,GAAG,CAAC,GAAG,EAAE,CAAC;YACtC,CAAC,GAAG,CAAC,CAAC,GAAG,CAAC,CAAC;SACd,CAAC,CAAC;QAEH,IAAI,GAAG,GAAG,IAAI,CAAC,IAAI,CAAC,MAAM,GAAG,CAAC,CAAC,CAAC;QAChC,IAAI,CAAC,CAAC,GAAG,CAAC,KAAK,SAAS,IAAI,KAAK,CAAC,KAAK,CAAC,GAAG,CAAC,IAAI,OAAO,CAAC,CAAC,GAAG,CAAC,KAAK,SAAS,EAAE;YACzE,CAAC,CAAC,GAAG,CAAC,GAAG,KAAK,CAAC;SAClB;aACI,IAAI,KAAK,CAAC,OAAO,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,EAAE;YAC5B,CAAC,CAAC,GAAG,CAAC,CAAC,IAAI,CAAC,KAAK,CAAC,CAAC;SACtB;aACI;YACD,CAAC,CAAC,GAAG,CAAC,GAAG,CAAE,CAAC,CAAC,GAAG,CAAC,EAAE,KAAK,CAAE,CAAC;SAC9B;KACJ;IAED,SAAS,cAAc,CAAC,GAAG;QACzB,OAAO,OAAO,CAAC,GAAG,CAAC,CAAC,IAAI,CAAC,UAAU,CAAC;YAChC,OAAO,KAAK,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC;SACzB,CAAC,CAAC;KACJ;IAED,KAAK,IAAI,CAAC,GAAG,CAAC,EAAE,CAAC,GAAG,IAAI,CAAC,MAAM,EAAE,CAAC,EAAE,EAAE;QAClC,IAAI,GAAG,GAAG,IAAI,CAAC,CAAC,CAAC,CAAC;QAElB,IAAI,QAAQ,CAAC,IAAI,CAAC,GAAG,CAAC,EAAE;;;;YAIpB,IAAI,CAAC,GAAG,GAAG,CAAC,KAAK,CAAC,uBAAuB,CAAC,CAAC;YAC3C,IAAI,GAAG,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC;YACf,IAAI,KAAK,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC;
```
Comment (lukastaegert) [inline bin/rollup.map]: This file should be removed as well.

File: docs/05-plugin-development.md [hunk 9]
```diff
@@ -187,6 +187,23 @@ Kind: `async, parallel`
 
 Called initially each time `bundle.generate()` or `bundle.write()` is called. To get notified when generation has completed, use the `generateBundle` and `renderError` hooks.
 
+#### `augmentChunkHash`
```
Comment (lukastaegert) [inline docs/05-plugin-development.md]: Thanks for adding documentation! It would be nice to stick with the alphabetical ordering of the hooks and move this up.

File: docs/05-plugin-development.md [hunk 10]
```diff
@@ -187,6 +187,23 @@ Kind: `async, parallel`
...
+Type: `(preRenderedChunk: PreRenderedChunk) => any`<br>
```
Comment (lukastaegert) [inline docs/05-plugin-development.md]: Is `any` really the correct type? Looking at how you actually use the return value, the logic assumes these are strings or things that can be safely converted to string, so definitely no functions or objects. I would actually use `string` here to avoid confusion.

File: src/Chunk.ts [hunk 11]
```diff
@@ -136,6 +136,7 @@ export default class Chunk {
 		return chunk;
 	}
 
+	augmentedHash?: string;
```
Comment (lukastaegert) [inline src/Chunk.ts]: From how this is generated, I would say this is more like a `hashAugmentation` as the actual hash is composed of more things. But maybe we can get rid of this property, cf. my other comments?

File: src/Chunk.ts [hunk 12]
```diff
@@ -341,6 +342,9 @@ export default class Chunk {
 		if (this.renderedHash) return this.renderedHash;
 		if (!this.renderedSource) return '';
 		const hash = sha256();
+		if (this.augmentedHash) {
+			hash.update(this.augmentedHash);
```
Comment (lukastaegert) [inline src/Chunk.ts]: As the `renderedHash` is effectively cached and determined at most once, but sometimes not at all, i.e. if there is no `[hash]` in the name pattern, I wondered if it would not be better to generate this value on the fly. The only necessary parameter `graph` is available on each chunk anyway and we would not need the additional property on the `Chunk` class.

File: src/rollup/types.d.ts [hunk 13]
```diff
@@ -327,6 +327,7 @@ interface OnWriteOptions extends OutputOptions {
 }
 
 export interface PluginHooks {
+	augmentChunkHash: (this: PluginContext, chunk: PreRenderedChunk) => void;
```
Comment (lukastaegert) [inline src/rollup/types.d.ts]: I think the correct type would be something like `... => string`?

File: src/Chunk.ts (hunk 11 above)
Comment (isidrok) [reply src/Chunk.ts]: That makes sense and will actually accomplish the lazy behaviour

**Comment by isidrok** [comment]
Alright I got requested changes done. Looking closely into how `file-hashes` test work I don't think they are suitable for this case since they are validating hashes against file contents and this has nothing to do with that. Should I move them back to the hooks suite?

**Comment by lukastaegert** [comment]
> Should I move them back to the hooks suite

We could do that but in the end, this *has* to do with file contents, so we could also make the test closer to the real use case, which would then also serve as a good illustrating example for this hook:

For both sets of options, we have a plugin that implements both the renderChunkHook and the augmentChunkHash hook. The renderChunk hook could be really simple, like prepending a comment. But the change should be slightly different in both cases (e.g. a different comment) and the hash augmentation could also be slightly different (e.g. the content of the comment). Without the augmentChunkHash hook, the test would be red, but due to the hook, the test is green.

File: src/Chunk.ts [hunk 14]
```diff
@@ -341,6 +342,8 @@ export default class Chunk {
 		if (this.renderedHash) return this.renderedHash;
 		if (!this.renderedSource) return '';
 		const hash = sha256();
+		const hashAugmentation = this.calculateHashAugmentation();
+		hash.update(hashAugmentation);
```
Comment (lukastaegert) [inline src/Chunk.ts]: 👍

**Comment by isidrok** [comment]
> This looks really good. Tell me if you want to do the changes to the test as proposed, otherwise from my side this can be merged.

Really nice test case, done!
