### PR TITLE
Tree shaking fixes

### LINKED ISSUE #2302: Rollup lost an else statement (tree shaking away a conditional function inside a loop)
Not sure what is causing this `else` block to go away.  Rollup seems to tree shake away the `isInteresting` function in some situations.

[View the repro in the repl](https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGlzSW50ZXJlc3RpbmdUYWclMjAlN0QlMjBmcm9tJTIwJy4lMkZpbnRlcmVzdGluZy5qcyclM0IlNUNuJTVDbnZhciUyMHRvQ2hlY2slMjAlM0QlMjAlNUIlN0JoaWdod2F5JTNBJTIwJ3ByaW1hcnknJTdEJTJDJTIwJTdCaGlnaHdheSUzQSUyMCdzZWNvbmRhcnknJTdEJTVEJTNCJTVDbnZhciUyMHRhZ3MlMjAlM0QlMjAlN0IlN0QlM0IlNUNudmFyJTIwY29uZmxpY3RpbmclMjAlM0QlMjBmYWxzZSUzQiU1Q24lNUNudG9DaGVjay5mb3JFYWNoKGZ1bmN0aW9uKHNyYyklMjAlN0IlNUNuJTVDdGZvciUyMCh2YXIlMjBrJTIwaW4lMjBzcmMpJTIwJTdCJTVDbiU1Q3QlNUN0aWYlMjAoIShrJTIwaW4lMjB0YWdzKSklMjAlN0IlNUNuJTVDdCU1Q3QlNUN0JTVDdHRhZ3MlNUJrJTVEJTIwJTNEJTIwc3JjJTVCayU1RCUzQiU1Q24lNUN0JTVDdCU3RCUyMGVsc2UlMjBpZiUyMCh0YWdzJTVCayU1RCUyMCUyNiUyNiUyMGlzSW50ZXJlc3RpbmdUYWcoayklMjAlMjYlMjYlMjB0YWdzJTVCayU1RCUyMCElM0QlM0QlMjBzcmMlNUJrJTVEKSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3QlNUN0Y29uZmxpY3RpbmclMjAlM0QlMjB0cnVlJTNCJTVDbiU1Q3QlNUN0JTdEJTVDbiU1Q3QlN0QlNUNuJTdEKSUzQiU1Q24lNUNuY29uc29sZS5sb2coY29uZmxpY3RpbmcpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmludGVyZXN0aW5nLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwaXNJbnRlcmVzdGluZ1RhZyhrZXkpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMGtleSUyMCElM0QlM0QlMjAnYXR0cmlidXRpb24nJTIwJTI2JTI2JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGtleSUyMCElM0QlM0QlMjAnY3JlYXRlZF9ieSclMjAlMjYlMjYlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwa2V5JTIwISUzRCUzRCUyMCdzb3VyY2UnJTIwJTI2JTI2JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGtleSUyMCElM0QlM0QlMjAnb2RibCclMjAlMjYlMjYlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwa2V5LmluZGV4T2YoJ3RpZ2VyJTNBJyklMjAhJTNEJTNEJTIwMCUzQiU1Q24lNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

<details>

<summary>summary</summary>

### main.js
```js
import { isInterestingTag } from './interesting.js';

var toCheck = [{highway: 'primary'}, {highway: 'secondary'}];
var tags = {};
var conflicting = false;

toCheck.forEach(function(src) {
	for (var k in src) {
		if (!(k in tags)) {
				tags[k] = src[k];
		} else if (tags[k] && isInterestingTag(k) && tags[k] !== src[k]) {
				conflicting = true;
		}
	}
});

console.log(conflicting);
```

### interesting.js
```js
export function isInterestingTag(key) {
    return key !== 'attribution' &&
        key !== 'created_by' &&
        key !== 'source' &&
        key !== 'odbl' &&
        key.indexOf('tiger:') !== 0;
}
```

### cjs output.js
```js
'use strict';

var toCheck = [{highway: 'primary'}, {highway: 'secondary'}];
var tags = {};
var conflicting = false;

toCheck.forEach(function(src) {
	for (var k in src) {
		if (!(k in tags)) {
				tags[k] = src[k];
		}
	}
});

console.log(conflicting);
```

</details>

### LINKED ISSUE #2303: Incorrect treeshaking of conditionals when using Object Spread
[See this repro](https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwYSUyMCUzRCUyMCU3QiU1Q24lNUN0cmVzdWx0JTNBJTIwdHJ1ZSU1Q24lN0QlM0IlNUNuJTVDbmNvbnN0JTIwYiUyMCUzRCUyMCU3QiU1Q24lNUN0Li4uYSU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKGIucmVzdWx0JTIwJTNGJTIwJTVDJTIyc3VjY2VzcyU1QyUyMiUyMCUzQSUyMCU1QyUyMmZhaWwlNUMlMjIpJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

The expected value is `console.log("success")`, but we're left with `console.log("fail")`.
It would seem that the Object spread syntax is accepted by Rollup, but I'm assuming you don't handle The Object Spread syntax when you traverse the Acorn AST. That's fine, but I think the correct behavior would be to opt-out from doing the tree-shaking like if `Object.assign` had been used instead of the spread syntax, since it currently breaks libraries and apps built with Rollup in situations like this

### LINKED ISSUE #2306: Code is lost when assigning to object at runtime
Hello, thanks for Rollup, it is super fast. I came a cross an issue when using object maps. I like to use this pattern where I use a "well known" key:

```js
const keys = {
    KEY_A: 'a',
    KEY_B: 'b'
}

const map = {};

map[keys.KEY_A] = function (x) {
    console.log('a called with ' + x);
};

map[keys.KEY_B] = function (x) {
    console.log('b called with ' + x)
};

function callMap(key, x) {
    const fn = map[key];
    if (fn) {
        fn(x);
    }
    else {
        console.log('key does not exist: ' + key);
    }
}

callMap('a', 0);
callMap('z', 0);
callMap('b', 0);
```
In the Repl, you can see that code gets lost:
```js
(function () {
    'use strict';

    function callMap(key, x) {
        {
            console.log('key does not exist: ' + key);
        }
    }

    callMap('a', 0);
    callMap('z', 0);
    callMap('b', 0);

}());
```

### LINKED ISSUE #2316: `for-of` loop is lost on Rollup 0.62.0
Rollup deletes `for-of` loop in this simple code:

```js
export function f(list) {
  for (const el of list) {
    if (el != null) {
      el.foo = 0
    }
  }
}
```

> https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwZihsaXN0KSUyMCU3QiU1Q24lNUN0Zm9yJTIwKGNvbnN0JTIwZWwlMjBvZiUyMGxpc3QpJTIwJTdCJTVDbiU1Q3QlNUN0aWYlMjAoZWwlMjAhJTNEJTIwbnVsbCklMjAlN0IlNUNuJTVDdCU1Q3QlNUN0ZWwuZm9vJTIwJTNEJTIwMCU1Q24lNUN0JTVDdCU3RCU1Q24lNUN0JTdEJTVDbiU3RCU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### LINKED ISSUE #2326: Compilation removes needed IF statements
This was a weird one to track down, but [here's the REPL link](https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBUUkVFLVNIQUtJTkclMjAqJTJGJTVDbmltcG9ydCUyMCcuJTJGbWF0aHMuanMnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMndpbmRvdy50ZXN0JTIwJTNEJTIwKGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTVDdHZhciUyMGNvbmZpZyUyQyUyMHByb3BzJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q24lNUN0ZnVuY3Rpb24lMjBkb1VwZGF0ZSUyMChmb3JjZSklMjAlN0IlNUNuJTVDdCU1Q3R2YXIlMjBjbHMlM0IlNUNuJTVDbiU1Q3QlNUN0Zm9yJTIwKGNscyUyMGluJTIwY29uZmlnKSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3RpZiUyMChwcm9wcyU1QmNscyU1RCUyMCUzRCUzRCUyMG51bGwpJTIwJTdCJTIwY29udGludWUlM0IlMjAlN0QlNUNuJTVDdCU1Q3QlNUN0JTJGJTJGJTVFJTVFJTVFJTVFJTVFJTVFJTVFJTVFJTVFJTIwV0hBVCUyMElOJTIwVEhFJTIwV09STEQhJTNGJTVDbiU1Q3QlNUN0JTdEJTVDbiU1Q3QlN0QlNUNuJTVDbiU1Q3RyZXR1cm4lMjAlN0IlMjBkb1VwZGF0ZSUyMCU3RCUzQiU1Q24lN0QoKSklM0IlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

As you can see, the compiler is removing the if statement, but leaving in the curly braces. Don't pick on the example too much, I reduced it as much as I could to get it down to something that demonstrates the core issue.

### PR DESCRIPTION
**Pull request by lukastaegert**
Resolves #2306.
Resolves #2316.
Resolves #2303.
Resolves #2302.
Resolves #2326.

This resolves quite a few issues of the tree-shaking algorithm. Some were caused by the new return expression handling logic while others were actually older. It also comes with 14(!) new functional tests, most of which were red. Here is a rundown of the most important issues that were fixed:

* Reassignments were not tracked properly through conditional and logical expressions where the test value was reassigned by a hoisted function: https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmxldCUyMG9iajElMjAlM0QlMjAlN0IlMjB4JTNBJTIwZmFsc2UlMjAlN0QlMkMlNUNuJTVDdG9iajIlMjAlM0QlMjAlN0IlMjB4JTNBJTIwZmFsc2UlMjAlN0QlM0IlNUNuJTVDbmxldCUyMGZvbyUyMCUzRCUyMGZhbHNlJTNCJTVDbiU1Q25yZWFzc2lnbkZvbygpJTNCJTVDbiU1Q24oZm9vJTIwJTNGJTIwb2JqMSUyMCUzQSUyMG9iajIpLnglMjAlM0QlMjB0cnVlJTNCJTVDbiU1Q25pZiUyMCghb2JqMS54JTIwJTdDJTdDJTIwb2JqMi54KSUyMCU3QiU1Q24lNUN0dGhyb3clMjBuZXclMjBFcnJvcignUmVhc3NpZ25tZW50JTIwd2FzJTIwbm90JTIwdHJhY2tlZCcpJTNCJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjByZWFzc2lnbkZvbygpJTIwJTdCJTVDbiU1Q3Rmb28lMjAlM0QlMjB0cnVlJTNCJTVDbiU3RCU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==
* Similarly, return expressions were not tracked properly in these situations either: https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjB0cnVlJTNCJTVDbnZhciUyMHRyaWdnZXJlZCUyMCUzRCUyMGZhbHNlJTNCJTVDbiU1Q25yZWFzc2lnbigpJTNCJTVDbiU1Q24oeCUyMCUzRiUyMCgpJTIwJTNEJTNFJTIwKCklMjAlM0QlM0UlMjAlN0IlN0QlMjAlM0ElMjAoKSUyMCUzRCUzRSUyMCgpJTIwJTNEJTNFJTIwJTdCdHJpZ2dlcmVkJTIwJTNEJTIwdHJ1ZSUzQiU3RCkoKSgpJTNCJTVDbiU1Q25mdW5jdGlvbiUyMHJlYXNzaWduKCklMjAlN0IlNUNuJTVDdHglMjAlM0QlMjBmYWxzZSUzQiU1Q24lN0QlNUNuJTVDbmFzc2VydC5vayh0cmlnZ2VyZWQpJTNCJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE
* Also, return expressions of return expressions were not reassigned properly: https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb2JqMSUyMCUzRCUyMCU3QiUyMHglM0ElMjBmYWxzZSUyMCU3RCUyQyU1Q24lNUN0b2JqMiUyMCUzRCUyMCU3QiUyMHglM0ElMjBmYWxzZSUyMCU3RCUzQiU1Q24lNUNuZnVuY3Rpb24lMjBmb28oKSUyMCU3QiU1Q24lNUN0aWYlMjAoTWF0aC5yYW5kb20oKSUyMCUzRSUyMDAuNSklMjAlN0IlNUNuJTVDdCU1Q3RyZXR1cm4lMjAoKSUyMCUzRCUzRSUyMG9iajElM0IlNUNuJTVDdCU3RCU1Q24lNUN0cmV0dXJuJTIwKCklMjAlM0QlM0UlMjBvYmoyJTNCJTVDbiU3RCU1Q24lNUNuZm9vKCkoKS54JTIwJTNEJTIwdHJ1ZSUzQiU1Q24lNUNuaWYlMjAoIShvYmoxLnglMjAlN0MlN0MlMjBvYmoyLngpKSUyMCU3QiU1Q24lNUN0dGhyb3clMjBuZXclMjBFcnJvcignUmVhc3NpZ25tZW50JTIwbm90JTIwdHJhY2tlZCcpJTNCJTVDbiU3RCU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==
* The same goes for return values of parameters: https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm9vKGdldE9iaiklMjAlN0IlNUNuJTVDdGdldE9iaigpLnglMjAlM0QlMjB0cnVlJTNCJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBvYmoxJTIwJTNEJTIwJTdCeCUzQSUyMGZhbHNlJTdEJTNCJTVDbmZvbygoKSUyMCUzRCUzRSUyMG9iajEpJTNCJTVDbiU1Q25pZiUyMCghb2JqMS54KSUyMCU3QiU1Q24lNUN0dGhyb3clMjBuZXclMjBFcnJvcignZnVuY3Rpb24lMjBwYXJhbWV0ZXIlMjByZWFzc2lnbm1lbnQlMjBub3QlMjB0cmFja2VkJyklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMEJhcihnZXRPYmopJTIwJTdCJTVDbiU1Q3RnZXRPYmooKS54JTIwJTNEJTIwdHJ1ZSUzQiU1Q24lN0QlNUNuJTVDbmNvbnN0JTIwb2JqMiUyMCUzRCUyMCU3QnglM0ElMjBmYWxzZSU3RCUzQiU1Q25uZXclMjBCYXIoKCklMjAlM0QlM0UlMjBvYmoyKSUzQiU1Q24lNUNuaWYlMjAoIW9iajIueCklMjAlN0IlNUNuJTVDdHRocm93JTIwbmV3JTIwRXJyb3IoJ2NvbnN0cnVjdG9yJTIwcGFyYW1ldGVyJTIwcmVhc3NpZ25tZW50JTIwbm90JTIwdHJhY2tlZCcpJTNCJTVDbiU3RCU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

There is also one improvement that was previously overlooked: Literal values of return expressions used to be handled as "unknown". This is fixed, this: https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwcmV0dXJuVHJ1ZSgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB0cnVlJTNCJTVDbiU3RCU1Q24lNUNuZnVuY3Rpb24lMjByZXR1cm5GYWxzZSgpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjBmYWxzZSUzQiU1Q24lN0QlNUNuJTVDbmlmJTIwKHJldHVyblRydWUoKSklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdyZXRhaW5lZCcpJTNCJTVDbiU3RCU1Q24lNUNuaWYlMjAocmV0dXJuRmFsc2UoKSklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdyZW1vdmVkJyklM0IlNUNuJTdEJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE now simplifies to
```js
{
	console.log('retained');
}
```

At the core, those were the main reasons for these issues + their fixes:
* If we "lost track" of a variable, we "reassigned all properties" of the variable while we should also have reassigned its return expression if there was one. This is now handled in that a reassignment of an unknown key also reassigns the return expression if applicable. This is a little bit of a hack but otherwise we would have needed a whole lot more deoptimization logic here.
* Certain expressions like conditionals and logical expressions could not be sure which branch applied during the bind phase which lead to issues with reassignments and return expressions. Also, test values and return expressions could not be reliably cached. This is inverted now by a new "cache and deoptimize" logic which applies to the test values of logical expressions, conditional expressions and if-statements, computed property keys, and the return values of call expressions and getter properties. It works like this:
  1. In their `bind` method or in either `getLiteralValueAtPath`, `getReturnExpressionWhenCalledAtPath` or `reassignPath` (whichever is called first; all of these can be called during the bind phase),  those nodes retrieve their relevant literal values or return expressions and cache these.
  2. When retrieving those, they supply themselves as an additional parameter for later "deoptimization".
  3. If the retrieved value is no longer reliable due to a reassignment, the entity where the reassignment happens calls the new `deoptimize` method of the original node.
  4. Deoptimizations can be caused by:
    * Reassigned local variables
    * Reassigned object expression properties
    * Deoptimized intermediate expressions like conditionals

With the new logic, performance seems to be about on par with the old logic. One great advantage of these changes is that we are now independent of the execution order of reassignments which again would enable us to move binding of entities into the tree-shaking phase (e.g. we could bind all sub-scopes each time a function is included).

As an aside, I reworked the logic for object expressions to build a map of all available properties once to avoid reiterating over its properties on every access.

### Update 1

I also added a simple fix for literal values of variables declared in for-loops.

### Update 2

I added a simple fix for untracked reassignments across object rest and spread operators in objects expressions and object patterns. Also updated some definitions.

### CODE REVIEW

File: src/ast/nodes/SpreadElement.ts [hunk 1]
```diff
@@ -1,7 +1,14 @@
...
 
-export default interface SpreadElement extends ExpressionNode {
+export default class SpreadElement extends NodeBase {
 	type: NodeType.tSpreadElement;
 	argument: ExpressionNode;
+
+	bind() {
+		super.bind();
+		// Only properties of properties of the argument could become subject to reassignment
+		this.argument.reassignPath([UNKNOWN_KEY, UNKNOWN_KEY]);
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/SpreadElement.ts]: Definitely, thanks a lot! Will see what solutions I can find.

File: src/ast/nodes/shared/FunctionNode.ts [hunk 2]
```diff
@@ -85,8 +86,13 @@ export default class FunctionNode extends NodeBase {
...
 	reassignPath(path: ObjectPath) {
-		if (path.length === 1 && path[0] === 'prototype') {
-			this.isPrototypeReassigned = true;
+		if (path.length === 1) {
+			if (path[0] === 'prototype') {
+				this.isPrototypeReassigned = true;
+			} else if (path[0] === UNKNOWN_KEY) {
+				this.isPrototypeReassigned = true;
+				this.scope.getReturnExpression().reassignPath(UNKNOWN_PATH);
+			}
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/shared/FunctionNode.ts]: In the given example, `path[0]` would be 'asdf'. This scenario corresponds to something like

```js
function x () {}
x[thisIsPrototype]= {the: 'prototype'};
```

as well as
```js
function x () {}
globalFunction(x);
```

Why the latter? In this situation, we lose track of `x`. For simplicity, this is tracked as reassigning `[UNKNOWN_KEY]` (as this goes hand in hand in most situations). I added comments at the corresponding places of `FunctionNode` and `ArrowFunctionExpression` explaining this as well as further tests as commenting out these lines did not turn any test red.

File: src/ast/nodes/SpreadElement.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/SpreadElement.ts]: The second example was already handle explicitly by the new spread element reassignment logic. Added a comment here + added handling for yield expressions.

**Comment by guybedford** [comment]
Continuing the review here. In the mean time I've found another failure case which still seems to apply despite this PR - 

https://rollupjs.org/repl?version=0.62.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjAnYXNkZiclM0IlNUNudmFyJTIweSUyMCUzRCUyMHglMjAlMkIlMjAnYXNkZiclM0IlNUNuJTVDbmlmJTIwKHglMjAlMkIlMjB5JTIwJTNEJTNEJTNEJTIwJ2FzZGYnKSU1Q24lMjAlMjBjb25zb2xlLmxvZygneWVzJyklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

will post any more I find as I find them.

**Comment by guybedford** [comment]
Sorry, the case I just mentioned isn't valid...

File: src/ast/nodes/ConditionalExpression.ts [hunk 3]
```diff
@@ -170,12 +171,17 @@ export default class ConditionalExpression extends NodeBase {
 		}
 	}
 
-	private getTestValue(recursionTracker: ImmutableEntityPathTracker) {
-		if (this.hasUnknownTestValue) return UNKNOWN_VALUE;
-		const value = this.test.getLiteralValueAtPath(EMPTY_PATH, recursionTracker);
-		if (value === UNKNOWN_VALUE) {
-			this.hasUnknownTestValue = true;
+	private updateUsedBranch() {
```
Comment (guybedford) [inline src/ast/nodes/ConditionalExpression.ts]: If going with the name change, perhaps `analyseBranchResolution`.

File: src/ast/nodes/IfStatement.ts [hunk 4]
```diff
@@ -1,73 +1,88 @@
...
-export default class IfStatement extends StatementBase {
+export default class IfStatement extends StatementBase implements DeoptimizableEntity {
 	type: NodeType.tIfStatement;
 	test: ExpressionNode;
 	consequent: StatementNode;
 	alternate: StatementNode | null;
 
-	private hasUnknownTestValue: boolean;
+	private testValue: LiteralValueOrUnknown;
+	private needsTestValue: boolean;
```
Comment (guybedford) [inline src/ast/nodes/IfStatement.ts]: Perhaps `analysedTestValue`? It wouldn't be clear to me otherwise that `needs` is referring to a lazy analysis state.

File: src/ast/nodes/IfStatement.ts [hunk 5]
```diff
@@ -1,73 +1,88 @@
...
+		super.bind();
+		if (this.needsTestValue) {
+			this.testValue = UNKNOWN_VALUE;
+			this.needsTestValue = false;
+			this.testValue = this.test.getLiteralValueAtPath(EMPTY_PATH, EMPTY_IMMUTABLE_TRACKER, this);
+		}
+	}
+
+	deoptimize() {
+		this.testValue = UNKNOWN_VALUE;
```
Comment (guybedford) [inline src/ast/nodes/IfStatement.ts]: Is this guaranteed to always be called after `bind()` so that `needsTestValue` is definitely `false`?

File: src/ast/nodes/LogicalExpression.ts [hunk 6]
```diff
@@ -11,153 +12,142 @@ import {
...
 	type: NodeType.tLogicalExpression;
 	operator: LogicalOperator;
 	left: ExpressionNode;
 	right: ExpressionNode;
 
-	private hasUnknownLeftValue: boolean;
-	private isOrExpression: boolean;
+	// Caching and deoptimization:
+	// We collect deoptimization information if usedBranch !== null
+	private needsValueResolution: boolean;
```
Comment (guybedford) [inline src/ast/nodes/LogicalExpression.ts]: Again here, if you agree.

File: src/ast/nodes/MemberExpression.ts [hunk 7]
```diff
@@ -93,32 +95,43 @@ export default class MemberExpression extends NodeBase {
 			}
 		} else {
 			super.bind();
+			if (this.propertyKey === null) this.updatePropertyKey();
```
Comment (guybedford) [inline src/ast/nodes/MemberExpression.ts]: `analysePropertyKey` for consistency again? Whatever we choose, the main thing is really having a consistent verb.

File: src/ast/nodes/MemberExpression.ts [hunk 8]
```diff
@@ -93,32 +95,43 @@ export default class MemberExpression extends NodeBase {
...
-			return this.variable.getLiteralValueAtPath(path, recursionTracker);
+			return this.variable.getLiteralValueAtPath(path, recursionTracker, origin);
 		}
-		return this.object.getLiteralValueAtPath(
-			[this.propertyKey || this.getComputedKey(recursionTracker), ...path],
-			recursionTracker
-		);
+		if (this.propertyKey === null) this.updatePropertyKey();
+		this.expressionsToBeDeoptimized.push(origin);
+		return this.object.getLiteralValueAtPath([this.propertyKey, ...path], recursionTracker, origin);
```
Comment (guybedford) [inline src/ast/nodes/MemberExpression.ts]: Much nicer.

File: src/ast/nodes/ObjectExpression.ts [hunk 9]
```diff
@@ -25,89 +24,151 @@ import Literal from './Literal';
...
+	private expressionsToBeDeoptimized: { [key: string]: DeoptimizableEntity[] };
+
+	bind() {
+		super.bind();
+		if (this.propertyMap === null) this.buildPropertyMap();
+	}
+
+	// We could also track this per-property but this would quickly become much more complex
+	deoptimize() {
+		if (!this.hasUnknownReassignedProperty) this.reassignAllProperties();
```
Comment (guybedford) [inline src/ast/nodes/ObjectExpression.ts]: It does seem a little unfortunate that the following:

```js
var obj = {
  x: 'x',
  y: 'y'
};
var test = false;

function asdf () {
  return obj;
}

if (asdf().x === 'x')
  console.log('yes');

if (obj.x === 'x')
  console.log('true');

function updateTest () {
  test = true;
}
```

loses all the analysis benfits if the return statement is just changed to `test ? obj : obj`.

File: src/ast/nodes/ObjectExpression.ts [hunk 10]
```diff
@@ -215,38 +292,56 @@ export default class ObjectExpression extends NodeBase {
...
-			) {
-				properties.push(property);
-				hasCertainHit = true;
-				break;
+				key = String(keyValue);
+			} else if (property.key instanceof Identifier) {
+				key = property.key.name;
+			} else {
+				key = String((<Literal>property.key).value);
+			}
```
Comment (guybedford) [inline src/ast/nodes/ObjectExpression.ts]: Perhaps cache the property here - 

```js
let propertyMapProperty = this.propertyMap[key];
```

File: src/ast/nodes/Property.ts [hunk 11]
```diff
@@ -22,54 +30,59 @@ export default class Property extends NodeBase {
...
-	declare(kind: string, _init: ExpressionEntity) {
+	declare(kind: string, init: ExpressionEntity) {
+		this.declarationInit = init;
 		this.value.declare(kind, UNKNOWN_EXPRESSION);
 	}
 
+	deoptimize() {
+		// As getter properties directly receive their values from function expressions that always
+		// have a fixed return value, there is no known situation where a getter is deoptimized.
+		throw new Error('Unexpected deoptimization');
```
Comment (guybedford) [inline src/ast/nodes/Property.ts]: +1 to having internal assertions... will be useful to catch more bugs.

File: src/ast/nodes/shared/MultiExpression.ts [hunk 12]
```diff
@@ -0,0 +1,65 @@
+import CallOptions from '../../CallOptions';
+import { DeoptimizableEntity } from '../../DeoptimizableEntity';
+import { ExecutionPathOptions } from '../../ExecutionPathOptions';
+import { ImmutableEntityPathTracker } from '../../utils/ImmutableEntityPathTracker';
+import { LiteralValueOrUnknown, ObjectPath, UNKNOWN_VALUE } from '../../values';
+import { ExpressionEntity } from './Expression';
+
+export class MultiExpression implements ExpressionEntity {
```
Comment (guybedford) [inline src/ast/nodes/shared/MultiExpression.ts]: This is a big step. Intermediate expressions!

Could function returns and generator yields not be treated as MultiExpression of all their return values?

File: src/ast/nodes/shared/FunctionNode.ts [hunk 13]
```diff
@@ -85,8 +86,16 @@ export default class FunctionNode extends NodeBase {
...
+		if (path.length === 1) {
+			if (path[0] === 'prototype') {
+				this.isPrototypeReassigned = true;
+			} else if (path[0] === UNKNOWN_KEY) {
+				this.isPrototypeReassigned = true;
+
+				// A reassignment of [UNKNOWN_PATH] is considered equivalent to having lost track
+				// which means the return expression needs to be reassigned as well
+				this.scope.getReturnExpression().reassignPath(UNKNOWN_PATH);
+			}
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/shared/FunctionNode.ts]: There are more situations where a reassignment happens. In all situations where the path is NOT UNKNOWN_PATH, there is an actual assignment taking place. More situations where we reassign UNKNOWN_PATH:
- there is more than one return expression
- a previously optimized conditional is deoptimized
- something is an export of the bundle
- something is an array element
- a variable has more than one declaration
- in any assignment, not only is the EMPTY_PATH of the left side reassigned, we also reassign UNKNOWN_PATH of the right side as we are no longer tracking mutations here (this one is REALLY important)
- this also goes for assignment patterns
- something is yielded (this one is new)

But you are right, this double meaning of reassignPath(UNKNOWN_PATH) should warrant a new name. I will go for `deoptimizePath` and probably rename the existing `deoptimize` methods to `deoptimizeCache` to better distinguish between the two.

File: src/ast/nodes/CallExpression.ts [hunk 14]
```diff
@@ -1,23 +1,35 @@
...
 	type: NodeType.tCallExpression;
 	callee: ExpressionNode;
 	arguments: (ExpressionNode | SpreadElement)[];
 
 	private callOptions: CallOptions;
+
+	// Caching and deoptimization:
+	// We collect deoptimization information if returnExpression !== UNKNOWN_EXPRESSION
 	private returnExpression: ExpressionEntity | null;
+	private expressionsToBeDeoptimized: DeoptimizableEntity[];
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/CallExpression.ts]: I did not check but I would not assume it to work as well as the ImmutableEntityPathTracker in that it would deoptimize more literal values than necessary e.g. in situations where one origin needs more than one lookup to get its value. At least these were the reason why the immutable tracker was used here.

File: src/ast/nodes/CallExpression.ts [hunk 15]
```diff
@@ -57,22 +70,62 @@ export default class CallExpression extends NodeBase {
 		}
 	}
 
+	deoptimize() {
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/CallExpression.ts]: You are right, this is possible. And most places have some guard against repeated execution, I just forgot to add one here. Thanks!

File: src/ast/nodes/ConditionalExpression.ts [hunk 16]
```diff
@@ -11,141 +12,142 @@ import {
...
+	private unusedBranch: ExpressionNode | null;
+	private expressionsToBeDeoptimized: DeoptimizableEntity[];
+
+	bind() {
+		super.bind();
+		if (this.needsValueResolution) this.updateUsedBranch();
+	}
+
+	deoptimize() {
+		if (this.usedBranch !== null) {
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/ConditionalExpression.ts]: Yes, this is something to keep in mind and hopefully improve in the future. In any case, I tried to make sure each conditional is covered by at least one test that turns red when I change it, and I added lots of tests when writing the conditionals (it's nice when TDD actually works as well as in these cases). Which is always a good idea anyway and should guard against a lot of issues.

File: src/ast/nodes/IfStatement.ts (hunk 5 above)
Comment (lukastaegert) [reply src/ast/nodes/IfStatement.ts]: Yes it is. `deoptimize` can only happen after the if statement has been passed as a deoptimization target to `this.test.getLiteralValueAtPath` in the last line of `bind`.

File: src/ast/nodes/ObjectExpression.ts (hunk 9 above)
Comment (lukastaegert) [reply src/ast/nodes/ObjectExpression.ts]: I might give it a try to improve a little here

File: src/ast/nodes/ObjectExpression.ts (hunk 10 above)
Comment (lukastaegert) [reply src/ast/nodes/ObjectExpression.ts]: good idea

File: src/ast/nodes/shared/MultiExpression.ts (hunk 12 above)
Comment (lukastaegert) [reply src/ast/nodes/shared/MultiExpression.ts]: The problem with function returns turned out to be a problem of convergence order for some code-bases (say bundling the TypeScript compiler for instance). If there are many functions with many returns, then with only a few steps, a single `hasEffects` check could suddenly trigger a million secondary checks as all returnExpressions are checked. This should definitely be revisited, though. One might consider e.g. limiting the number of tracked return expressions to two or similar things.

File: src/ast/nodes/ObjectExpression.ts (hunk 9 above)
Comment (lukastaegert) [reply src/ast/nodes/ObjectExpression.ts]: No, it seems with the return expression handling, fixing this would be a little more involved. This will probably need to wait for SSA.

**Comment by lukastaegert** [comment]
Implemented the suggested changes, thanks for the detailed review!

File: src/ast/nodes/shared/MultiExpression.ts (hunk 12 above)
Comment (guybedford) [reply src/ast/nodes/shared/MultiExpression.ts]: Definitely, setting a limit on this would be a good starting approach!

File: src/ast/nodes/shared/FunctionNode.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (guybedford) [reply src/ast/nodes/shared/FunctionNode.ts]: In cases where `reassignPath` really does mean `reassignPath` could we retain the meaning, or is that a big refactor? I just think it seems like there should be a semantic distinction between `reassignPath` which refers to reassigning a binding (which might be possible to track in future), and `deoptimizePath`?

[the remark this answers is not in the document]
Comment (guybedford) [reply src/ast/nodes/shared/FunctionNode.ts]: Nice changing to `deoptimizePath` though that seems much clearer to me!

Or do you think that `reassignPath` for actual reassignments is always about deoptimization, and that if we were to have better tracking here, we'd do it another way?

[the remark this answers is not in the document]
Comment (guybedford) [reply src/ast/nodes/shared/FunctionNode.ts]: Also `deoptimizeCache` sounds great, nice to be clear on what exactly is the deoptimization!

[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/shared/FunctionNode.ts]: The hope is that ultimately with SSA, all remaining reassignments will be "real" deoptimizations where an entity is out of sight of the algorithm. But also in its current form, deoptimize is probably a better name because we never reassign *to* anything but mark it as evil and unreliable ;)
