### PR TITLE
Fix treeshaken parameters around parentheses

### LINKED ISSUE #2909: Treeshaking of arguments leads to SyntaxError
- Rollup Version: 1.14.4
- Operating System (or Browser): osx and browser
- Node Version: 12.0.0

### How Do We Reproduce?

https://rollupjs.org/repl?version=1.14.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QndyaXRlR2VvbWV0cnklN0QlMjBmcm9tJTIwJy4lMkZtYXRocy5qcyclM0IlNUNuY29uc29sZS5sb2cod3JpdGVHZW9tZXRyeSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMHdyaXRlR2VvbWV0cnkoZ2VvbWV0cnklMkMlMjBvcHRfb3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwd3JpdGVQb2ludEdlb21ldHJ5KChnZW9tZXRyeSklMkMlMjBvcHRfb3B0aW9ucyklM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMHdyaXRlUG9pbnRHZW9tZXRyeShnZW9tZXRyeSUyQyUyMG9wdF9vcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwdHlwZSUzQSUyMCdQb2ludCclMkMlNUNuJTIwJTIwJTIwJTIwY29vcmRpbmF0ZXMlM0ElMjBnZW9tZXRyeSUyQyU1Q24lMjAlMjAlN0QlM0IlNUNuJTdEJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behavior

It should generate valid JS:

### Actual Behavior

It does generate JS with syntax errors:
```js
function writeGeometry(geometry, opt_options) {
  return writePointGeometry((geometry);
}
```
^ notice the missing closing `)` after `geometry)`.

### Real world
This issue was first reported by an user of stencil when trying to use the `ol` (open layers) https://www.npmjs.com/package/ol package.

https://github.com/ionic-team/stencil/issues/1607

Specifically this piece of the code:

```js
function writePointGeometry(geometry, opt_options) {
  return {
    type: 'Point',
    coordinates: geometry.getCoordinates()
  };
}
function writeGeometry(geometry, opt_options) {
  geometry = /** @type {import("../geom/Geometry.js").default} */ (transformWithOptions(geometry, true, opt_options));
  var type = geometry.getType();

  /** @type {GeoJSONGeometry} */
  var geoJSON;
  switch (type) {
    case GeometryType.POINT: {
      geoJSON = writePointGeometry(/** @type {Point} */ (geometry), opt_options);
      break;
    }
 }
}
```

```js
      geoJSON = writePointGeometry(/** @type {Point} */ (geometry), opt_options);
```

### PR DESCRIPTION
**Pull request by manucorporat**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #2909 
Close #2910

### CODE REVIEW

File: src/ast/nodes/CallExpression.ts [hunk 1]
```diff
@@ -248,7 +248,14 @@ export default class CallExpression extends NodeBase implements DeoptimizableEnt
...
 					}
-					code.remove(this.arguments[lastIncludedIndex].end, this.end - 1);
+					code.remove(
+						findFirstOccurrenceOutsideComment(
+							code.original,
+							',',
+							this.arguments[lastIncludedIndex].end
+						),
+						this.end - 1
+					);
```
Comment (lukastaegert) [inline src/ast/nodes/CallExpression.ts]: Nice one, I'll take yours 😜

Comment (manucorporat) [reply src/ast/nodes/CallExpression.ts]: It was a simple enough issue to debug! as usual https://astexplorer.net/ was my friend

Comment (lukastaegert) [reply src/ast/nodes/CallExpression.ts]: It is mine as well 😉
