### PR TITLE
Fix plugin regressions

### LINKED ISSUE #2243: [0.60.0] UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'code' of undefined
just upgraded to 0.60.0 and getting this on Windows 10:

```
(node:8876) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'code' of undefined
    at O:\wnmp\www\localhost\domvm\node_modules\rollup\dist\rollup.js:21671:46
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
(node:8876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

builds still appear to work properly though...

### LINKED ISSUE #2245: version 0.60.0 broke rollup-analyzer plugin
I filed an issue with [rollup-analyzer-plugin](https://github.com/doesdev/rollup-analyzer-plugin/issues/2). It seems that something in rollup version 0.60.0 has broken that plugin.

Filing an issue here in case someone can suggest a fix, in which case I'd be happy to create a PR to that plugin to fix it...

### LINKED ISSUE #2247: [0.60.0] Error: Multiple inputs are only supported for experimentalCodeSplitting
Just upgraded rollup for a config that also uses `rollup-plugin-multi-entry`:

`[!] Error: Multiple inputs are only supported for experimentalCodeSplitting.`

rollup.config.js:

```ini
export default [{
    input: [
        'test1.js',
        'test2.js',
        'test3.js'
    ],
    output: {
        file: 'assets/js/dist/front.min.js',
        format: 'iife'
    },
    plugins: [
        multiEntry(),
        terser()
    ]
}, {
   /* ... */
}]
```

I'm not 100% sure what broke, and why. Is `rollup-plugin-multi-entry` broken? Or is it unnecessary now with the addition of `experimentalCodeSplitting`?

Thanks

### PR DESCRIPTION
**Pull request by guybedford**
1. I seem to have messed up the signature of this function in the process by mistake - this returns it to its usual form as expected (resolves #2245)
2. I've also included a closure fix for the chunk.id handling, which must be read synchronously (resolves #2243)
3. I've fixed the multiple input validation to happen after the options hook call (resolves #2247)

### CODE REVIEW

**Comment by guybedford** [comment]
(also included a closure fix for the chunk.id handling, which must be read synchronously)

**Comment by guybedford** [comment]
Updated to include a fix for #2247 as well

File: src/rollup/index.ts [hunk 1]
```diff
@@ -104,14 +104,71 @@ function getInputOptions(rawInputOptions: GenericConfigObject): any {
 
 	checkInputOptions(inputOptions);
 	inputOptions.plugins = ensureArray(inputOptions.plugins);
-	return inputOptions.plugins.reduce(applyOptionHook, inputOptions);
+	inputOptions = inputOptions.plugins.reduce(applyOptionHook, inputOptions);
+
+	if (!inputOptions.experimentalCodeSplitting) {
```
Comment (lukastaegert) [inline src/rollup/index.ts]: Makes a lot more sense to do these checks *after* plugins have been applied 👍
