### PR TITLE
Double declarations

### LINKED ISSUE #2275: TypeError: Cannot read property 'isExternal' of null
Clone https://github.com/vega/vega-lite/tree/dom/rollup-bug, then run

Rollup: 0.60.7. No problems in 0.59. 

```
yarn
yarn build:only
```

Error

```
yarn run v1.7.0
$ tsc && cp package.json build/src/ && rollup -c
build/src/index.js → build/vega-lite.js...
[!] TypeError: Cannot read property 'isExternal' of null
TypeError: Cannot read property 'isExternal' of null
    at Module.traceVariable (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:13092:30)
    at ModuleScope.findVariable (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:12366:29)
    at FunctionScope.Scope.findVariable (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:3925:68)
    at Scope.findVariable (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:3925:68)
    at FunctionScope.Scope.findVariable (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:3925:68)
    at Scope.findVariable (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:3925:68)
    at BlockScope.Scope.findVariable (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:3925:68)
    at Identifier$$1.bind (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:9566:40)
    at Identifier$$1.reassignPath (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:9628:18)
    at LocalVariable.reassignPath (/Users/domoritz/Developer/UW/vega-lite/node_modules/rollup/dist/rollup.js:2628:27)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by lukastaegert**
Resolves #2275.

When a variable has more than one declaration, the reassignment tracking logic could trigger a bug as it was engaged before the inter module bindings were set up.

While fixing this, some other issues popped up that are fixed as well:
* When a variable has more than one declaration, reassignments were not tracked properly for all initialisers
* Reassignments of pattern defaults were not tracked properly
* Reassignments of elements of array literals were not tracked properly. For this one, a very simple logic was implemented that just marks all array elements as "reassigned". In the future, a more elaborate logic could be implemented similar to the object expression logic which would allow values to be tracked across tuples.

All of these issues are now properly tested and fixed.

### CODE REVIEW

File: src/ast/nodes/Identifier.ts [hunk 1]
```diff
@@ -33,9 +34,16 @@ export default class Identifier extends NodeBase {
 			this.variable = this.scope.findVariable(this.name);
 			this.variable.addReference(this);
 		}
+		if (
+			this.variable !== null &&
+			(<LocalVariable>this.variable).isLocal &&
+			!(<LocalVariable>this.variable).bound
+		) {
+			(<LocalVariable>this.variable).bind();
+		}
```
Comment (guybedford) [inline src/ast/nodes/Identifier.ts]: I take it this is the fix? Is there no way to ensure a strong separation of the binding phase? How is this timing issue occurring in the first place?

File: src/ast/variables/LocalVariable.ts [hunk 2]
```diff
@@ -33,17 +37,32 @@ export default class LocalVariable extends Variable {
 		super(name);
 		this.declarations = declarator ? [declarator] : [];
 		this.init = init;
+		this.initialisers = [init];
```
Comment (guybedford) [inline src/ast/variables/LocalVariable.ts]: I love how this project is committed to being rebelliously European :)

I hate to be difficult,  but surely we shouldn't need to track all initializers here, since initializer precedence can always apply (https://github.com/rollup/rollup/issues/2278)? Or do we specifically need to apply `reassignPath(UNKNOWN_PATH)` to each initializer? Can you perhaps help clarify why tracking this information on the variable is not enough?

Alternatively could `this.init` be replaced to always reference `this.initialisers[0]`? I just hate to see the redundancy.

File: src/ast/variables/LocalVariable.ts [hunk 3]
```diff
@@ -33,17 +37,32 @@ export default class LocalVariable extends Variable {
...
+			}
+			this.init = UNKNOWN_EXPRESSION;
+		}
 	}
 
 	getLiteralValueAtPath(
 		path: ObjectPath,
 		recursionTracker: ImmutableEntityPathTracker
 	): LiteralValueOrUnknown {
+		if (!this.bound) this.bind();
```
Comment (guybedford) [inline src/ast/variables/LocalVariable.ts]: I'd prefer to fix root cause if we can... this feels a bit like trying to plug a leak.

**Comment by guybedford** [comment]
Another thing - surely if the `initialisers` array here solves the double declaration issue allowing the variable to be properly defined, why is it still necessary to the specific binding checks?

File: src/ast/nodes/Identifier.ts (hunk 1 above)
Comment (lukastaegert) [reply src/ast/nodes/Identifier.ts]: Unfortunately at least at the moment, I do not know if a separation will be possible at all. Here is an outline of the issue:

## The issue
Before the actual tree-shaking, we pass through three phases:
* the *initialization* or construction phase in which rollup's AST nodes are constructed, the scopes are created and the declaration nodes register themselves on the scope and create the corresponding local variables.
* the *link* phase where the inter-module links are established
* the *bind* phase during which the remaining identifiers are associated with the declarations and all reassignments are collected.

The *bind*  phase relies on all links being in place and the variables having their proper initializers set. This is the reason why before this PR, double declarations were normalized during construction by setting the "init" to "unknown".

However as this means we are losing track of the initializers, it is important we mark all their paths as "reassigned" so that their usages are never dropped in case they are mutated somewhere. 

Reassigning paths, however, is not always possible during initialization in case of imported variables which was the reason for this issue. 

## Why do we need to track the "bound" state of variables?

When using functions, it is easy to access a variable the definition of which is further down in the file. As the binding phase just works from top to bottom, we can therefore not rely on the declarations of the variable being consolidated before any of the functions that can be used during bind access them (those being `reassignPath`, `getReturnExpressionWhenCalledAtPath` and `getLiteralValueAtPath`, all of which can pass through several variables to do their work).

A separate phase between *link*  and *bind*  would also not solve the issue entirely as it is still possible that the necessary reassignments would reach a variable that is not bound yet.

Another approach could be to not consolidate declarations at all. But this would make *all* of `LocalVariable` more complicated and definitely slow down tree-shaking while I think the optimization benefit would be small due to the fact that double declarations are rather rare. I'll think about how this can be made a little less convoluted.

File: src/ast/variables/LocalVariable.ts (hunk 2 above)
Comment (lukastaegert) [reply src/ast/variables/LocalVariable.ts]: Without TDZ/flow analysis, we do not know which definition applies where. Thus the approach is to make the variable "unknown". As we can no longer track initializer references in such a situation, all initializers need the `reassignPath(UNKNOWN_PATH)`.
I could however simplify this to get rid of the redundancy.

**Comment by lukastaegert** [comment]
We could also track this as an either-or case but I feel this would make everything slower just for an edge case which is usually a bug.

**Comment by lukastaegert** [comment]
Actually found a way to get rid of the `bound` variable by separating the collection of initializers and setting the `init` value during construction and only doing the reassignments during bind (in which case order is no longer important).

**Comment by lukastaegert** [comment]
Ready for another review.

File: src/ast/variables/LocalVariable.ts [hunk 4]
```diff
@@ -21,48 +21,49 @@ const MAX_PATH_DEPTH = 7;
...
-			for (const initialiser of this.initialisers) {
-				initialiser.reassignPath(UNKNOWN_PATH);
+	consolidateInitializers() {
+		if (this.additionalInitializers !== null) {
+			for (const initializer of this.additionalInitializers) {
+				initializer.reassignPath(UNKNOWN_PATH);
 			}
-			this.init = UNKNOWN_EXPRESSION;
+			this.additionalInitializers = null;
 		}
```
Comment (guybedford) [inline src/ast/variables/LocalVariable.ts]: Can we not apply `initializer.reassignPath` in `addDeclaration`? Or is this the whole issue with the `.bound` checks?
