### PR TITLE
Default and export naming fixes

### LINKED ISSUE #1996: Code splitting with 'amd' output with default export from common chunk causes incorrect import from dependent chunks
If a common module has the form:

```js
const identifier = /* some value */;
export default identifier;
```

and is used from multiple entry points like:

```js
import x from './shared';
/* do stuff with x */
```

then, when bundled using `format: 'amd'`, the output in the dependent modules seems to contain free references to `x` (rather than something like `__chunk1_js.identifier`).

Minimal reproduction here: https://gist.github.com/anandthakker/f2bc16bed7335e8cccb21f257bdf6529 

If you change the common module to simply `export default /* value */`, the error does _not_ occur.

### PR DESCRIPTION
**Pull request by guybedford**
This fixes #1996 along with some other cases around export default and named exports:

* The issue was the fact that default exports get a temporary reassignment tracking variable. So the fix was to ensure this variable supports `safeName` and doesn't get a safe name when there's an original reassignment.
* There was an issue with the CJS and AMD export mode on chunks being set to auto. Internal chunks need to always use named exports for consistency with the interfaces, which fixed a missed test case as well.
* ensureExport now takes an export name argument. Export names can in theory be arbitrary, but when they match up with the exact signature of a chunk we allow chunks to become entry point chunks. So ensuring export name consistency helps ensure we don't create unnecessary facades.
* Removed an unused code path in ensureExport
* Default exports are now called `default` by default, while we were using their import aliases before.

The depths of these cases keeps expanding... I'm sure it will continue to! But as long as we put equal effort into refactoring and fixes we should be on a good footing (and project sponsorship has been a huge help to justify this time input!!).

### CODE REVIEW

**Comment by anandthakker** [comment]
@guybedford Tried this out over in https://github.com/mapbox/mapbox-gl-js/pull/6196 and I'm seeing:

```
exports.* = commonjsGlobal;
exports.*$1 = unwrapExports;
exports.*$2 = createCommonjsModule;
```

in chunk1.js

File: src/ast/variables/ExportDefaultVariable.ts [hunk 1]
```diff
@@ -14,6 +14,7 @@ export default class ExportDefaultVariable extends LocalVariable {
 		super(name, exportDefaultDeclaration, exportDefaultDeclaration.declaration);
 		this.isDefault = true;
 		this.hasId = !!(<FunctionDeclaration | ClassDeclaration>exportDefaultDeclaration.declaration).id;
+		this.exportName = 'default';
```
Comment (anandthakker) [inline src/ast/variables/ExportDefaultVariable.ts]: How hard would it be to include the filename of the module as part of this name, e.g., `my_module$default` for the default export of `my-module.js`?  Seems like this could make for easier debugging in some cases.

**Comment by anandthakker** [comment]
```diff
diff --git a/src/Chunk.ts b/src/Chunk.ts
index 6c01905c..69b6eea4 100644
--- a/src/Chunk.ts
+++ b/src/Chunk.ts
@@ -146,9 +146,10 @@ export default class Chunk {
                }

                let i = 0;
-               safeExportName = exportName;
+               const baseExportName = exportName === '*' ? '_namespace' : exportName;
+               safeExportName = baseExportName;
                while (this.exports[safeExportName]) {
-                       safeExportName = exportName + '$' + ++i;
+                       safeExportName = baseExportName + '$' + ++i;
                }
                variable.exportName = safeExportName;
```

Fixes the above for me

File: src/ast/variables/ExportDefaultVariable.ts (hunk 1 above)
Comment (guybedford) [reply src/ast/variables/ExportDefaultVariable.ts]: The reason we use the initial name is because this stage of the algorithm is still attempting to determine if the chunk is an entry point module itself (entry.js), or if it is a chunk (chunk[i].js). Ideally the algorithm could do the export naming after this stage in the process in which case we can better handle naming definitely. I will look into a refactor along these lines, but perhaps not just yet.

Comment (guybedford) [reply src/ast/variables/ExportDefaultVariable.ts]: (So basically in the scenario that the chunk is an entry point, we need it to do the correct naming as the entry point would expect)

**Comment by guybedford** [comment]
@anandthakker any chance of a test case? I take it you have a namespace import across a chunk boundary?

**Comment by anandthakker** [comment]
@guybedford y, I'll try to reduce a test case.  We don't have an explicit namespace import -- from the variable names (`commonjsGlobal`, `unwrapExports`, `createCommonjsModule`), my guess is that this is coming from a module produced by https://github.com/rollup/rollup-plugin-commonjs

**Comment by guybedford** [comment]
Sure no stress, I'll run it on my test case here for that too and see what I can find.

**Comment by anandthakker** [comment]
@guybedford reduced test case here: https://gist.github.com/anandthakker/68b1b63f2c1236e85709aae0f9f80ad9

**Comment by guybedford** [comment]
@anandthakker amazing thanks for isolating - my CJS case here didn't catch it.

**Comment by guybedford** [comment]
@anandthakker I've included the fix here. Thanks again for the test cases.

**Comment by anandthakker** [comment]
@guybedford thanks!  Confirmed that it's working in practice over at https://github.com/mapbox/mapbox-gl-js/tree/6fa5becea62ac5a58a5eb1572fb764c64e50fa36

**Comment by anandthakker** [comment]
(By the way, @guybedford, you can also see there the hacky way we're using code splitting to approximate the `new Worker()` strategy under discussion over at https://github.com/rollup/rollup/issues/1029)

File: src/Chunk.ts [hunk 2]
```diff
@@ -136,44 +138,30 @@ export default class Chunk {
...
-		// and note the name it comes from
-		if (module.chunk !== this && !module.isExternal) {
-			curExport.name = (<Module>module).chunk.ensureExport(module, variable);
-		}
-		else {
-			curExport.name = safeExportName;
-		}
-
 		return safeExportName;
 	}
```
Comment (lukastaegert) [inline src/Chunk.ts]: 👍

File: src/ast/scopes/Scope.ts [hunk 3]
```diff
@@ -86,7 +86,7 @@ export default class Scope {
 			const declaration = this.variables[key];
 
 			// we can disregard exports.foo etc
-			if (declaration.exportName && declaration.isReassigned && !declaration.isId)
+			if (declaration.exportName && (declaration.isDefault || declaration.isReassigned && !declaration.isId))
```
Comment (lukastaegert) [inline src/ast/scopes/Scope.ts]: The non-use of more parentheses here makes me a little uneasy (sorry, but I'm one of those people who need to look into an operator precedence table to see that `&&` binds more strongly than `||`).

**Comment by arackaf** [comment]
I'm trying to test this branch out, but I can't quite get npm to install it - can anyone here possibly lend a hand?  As far as I can tell, this is what I want

`npm i https://github.com/rollup/rollup.git#default-identifier-renaming --save`

but npm doesn't seem to like it

**Comment by lukastaegert** [comment]
Hi @arackaf,

you should probably check your npm version. As rollup relies on its `prepare` script being executed to build its bundle, direct Github installation will only work for npm versions 5.0.0 and later. As I just confirmed, `npm i rollup/rollup#default-identifier-renaming --save` should work with current npm versions.

Nevertheless, I am about to release this branch now anyway 😉

**Comment by arackaf** [comment]
Aha! Thanks Lukas.  I'm still too scared to go back in the npm 5 waters. I reverted back to the comfort and safety of npm 4 since many of the 5 bugs affected me directly.

**Comment by guybedford** [comment]
@arackaf for future reference try `git://github.com/rollup/rollup#default-identifier-renaming`.

**Comment by lukastaegert** [comment]
@arackaf Might be worth giving npm@5 another shot. A lot has been fixed and improved since 5.0.0. We're using it at work for two large projects and after some initial hickups, it's now been smooth riding for quite a few months now. The performance benefits are nothing to sneeze at 😉
