### PR TITLE
Fix `removedExports` to correctly track the exported item

### LINKED ISSUE #2834: `RenderedModule.removedExports` is wrong when using export declarations
I’m not really sure if this is actually a bug or intended behavior.

The `removedExports` metadata refers to the `export declaration` that was removed.
However, if you have explicit `export { foo }` declarations, instead of `export function foo() {}`, it reports them as removed, since the `export declaration` itself will be rewritten by rollup, but the `function declaration` itself is still included and rendered.

In other words, `export function foo() {}` correctly reflects in `removedExports / renderedExports` whether the function is included in the output or not, however `function foo() {} export { foo }` will **always** list `foo` inside `removedExports`.

If this is indeed intended instead of a bug, it would be nice to provide a different implementation that really refers to the `function/class/const/whatever` that is being removed.

- Rollup Version: 1.11.0
- Operating System (or Browser): linux
- Node Version: 11.14

### How Do We Reproduce?

```ts
// main.js
export { a, c as b } from "./a";

// a.js
function a() {}
function b() {}
function c() {}

export { a, b, c };
// the `module` has: { "removedExports": ["a", "b", "c"] }
```

[REPL Link](https://rollupjs.org/repl?version=1.11.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGElMkMlMjBjJTIwYXMlMjBiJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZhJTVDJTIyJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBhKCklMjAlN0IlN0QlNUNuZnVuY3Rpb24lMjBiKCklMjAlN0IlN0QlNUNuZnVuY3Rpb24lMjBjKCklMjAlN0IlN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGElMkMlMjBiJTJDJTIwYyUyMCU3RCUzQiU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXNtJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

For the testcase above, `removedExports` for `a.js` should list only `["b"]`, corresponding to the `function declaration` which was actually removed.

### Actual Behavior

For the testcase above, `removedExports` for `a.js` lists `["a", "b", "c"]`, which is kind of wrong, depending on your expectation on how `removedExports` should work.

It correctly lists **all** the `export declarations`, since they will be re-written by rollup someplace else, but the `function declarations` are still there.

### PR DESCRIPTION
**Pull request by Swatinem**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

closes #2834

### Description

The `RenderedModule.removedExports/renderedExports` now correctly track the *item* being exported, and not the export declaration itself.

### CODE REVIEW

File: test/misc/bundle-information.js [hunk 1]
```diff
@@ -416,4 +416,95 @@ console.log(other);Promise.all([import('./dynamic1'), import('./dynamic2')]).the
 				);
 			});
 	});
+
+	it('contains correct information about rendered/removedExports', () => {
```
Comment (lukastaegert) [inline test/misc/bundle-information.js]: I find it quite complex and harder to read/play around with to run rollup twice in the same test. Would it make sense to turn this into two separate tests, maybe with descriptions that highlight what the difference between the two runs is? That way you cannot compare the results programmatically but I think that is only a small loss.

**Comment by Swatinem** [comment]
> If a module exports e.g. a function and this export is not used by another module but the function is used internally, then this export will be reported as "rendered". Not sure if this is what we want

My usecase for this is to build a plugin that errors on *dead code*. So at least for my usecase, the information if an item is included in the bundle is exactly the info I rely on :-)

Will update according to your comments in a sec, have to finish up another PR :-)
