### PR TITLE
Fix transformation of `import.meta.url` in CommonJS

### LINKED ISSUE #4461: `import.meta.url` transformation produces invalid file URL strings
### Rollup Version

2.70.1

### Operating System (or Browser)

Windows

### Node Version (if applicable)

v16.14.0

### Link To Reproduction

https://github.com/mdjermanovic/rollup-import-meta-url-repro

### Expected Behaviour

`import.meta.url` to be transformed to an expression that always evaluates to valid URL strings.

### Actual Behaviour

When `__filename` contains special characters or sequences such as `%2F`, `new (require('u' + 'rl').URL)('file:' + __filename).href` could be an invalid file URL string.

```
node:internal/modules/cjs/loader:1216
      throw new ERR_INVALID_ARG_VALUE('filename', filename,
      ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:///C:/milos/rollup-import-meta-url-repro/my%2Fdir/index.cjs'
    at new NodeError (node:internal/errors:371:5)
    at Function.createRequire (node:internal/modules/cjs/loader:1216:13)
    at Object.<anonymous> (C:\milos\rollup-import-meta-url-repro\my%2Fdir\index.cjs:5:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_INVALID_ARG_VALUE'
}

```

Ref: https://github.com/eslint/eslint/issues/15766

### PR DESCRIPTION
**Pull request by fasttime**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

resolves #4461

### Description

This PR resolves an issue with the conversion of certain file names to URLs when transforming modules into CommonJS code. In CommonJS, `import.meta.url` is not available and must be also transformed. The current implementation relies on `new URL(filePath).href`, which does not work well if the file path contains certain character sequences as described in #4461. In fact the argument passed to `new URL()` is interpreted as a URL-encoded string rather than a path, and this can be problematic.

This PR changes the way `import.meta.url` is transformed in CommonJS code using [`pathToFileURL`](https://nodejs.org/api/url.html#urlpathtofileurlpath). A test for the fix is included in [`/test/function/samples/emit-file/file-references-in-bundle`](https://github.com/rollup/rollup/pull/4875/files#diff-3dc13ca7f34a8515732fd37cfaa2c2c1570578f66be59b98436118404d1ea094).

### CODE REVIEW

File: src/ast/nodes/MetaProperty.ts [hunk 1]
```diff
@@ -175,18 +175,17 @@ const relativeUrlMechanisms: Record<InternalModuleFormat, (relativePath: string)
 		return getResolveUrl(`require.toUrl('${relativePath}'), document.baseURI`);
 	},
 	cjs: relativePath =>
-		`(typeof document === 'undefined' ? ${getResolveUrl(
-			`'file:' + __dirname + '/${relativePath}'`,
-			`(require('u' + 'rl').URL)`
-		)} : ${getRelativeUrlFromDocument(relativePath)})`,
+		`(typeof document === 'undefined' ? ${`require('u' + 'rl').pathToFileURL(__dirname + '/${relativePath}').href`} : ${getRelativeUrlFromDocument(
```
Comment (lukastaegert) [inline src/ast/nodes/MetaProperty.ts:178]: The generated code looks fine to me! One minor optimization to avoid duplication in this file: It would be nice to extract a helper function similar to `getResolveUrl` that encapsulates the logic and avoids repeating it in four places.

E.g.
```suggestion
		`(typeof document === 'undefined' ? ${getFileUrlFromDirname(relativePath)} : ${getRelativeUrlFromDocument(
```

and above

```ts
const getFileUrlFromDirname = (path: string) => `require('u' + 'rl').pathToFileURL(__dirname + '/${path}').href`;
```

**Comment by lukastaegert** [comment]
Also, you need to make the new test assertions OS agnostic 😉

File: src/ast/nodes/MetaProperty.ts (hunk 1 above)
Comment (fasttime) [reply src/ast/nodes/MetaProperty.ts]: I added two helper functions:

https://github.com/rollup/rollup/blob/d10ffc3f15bd685f5caba869df72f99b2b8dd8a9/src/ast/nodes/MetaProperty.ts#L165-L168

These are now used to calculate the URL expressions from the full or relative filename.

Also fixed the failing test on Windows 🤞

**Review by lukastaegert — APPROVED** [review]
Beautiful! Thanks a lot!
