### PR TITLE
fix: watch mode input should not be an output subpath

### LINKED ISSUE #5938: Infinite loop build in watch mode
### Rollup Version

4.40.0

### Operating System (or Browser)

macOS

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://github.com/vitejs/vite/pull/19922

https://stackblitz.com/edit/vitejs-vite-jdzbgww2?file=package.json

### Expected Behaviour

Directly throw an error message to exit the process or give a warning message, and the watch will not take effect.

### Actual Behaviour

Since the output path includes the entry file, packaging the build file will cause the watch to be re-triggered, resulting in repeated builds.

### PR DESCRIPTION
**Pull request by btea**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

List any relevant issue numbers:

### Description
close #5938

### CODE REVIEW

File: src/watch/watch-proxy.ts [hunk 1]
```diff
@@ -31,6 +53,11 @@ async function watchInternal(configs: MaybeArray<RollupOptions>, emitter: Rollup
 			)
 		);
 	}
+	if (!checkWatchConfig(watchOptionsList)) {
+		return error(
+			logInvalidOption('watch', URL_WATCH, 'the input should not be inside the output dir')
```
Comment (lukastaegert) [inline src/watch/watch-proxy.ts:58]: If we throw the error within checkWatchConfig instead, then we can actually print the offending paths, which users might like if they have multiple configs.

File: src/watch/watch-proxy.ts [hunk 2]
```diff
@@ -17,6 +22,23 @@ export default function watch(configs: RollupOptions[] | RollupOptions): RollupW
...
 }
 
+function checkWatchConfig(config: MergedRollupOptions[]): boolean {
+	for (const item of config) {
+		if (item.input && item.output) {
+			const input = typeof item.input === 'string' ? ensureArray(item.input) : item.input;
+			const output = ensureArray(item.output);
+			for (const index in input) {
+				const inputPath = input[index as keyof typeof input] as string;
+				const subPath = output.some(o => o.dir && inputPath.startsWith?.(o.dir));
```
Comment (lukastaegert) [inline src/watch/watch-proxy.ts:32]: While only an edge case, "startsWith" can have false positives, e.g. if the output dir is `foo/website/` and the input is `foo/website.js`, which feels slightly plausible to me. AI suggest something like

```js
function isSubPath(parentDir, filePath) {
  const relative = path.relative(parentDir, filePath);
  return relative && !relative.startsWith('..') && !path.isAbsolute(relative);
}
```

which does not feel too bad to me, though of course it is more involved. Alternatively, one could probably extend "startsWith" with a check that the remaining part of inputPath starts with a path separator.

**Review by lukastaegert — COMMENTED** [review]
Hi, thanks for the PR! This check is definitely a good idea, just some questions to refine some edge cases.

File: src/watch/watch-proxy.ts (hunk 1 above)
Comment (btea) [reply src/watch/watch-proxy.ts:58]: That makes sense.

File: src/watch/watch-proxy.ts (hunk 2 above)
Comment (btea) [reply src/watch/watch-proxy.ts:32]: Thanks for the review, I will change it.

**Review by lukastaegert — APPROVED** [review]
