### PR TITLE
Avoid chunks TLA dynamic import circular when TLA dynamic import used in non-entry modules

### LINKED ISSUE #5929: Incorrect chunking when code has top-level await
### Rollup Version

4.40.0

### Operating System (or Browser)

REPL

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://rollupjs.org/repl/?version=4.40.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwc3RvcmUlMjBmcm9tJTIwJy4lMkZzdG9yZS5qcyclNUNuJTVDbmNvbnNvbGUubG9nKHN0b3JlLmdldFN0YXRlKCkuY291bnQpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwYWFhYSUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGYS5qcyU1QyUyMiU1Q24lNUNuY29uc3QlMjB1c2VTdG9yZSUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBnZXRTdGF0ZSUzQSUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb3VudCUzQSUyMGFhYWElMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKCdsb2FkaW5nJTIwbGF6eU1vZHVsZScpJTVDbmNvbnN0JTIwbW9kdWxlJTIwJTNEJTIwYXdhaXQlMjBpbXBvcnQoJy4lMkZsYXp5TW9kdWxlLmpzJyklM0IlNUNuY29uc29sZS5sb2coJ21vZHVsZSUyMHZhbHVlJTIwaXMlMjAlM0EnJTJDJTIwbW9kdWxlLmRlZmF1bHQpJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwdXNlU3RvcmUlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIyc3RvcmUuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwYWFhYSUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGYS5qcyU1QyUyMiU1Q24lNUNuY2xhc3MlMjBGb28lMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3RydWN0b3IoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygnZm9vJyUyQyUyMGFhYWEpJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbmNvbnN0JTIwZm9vJTIwJTNEJTIwbmV3JTIwRm9vKCklNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmb28lMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIybGF6eU1vZHVsZS5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGFhYWElMjAlM0QlMjAlNUMlMjIlNUMlMjIlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE

### Expected Behaviour

When running the output code, the following is output:
```
loading lazyModule
foo
module value is : Foo {}
```
This is the output when running the input code.

### Actual Behaviour

When running the output code, the following is output:
```
loading lazyModule
Warning: Detected unsettled top-level await at /path/to/dist/main.js:12
const module = await import('./lazyModule-CphAvXjM.js');
```

This is a slightly complicated version of #4708 but different from #5884 (the `await import` is not wrapped).

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
resolves #5929

### CODE REVIEW

File: src/utils/chunkAssignment.ts [hunk 1]
```diff
@@ -285,9 +285,12 @@ function analyzeModuleGraph(entries: Iterable<Module>): {
...
 					dynamicImportsForCurrentEntry.add(resolution);
-					if (resolution.includedDirectTopLevelAwaitingDynamicImporters.has(currentEntry)) {
-						awaitedDynamicEntryModules.add(resolution);
-						awaitedDynamicImportsForCurrentEntry.add(resolution);
+					for (const includedDirectTopLevelAwaitingDynamicImporter of resolution.includedDirectTopLevelAwaitingDynamicImporters) {
+						if (modulesToHandle.has(includedDirectTopLevelAwaitingDynamicImporter)) {
+							awaitedDynamicEntryModules.add(resolution);
+							awaitedDynamicImportsForCurrentEntry.add(resolution);
+							break;
+						}
```
Comment (lukastaegert) [inline src/utils/chunkAssignment.ts:293]: Looks good to me, thanks! I needed to think about this for a moment, maybe we want to rename `modulesToHandle` to something like `staticDependencies`, that would clarify that this is not just a transient Set but really has a meaning. Otherwise, this looks fine to me.

Comment (TrickyPi) [reply src/utils/chunkAssignment.ts]: Done!

**Review by lukastaegert — APPROVED** [review]
Looks good to me. I needed to think a moment, but
