### PR TITLE
Fix #2230, default identifier renaming issue

### LINKED ISSUE #2230: Incorrect function name mangling while tree shaking dependencies
Rollup does some incorrect mangling for function names while tree shaking. We have seen this behavior for quite a while, so not sure what exact version this was introduced.

I believe this might be a trivial bug to fix for the owners if you know the code base. Otherwise, if you don't have time to prioritize this, let me know and I will dig in.

[Repro](https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMF9pbmhlcml0cyUyMGZyb20lMjAlNUMlMjIuJTJGaW5oZXJpdHMlNUMlMjIlM0IlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB0ZXN0KCklMjAlN0IlNUNuJTIwJTVDdCUyMHZhciUyMEZvbyUyMCUzRCUyMCU3QiU3RCUzQiU1Q24lMjAlMjBfaW5oZXJpdHMoJTdCJTdEJTJDJTIwRm9vKSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyaW5oZXJpdHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwc2V0UHJvdG90eXBlT2YlMjBmcm9tJTIwJTVDJTIyLiUyRnNldFByb3RvdHlwZU9mJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBfaW5oZXJpdHMoc3ViQ2xhc3MlMkMlMjBzdXBlckNsYXNzKSUyMCU3QiU1Q24lMjAlMjBpZiUyMChzdXBlckNsYXNzKSUyMHNldFByb3RvdHlwZU9mKHN1YkNsYXNzJTJDJTIwc3VwZXJDbGFzcyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzZXRQcm90b3R5cGVPZi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBfc2V0UHJvdG90eXBlT2YobyUyQyUyMHApJTIwJTdCJTVDbiUyMCUyMF9zZXRQcm90b3R5cGVPZiUyMCUzRCUyME9iamVjdC5zZXRQcm90b3R5cGVPZiUyMCU3QyU3QyUyMGZ1bmN0aW9uJTIwX3NldFByb3RvdHlwZU9mKG8lMkMlMjBwKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBvLl9fcHJvdG9fXyUyMCUzRCUyMHAlM0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwbyUzQiU1Q24lMjAlMjAlN0QlM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMF9zZXRQcm90b3R5cGVPZihvJTJDJTIwcCklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

## Code example: 
This example is a boiled down version of the use of babel helpers (latests babel 7).

main.js
```js
import _inherits from "./inherits";
export function test() {
    var Foo = {};
   _inherits({}, Foo);
}
```

inherits.js
```js
import setPrototypeOf from "./setPrototypeOf";

export default function _inherits(subClass, superClass) {
  if (superClass) setPrototypeOf(subClass, superClass);
}
```

setPrototypeOf.js

```js
export default function _setPrototypeOf(o, p) {
  _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {
    o.__proto__ = p;
    return o;
  };

  return _setPrototypeOf(o, p);
}
```

Output:

```js
Object.defineProperty(exports, '__esModule', { value: true });

function _setPrototypeOf(o, p) {
  _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {
    o.__proto__ = p;
    return o;
  };

  return _setPrototypeOf(o, p);
}

function _inherits(subClass, superClass) {
  // HERE: setPrototypeOf is incorrectly scoped it should be _setPrototypeOf
  if (superClass) setPrototypeOf(subClass, superClass);
}

function test() {
 	 var Foo = {};
  _inherits({}, Foo);
}

exports.test = test;
```

As you can see the `setPrototypeOf` call is named incorrectly.

### PR DESCRIPTION
**Pull request by guybedford**
This ensures that the name of the default variable is kept as its declaration name for function and class declarations, instead of using reference hints.

### CODE REVIEW

**Comment by diervo** [comment]
If we could get a release with this change soon, it will save our team a lot of time :)
@caridy will pay for a dinner ;)

**Comment by guybedford** [comment]
@diervo you're welcome. Shameless plug - Salesforce OS support would look great at https://opencollective.com/rollup :)

I don't have publish access, but @lukastaegert should be back today, so we should be able to get this out early this week.

**Comment by diervo** [comment]
@guybedford @lukastaegert Yes! I'm working on it ;) I just got approval for babel last month (https://opencollective.com/salesforce), and I'm working for getting rollup as well, keep you updated.

Thanks for the quick turn around.

**Comment by guybedford** [comment]
@diervo that would be amazing, thank you so much for looking into it!

File: test/form/samples/default-identifier-deshadowing/dep.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+export default function a() {
+	console.log('effect');
+  a = someGlobal;
+  return a();
+}
```
Comment (lukastaegert) [inline test/form/samples/default-identifier-deshadowing/dep.js]: I would remove the `console.log` statement as the function call should not be removed even without it. `a()` is basically equivalent to `someGlobal()` which can have side-effects.

File: src/ast/variables/ExportDefaultVariable.ts [hunk 2]
```diff
@@ -23,9 +23,11 @@ export default class ExportDefaultVariable extends LocalVariable {
...
 
 	addReference(identifier: Identifier) {
-		this.name = identifier.name;
-		if (this.original !== null) {
-			this.original.addReference(identifier);
+		if (!this.hasId) {
+			this.name = identifier.name;
+			if (this.original !== null) {
+				this.original.addReference(identifier);
+			}
```
Comment (lukastaegert) [inline src/ast/variables/ExportDefaultVariable.ts]: Seems like a good approach! The original logic was probably only in place to provide a better name than the file name to unnamed default exports. If we have an id, using that makes a lot of sense.

File: test/form/samples/default-identifier-deshadowing/dep.js (hunk 1 above)
Comment (guybedford) [reply test/form/samples/default-identifier-deshadowing/dep.js]: Sure, done.

**Comment by caridy** [comment]
jajaja! Dinner is on me!
