### PR TITLE
cli: implement --failAfterWarnings flag

### LINKED ISSUE #3021: Add CLI option to fail with warnings
### Feature Use Case
When building on a CI server, have the job fail if there are any warnings.

### Feature Proposal
A CLI option like `--no-warnings`, which still finishes the build and prints all warnings, but exits with a non-zero code.

### PR DESCRIPTION
**Pull request by tjenkinson**
This PR contains:
- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers: closes #3021

### Description
Adds the `--failAfterWarnings` flag which when provided causes the command to error if there were any warnings.

#### TODO
- [x] It looks like the expected output is not checked with `error: () => true`

### CODE REVIEW

File: test/cli/samples/fail-after-warnings/_expected.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+'use strict';
+
+require('unknown');
```
Comment (tjenkinson) [inline test/cli/samples/fail-after-warnings/_expected.js:3]: don't think this is been checked with `error: () => true` in this or other tests. will investigate

Comment (lukastaegert) [reply test/cli/samples/fail-after-warnings/_expected.js:3]: Please do. I checked e.g. `node-config-not-found` and changing the expected output there turned the test red.

**Comment by lukastaegert** [comment]
Nice work. I will try to have a proper look shortly.

File: test/cli/samples/fail-after-warnings/_expected.js (hunk 1 above)
Comment (tjenkinson) [reply test/cli/samples/fail-after-warnings/_expected.js]: In this case it's because I wasn't returning `true` to make it continue. In the other tests where _expected.js was being ignored I removed `_expected.js` because they didn't match, and I'm not sure if the intent was to check the output or not?

File: cli/run/index.ts [hunk 2]
```diff
@@ -67,6 +67,12 @@ export default async function runRollup(command: any) {
 				for (const inputOptions of options) {
 					await build(inputOptions, warnings, command.silent);
 				}
+				if (command.failAfterWarnings && warnings.total) {
+					throw {
+						code: 'FAIL_AFTER_WARNINGS',
+						message: 'Warnings occurred and --failAfterWarnings flag present'
+					};
```
Comment (tjenkinson) [inline cli/run/index.ts:74]: throwing the object felt a bit strange. Not sure if having a

```ts
warnings.flush();
handleError({
  code: 'FAIL_AFTER_WARNINGS',
  message: 'Warnings occurred and --failAfterWarnings flag present'
});
```
would be better?

File: test/cli/samples/fail-after-warnings/_expected.js (hunk 1 above)
Comment (lukastaegert) [reply test/cli/samples/fail-after-warnings/_expected.js]: You need to return `true` in order to continue https://github.com/rollup/rollup/blob/8333387aeb2e839d720b86921878a8afd73bde4a/test/cli/index.js#L42
`_expected.js` should be compared to stdout, but only if there is no `_expected` dir, `config.test`, `config.result`, `config.execute`, `config.stderr` that does not return `true` or `config.error` that does not return `true`.

File: cli/run/batchWarnings.ts [hunk 3]
```diff
@@ -7,18 +7,25 @@ export interface BatchWarnings {
...
+		get total() {
+			return total;
+		},
+
 		get count() {
 			return count;
 		},
 
 		add: (warning: RollupWarning) => {
+			total += 1;
```
Comment (lukastaegert) [inline cli/run/batchWarnings.ts:28]: To me it looks like `total` is absolutely identical to `count`?

File: cli/run/index.ts (hunk 2 above)
Comment (lukastaegert) [reply cli/run/index.ts:74]: Throwing something that is not an `Error` instance is always a bad idea IMO as it violates expectations. `handleError` is the correct way to do it.

File: cli/help.md [hunk 4]
```diff
@@ -49,6 +49,7 @@ Basic options:
 --preserveSymlinks          Do not follow symlinks when resolving files
 --shimMissingExports        Create shim variables for missing exports
 --silent                    Don't print warnings
+--failAfterWarnings         Exit with an error code if there was a warning during the build
```
Comment (lukastaegert) [inline cli/help.md:52]: We also need to extend documentation in the `docs` folder,  just check where and how e.g. `--enivronment` is documented.

File: cli/run/batchWarnings.ts (hunk 3 above)
Comment (tjenkinson) [reply cli/run/batchWarnings.ts:28]: The problem was `count` is reset during the `flush()`. We need to know if a warning occurred at any point, even if they've already been flushed.

Comment (lukastaegert) [reply cli/run/batchWarnings.ts:28]: Ok, then how about not counting at all but just setting a boolean from `false` to `true`?

Comment (tjenkinson) [reply cli/run/batchWarnings.ts:28]: sure will update
