### PR TITLE
Properly rename destructured parameters

### LINKED ISSUE #2418: Incorrectly renames destructured function arguments
- Rollup Version: 0.58.0
- Operating System (or Browser): any
- Node Version: 8

### How Do We Reproduce?

In functions that contain named arguments (via destructuring), and where the argument name matches an imported variable in the outer scope, Rollup incorrectly renames the argument – but without updating the locations where it is called.

```js
import {name} from ''

function test({name=10}={}) {
}
test({name: 20});
```

### Expected Behavior

[REPL 0.57.0](https://rollupjs.org/repl?version=0.57.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3Qm5hbWUlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGVfMS5qcyclNUNuJTVDbmZ1bmN0aW9uJTIwdGVzdCglN0JuYW1lJTNEMTAlN0QlM0QlN0IlN0QpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKG5hbWUpJTNCJTVDbiU3RCU1Q24lNUNubmFtZSgpJTNCJTVDbnRlc3QoJTdCbmFtZSUzQSUyMDIwJTdEKSU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlXzEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBuYW1lKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCd4JyklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

```js
function test({name: name$$1=10}={}) {
}
test({name: 20});
```

### Actual Behavior

[REPL 0.58.0](https://rollupjs.org/repl?version=0.58.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3Qm5hbWUlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGVfMS5qcyclNUNuJTVDbmZ1bmN0aW9uJTIwdGVzdCglN0JuYW1lJTNEMTAlN0QlM0QlN0IlN0QpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKG5hbWUpJTNCJTVDbiU3RCU1Q24lNUNubmFtZSgpJTNCJTVDbnRlc3QoJTdCbmFtZSUzQSUyMDIwJTdEKSU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlXzEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBuYW1lKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCd4JyklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

```js
function test({name$$1=10}={}) {
}
test({name: 20});
```

Rollup changes the named parameter but without updating the places where it is called.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevent issue numbers:
Resolves #2418

### Description
The issue was that in certain situations, cf. #2418, shorthanded properties in assignment patterns (all of this was necessary to trigger the bug) were renamed without keeping the original property name.

This one was tricky as to *why* this was broken between 0.57.1 and 0.58.0. The relevant change was the new logic to no longer switch AST prototypes but copy the AST into rollup.

The actual reason was that even though the pattern `{property = defaultVale}` produces the AST nodes `ObjectPattern > Property > AssignmentPattern > Identifier`, the old logic before 0.58.0 would mark the `Property` as the parent of the `Identifier`.

The changed logic starting with 0.58.0 unknowingly corrected this mistake by marking the `AssignmentPattern` as the parent of the `Identifier` which no longer triggered a check in the `Identifier` rendering logic.

I decided to stick with the correct parent-child relationships and changed the check in question.

### CODE REVIEW

File: src/ast/nodes/Identifier.ts [hunk 1]
```diff
@@ -160,7 +161,11 @@ export default class Identifier extends NodeBase {
 					storeName: true,
 					contentOnly: true
 				});
-				if (this.parent.type === NodeType.Property && (<Property>this.parent).shorthand) {
+				let relevantParent = this.parent;
+				if (relevantParent.type === NodeType.AssignmentPattern) {
+					relevantParent = (<AssignmentPattern>relevantParent).parent;
```
Comment (guybedford) [inline src/ast/nodes/Identifier.ts]: Perhaps skip over this path entirely - `if (this.parent.type !== NodeType.AssignmentPatern && ...`. Because surely the parent of an assignment pattern can never be an object shorthand?

**Comment by guybedford** [comment]
Ok this is quite odd - I've just run this test locally in Node 6 and am not getting any failure.

File: src/ast/nodes/Identifier.ts (hunk 1 above)
Comment (lukastaegert) [reply src/ast/nodes/Identifier.ts]: Quite to the contrary, this is the most important bit! In this example

```js
const {name = 10 } = {};
```

the parent of the assignment pattern *is* a shorthanded property (definitely worth checking this out: hhttp://astexplorer.net/#/gist/a593a01bc9b6b052a1ee898fa4f2c944/91715110ff8c51a2ad9201408ab6f76225b3bc6e )

This was in fact the only situation in which the bug triggered.

Comment (lukastaegert) [reply src/ast/nodes/Identifier.ts]: Not sure how to write this more nicely, though.

Comment (guybedford) [reply src/ast/nodes/Identifier.ts]: Ahh I see, looks good then.
