### PR TITLE
Import specifier deshadowing fix

### LINKED ISSUE #1910: module name collision
https://gist.github.com/aligon/bba460bf9dadee2d37f2214ca854e77a

I'm using an external component from another library, that I want to pass the same props to from a couple of different places. To that end, I created a wrapper component that imports the external component and renders it with the shared props. The wrapper and external component share the same class name, so in the wrapper I import the external to another name. The bundled version of the wrapper's render appears to be rendering the wrapper component, not the external component.

/cc @jsg2021

### PR DESCRIPTION
**Pull request by guybedford**
This fixes #1910.

The main fix is just the line in `src/Chunk.ts`, but in the process this exposed an idempotency bug in the deshadowing process itself in that `safeName` results from previous deshadowing runs can affect future runs.

I've fixed the idempotency bug with a reliable but hacky approach for now, hopefully we can put some thought to something better here, but correctness comes first I feel. Just let me know if I can help explain it at all further.

### CODE REVIEW

**Comment by guybedford** [comment]
(To explain the idempotency bug - it is that the `iife` format run which comes after the `es` run would have Sticky$$1 as the function deshadowing name, when the deshadowing is unnecessary for this render run, since the `safeName` would have been left over from a previous run. Ideally the `safeName` data would be a separate layer or entirely cleared between runs, but a full reset iteration seems like a performance loss.)

File: src/ast/variables/Variable.ts [hunk 1]
```diff
@@ -36,7 +36,13 @@ export default class Variable implements ExpressionEntity {
...
 	) { }
 
-	getName (): string {
+	getName (reset?: boolean): string {
+		if (reset && this.safeName && this.safeName !== this.name && 
+				this.safeName[this.name.length] === '$' &&
+				this.safeName[this.name.length + 1] === '$') {
+			this.safeName = undefined;
+			return this.name;
+		}
```
Comment (lukastaegert) [inline src/ast/variables/Variable.ts]: I see what you mean. I think this is not too bad for now but yes, this is a weird interaction between different runs we should probably fix more substantially at some point. Good catch, though 👍
