### PR TITLE
fix: ignores empty statements in class body that is returned by SWC parser

### LINKED ISSUE #5171: [v4] Rollup errors on semicolon after class method `Cannot convert ClassMember::Empty`
### Rollup Version

4.0.0

### Operating System (or Browser)

mac

### Node Version (if applicable)

18

### Link To Reproduction

https://rollupjs.org/repl/?version=4.0.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMGJhcigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCdoaScpJTNCJTVDbiUyMCUyMCU3RCUzQiUyMCUyRiUyRiUyMCUzQy0tJTIwdGhpcyUyMGlzJTIwdGhlJTIwY3VscHJpdCU1Q24lN0QlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=

### Expected Behaviour

Given the following code:
```js
export class Foo {
  bar() {
    console.log('hi');
  }; // <-- this is the culprit
}
```
(note the semicolon)

The error I'm seeing is:

```
thread '<unnamed>' panicked at parse_ast/src/convert_ast/converter.rs:562:32:
not implemented: Cannot convert ClassMember::Empty
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
sh: line 1: 50188 Abort trap: 6           NODE_OPTIONS=--max-old-space-size=8192 rollup -c rollup/prod.config.mjs
```

### Actual Behaviour

rollup doesnt crash :)

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
resolves #5171 

### Description
~~This PR also defines the default rendering of the `EmptyStatement` node~~

### CODE REVIEW

File: rust/parse_ast/src/convert_ast/converter.rs [hunk 1]
```diff
@@ -556,10 +556,10 @@ impl<'a> AstConverter<'a> {
       ClassMember::PrivateMethod(private_method) => self.convert_private_method(private_method),
       ClassMember::PrivateProp(private_property) => self.convert_private_property(private_property),
       ClassMember::StaticBlock(static_block) => self.convert_static_block(static_block),
+      ClassMember::Empty(empty_stmt) => self.convert_empty_statement(empty_stmt),
```
Comment (lukastaegert) [inline rust/parse_ast/src/convert_ast/converter.rs:559]: I think it is not correct to convert it to an empty statement. ESTree spec does not allow statements in classes https://github.com/estree/estree/blob/master/es2022.md#classbody
If you compare with what acorn does https://astexplorer.net you see that it just ignores the semicolon and does not generated an AST Node for it. I think we should do the same.

Comment (TrickyPi) [reply rust/parse_ast/src/convert_ast/converter.rs:559]: Ah, I see.

**Review by lukastaegert — APPROVED** [review]
