### PR TITLE
Fix #2353 - retain empty manual chunks

### LINKED ISSUE #2353: manualChunks option fails with unexpected error if the chunk only contains dynamic imports
Hello from Dropbox!

The manualChunks option produces an unexpected error `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined` if the chunk group only contains dynamic imports:
```
manualChunks: {
  dynamic_imports: [
    'src/dynamic_used_by_a.js',
    'src/dynamic_used_by_both.js',
  ],
},
```

Repro here:
https://github.com/taylorcode/rollup-manualchunks-dynamic-import-issue

### PR DESCRIPTION
**Pull request by guybedford**
When a chunk is empty, we skip its inclusion entirely, unless it was an entry chunk.

Manual chunks should also be included to line up with this logic, fixing the error thrown in #2353.

### CODE REVIEW

File: src/Graph.ts [hunk 1]
```diff
@@ -484,7 +484,7 @@ export default class Graph {
 				// filter out empty dependencies
 				for (let i = 0; i < chunkList.length; i++) {
 					const chunk = chunkList[i];
-					if (chunk.isEmpty && !chunk.entryModule) {
+					if (chunk.isEmpty && !chunk.entryModule && !chunk.isManualChunk) {
```
Comment (manucorporat) [inline src/Graph.ts]: i am wondering why not using .filter() here or .map() instead of:
```
 					for (const module of orderedModules) {
 						const chunkInstance = new Chunk(this, [module]);	 						const chunkInstance = new Chunk(this, [module]);
```

Comment (lukastaegert) [reply src/Graph.ts]: I agree, the `.splice`/`i--` seems unnecessarily complicated to me while providing only limited performance benefits considering this loop is only run once.

Comment (guybedford) [reply src/Graph.ts]: I'm really not sure what the suggestion is here. Can you please spell it out. Note that we are mutating an array while iterating it.

Comment (lukastaegert) [reply src/Graph.ts]:
```js
chunkList = chunkList.filter(chunk => !chunk.isEmpty || chunk.entryModule || chunk.isManualChunk);
```

Comment (lukastaegert) [reply src/Graph.ts]: Reads a little nicer 😉

Comment (guybedford) [reply src/Graph.ts]: Ah, thanks! One of those pieces of code you get so used to looking at you miss the simplification :)
