### PR TITLE
Watch files onbuild, even if build fails

### LINKED ISSUE #1773: Rollup watch has a fatal error on first run if encounters error
Repro here: https://github.com/mhkeller/rollup-fatal-watch

If I **introduce** a syntax error on a file, rollup will give me a nice error and once I've fixed it, rebuild.

If I try to run `rollup -w` on a file that **has** that same syntax error, the watch exits. I have to fix the error and then run `npm run build` again. 

It would be nicer if the behavior were the same between first run and during a build. 

Perhaps related to https://github.com/rollup/rollup/issues/1563

### PR DESCRIPTION
**Pull request by mhkeller**
This PR contains:
- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #1773 

### Description

This PR is a fix for https://github.com/rollup/rollup/issues/1773 which created inconsistent behavior between how errors were handled when using rollup watch. Before, if you had a syntax error in your file, the watch process would never get started. Now, it will watch all files in the dependency graph up until the error and keep your watch process running. This avoids the user from having to restart the watch process once the error is fixed and matches the normal rollup watch behavior.

It does this by adding the `graph` object to the error and then adding the watchers for files already scanned in the graph.

Still needed:
- [x] Test
- [x] This breaks some existing tests that rely on the error message format not having a `watchFiles` array so those need to be fixed.

### CODE REVIEW

File: src/Module.ts [hunk 1]
```diff
@@ -244,6 +244,7 @@ export default class Module {
 	error(props: RollupError, pos: number) {
 		if (pos !== undefined) {
 			props.pos = pos;
+			props.graph = this.graph;
```
Comment (Rich-Harris) [inline src/Module.ts]: Since `graph` is only being used to access `graph.watchFiles`, how about just passing those?

```suggestion
props.watchFiles = Object.keys(this.graph.watchFiles);
```

Comment (mhkeller) [reply src/Module.ts]: 👍👍 

Using `Object.keys` doesn't give you the watch files for some reason but the same `Array.from(this.graph.moduleById.keys())` does the trick. Changed in https://github.com/rollup/rollup/pull/3081/commits/7c003ac4bcd75bb44c850be9c8b46de6a56b4c1e

File: src/watch/index.ts [hunk 2]
```diff
@@ -243,9 +244,13 @@ export class Task {
 					result
 				});
 			})
-			.catch((error: Error) => {
+			.catch((error: RollupError) => {
 				if (this.closed) return;
 
+				error.watchFiles.forEach(id => {
```
Comment (mhkeller) [inline src/watch/index.ts]: May want to make this more restrictive so that it is only adding files in that initial error before any are added such as

```js
	if (this.watched.size === 0) {
	const watched = (this.watched = new Set());

	error.watchFiles.forEach(id => {
		watched.add(id);
		this.watchFile(id);
	});
}
```

File: src/Graph.ts [hunk 3]
```diff
@@ -222,7 +222,6 @@ export default class Graph {
 			for (const module of this.moduleById.values()) {
 				if (module instanceof Module) {
 					this.modules.push(module);
-					this.watchFiles[module.id] = true;
```
Comment (lukastaegert) [inline src/Graph.ts]: Instead of adding files only once loading and parsing was successful, I think it is better to add them right away before loading so that the same logic can be used for the successful and the error case.

File: src/Module.ts [hunk 4]
```diff
@@ -272,6 +272,13 @@ export default class Module {
 			props.frame = getCodeFrame(this.originalCode, location.line, location.column);
 		}
 
+		if (this.graph.phase < BuildPhase.GENERATE) {
+			const watchFiles = Object.keys(this.graph.watchFiles);
+			if (watchFiles.length > 0) {
+				props.watchFiles = watchFiles;
+			}
+		}
+
```
Comment (lukastaegert) [inline src/Module.ts]: I agree that adding the watchFiles to the error is probably the best solution, at least I could not think of a better approach. But instead of limiting it to the case where an explicit file position is provided, I changed the logic so that it triggers for every error in the build phase where there are added files, as in all those cases, the watcher will not receive any new watchFiles.

File: src/ModuleLoader.ts [hunk 5]
```diff
@@ -280,6 +280,7 @@ export class ModuleLoader {
 
 		const module: Module = new Module(this.graph, id, moduleSideEffects, isEntry);
 		this.modulesById.set(id, module);
+		this.graph.watchFiles[id] = true;
```
Comment (lukastaegert) [inline src/ModuleLoader.ts]: I think this is the best place to add the new watchFile; with this logic, files added via `this.addWatchFile` in a plugin will also not be forgotten.

File: src/watch/fileWatchers.ts [hunk 6]
```diff
@@ -60,9 +60,9 @@ export default class FileWatcher {
 
 		const handleWatchEvent = (event: string) => {
 			if (event === 'rename' || event === 'unlink') {
-				this.close();
-				group.delete(id);
+				modifiedTime = -1;
```
Comment (lukastaegert) [inline src/watch/fileWatchers.ts]: Not strictly related to the issue at hand but I noticed that when I delete and recreate a file that is required for a build to succeed, the recreation will not trigger a new run, which is bad. Now the only time watched files are removed is when a run was successful; otherwise we just accumulate watched files so that we do not miss anything important.

File: src/watch/fileWatchers.ts [hunk 7]
```diff
@@ -60,9 +60,9 @@ export default class FileWatcher {
...
 				this.trigger(id);
+				return;
```
Comment (lukastaegert) [inline src/watch/fileWatchers.ts]: No use triggering twice.

File: src/watch/index.ts [hunk 8]
```diff
@@ -48,9 +48,9 @@ export class Watcher {
 
 	close() {
 		if (this.buildTimeout) clearTimeout(this.buildTimeout);
-		this.tasks.forEach(task => {
+		for (const task of this.tasks) {
```
Comment (lukastaegert) [inline src/watch/index.ts]: I replaced some .forEach with more efficient for loops, not really related to the task but who know when I will have a look at these files the next time.

File: src/watch/index.ts [hunk 9]
```diff
@@ -243,31 +224,43 @@ export class Task {
...
-							if (module.transformDependencies) {
-								module.transformDependencies.forEach(depId => {
-									this.watchFile(depId, true);
-								});
-							}
-						});
-					}
-					this.watchFiles.forEach(id => {
+				if (Array.isArray(error.watchFiles)) {
+					for (const id of error.watchFiles) {
```
Comment (lukastaegert) [inline src/watch/index.ts]: As I see it, none of the other logic is needed if we only remove files on successful builds. I also removed the `absolutePath` logic as this is already caught in the file watcher itself; otherwise, the logic between successful runs and errors would be asymmetric. If this actually caused issues for you, we should add a test.

File: src/watch/index.ts [hunk 10]
```diff
@@ -243,31 +224,43 @@ export class Task {
...
 						this.watchFile(id);
-					});
+					}
 				}
 				throw error;
 			});
 	}
 
-	watchFile(id: string, isTransformDependency = false) {
+	private updateWatchedFiles(result: RollupBuild) {
```
Comment (lukastaegert) [inline src/watch/index.ts]: No real logic change, just to make it more readable

File: src/watch/index.ts [hunk 11]
```diff
@@ -243,31 +224,43 @@ export class Task {
...
+			}
+		}
+		for (const id of previouslyWatched) {
+			if (!this.watched.has(id)) deleteTask(id, this, this.chokidarOptionsHash);
+		}
+	}
+
+	private watchFile(id: string, isTransformDependency = false) {
 		if (!this.filter(id)) return;
+		this.watched.add(id);
```
Comment (lukastaegert) [inline src/watch/index.ts]: By doing this here, `this.watched` is strictly coupled to the watched files and we do not forget to clean up any of them. Also, `this.watched` should never be reset unless it is made sure that there are no remaining dangling watchers that are no longer tracked.

File: test/watch/index.js [hunk 12]
```diff
@@ -402,12 +515,17 @@ describe('rollup.watch', () => {
 								foo: 'foo-2',
 								bar: 'bar-1'
 							});
-							sander.writeFileSync('test/_tmp/input/bar.js', `export default 'bar-2';`);
-						},
-						() => {
-							assert.deepStrictEqual(run('../_tmp/output/bundle.js'), {
-								foo: 'foo-2',
-								bar: 'bar-1'
+							let unexpectedEvent = false;
```
Comment (lukastaegert) [inline test/watch/index.js]: This makes sure the test actually turns red when I removed the relevant logic.

**Comment by lukastaegert** [comment]
Damn, no idea why the tests are failing on CI while they appear to be running nicely locally, will investigate

**Comment by lukastaegert** [comment]
Ok, it seems only chokidar can reliably keep watching deleted files, so I made this a chokidar-only feature. Another good argument for switching to always using chokidar at some point.

File: src/Module.ts (hunk 4 above)
Comment (lukastaegert) [reply src/Module.ts]: Actually I changed it to "every error" as errors from the generate phase never seem to be triggered via this logic.

File: src/watch/fileWatchers.ts (hunk 6 above)
Comment (lukastaegert) [reply src/watch/fileWatchers.ts]: Ok, we can do this for chokidar but it does not seem to work well for fs.watch...

Comment (lukastaegert) [reply src/watch/fileWatchers.ts]: Ok, running chokidar still fails on CI. I guess I'll just have to revert this.

Comment (lukastaegert) [reply src/watch/fileWatchers.ts]: I assume it depends on the operating system if that works as chokidar will use different techniques. I guess we will need to live with this, you can still trigger another run by modifying any other file that was already part of the graph.

File: src/watch/index.ts (hunk 9 above)
Comment (lukastaegert) [reply src/watch/index.ts]: I believe this will still happen. At the moment, those will be filtered out here: https://github.com/rollup/rollup/blob/1429d571908319df6c1b9c8f722c525c2077c66e/src/watch/fileWatchers.ts#L52

But we can save us a few unneeded `fs.statSync`. I think the proper place would be to do this in the watcher logic—similar how you did it but symmetric for all situations—as Rollup core should not know about which files are "watchable". In the future, I hope we can make the watcher completely pluggable so that you can e.g. use TypeScripts watcher, but that's another story. I will add this before we merge this.

Comment (lukastaegert) [reply src/watch/index.ts]: Ah, it seems that just checking for `isAbsolute` is not enough because it is supported (and tested) to add non-absolute watch files via `this.addWatchFile`. So I guess we stick with the old logic

**Comment by oscar-b** [comment]
@mhkeller @lukastaegert Using rollup v1.25.1 I'm still seeing the original issue with watch not firing after an initial error. Looking through this PR, it seems like it should be fixed when using chokidar, but it doesn't work here (chokidar v3, macOS).

I'm testing by introducing a syntax error before starting `rollup -c -w`:
```
export *a from './Something';
```

I have this in my `rollup.config.js` (but also tried with just `chokidar: true`:
```
watch: {
	chokidar: { atomic: true },
},```

It doesn't make any difference to activate polling mode either using `CHOKIDAR_USEPOLLING=true`.

Any other ideas?
