### PR TITLE
[v4.0] fix: also strip BOM from code strings in JS

### LINKED ISSUE #5162: [v4] Invalid variable name generated when importing from UTF-8 with BOM file
### Rollup Version

4.0.0-23

### Operating System (or Browser)

Windows

### Node Version (if applicable)

18.17.1

### Link To Reproduction

https://github.com/sapphi-red-repros/rollup-bom-invalid-variable-name-generated

### Expected Behaviour

The generated code is valid.
```js
const msg$1g = 'foo;'

// import from a utf-8 bom file
const msg = 'foo';
console.log(msg, msg$1);
```

### Actual Behaviour

The generated code is invalid.
```js
constmsg$1g = 'foo;'

// import from a utf-8 bom file
const msg = 'foo';
console.log(msg, msg$1);
```

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

- resolves #5162

### CODE REVIEW

File: src/Module.ts [hunk 1]
```diff
@@ -798,6 +798,11 @@ export default class Module {
 		resolvedIds?: ResolvedIdMap;
 		transformFiles?: EmittedFile[] | undefined;
 	}): void {
+		/* eslint-disable-next-line unicorn/number-literal-case */
+		if (code.charCodeAt(0) === 0xfe_ff) {
+			code = code.slice(1);
+		}
+
```
Comment (lukastaegert) [inline src/Module.ts:805]: Reading up in Wikipedia about BOMs, I am not 100% sure if this fully resolves the issue in all cases, but it looks reasonable.

**Review by lukastaegert — APPROVED** [review]

File: src/Module.ts (hunk 1 above)
Comment (TrickyPi) [reply src/Module.ts:805]: Yeah, I'm also not 100% sure, but I had a look at `SWC` and `strip-bom`(npm package), It seems that they also do the same thing. If there are any uncovered cases, we can fix them later.
