### PR TITLE
Wrap simplified assignments if necessary

### LINKED ISSUE #3950: removed unused variable and cause syntax error of bind function
- Rollup Version: 2.83.3
- Operating System (or Browser): Mac Chrome
- Node Version (if applicable): 14.53
- Link to reproduction (IMPORTANT, read below):  https://repl.it/@loveppears/rollup-repro-1

I am building a js library which requires a 3rd library `lottie`, and it has the following code

```
var wiggle = function wiggle(){}.bind(this)
```

But after I import it and build it, I got error in the line below

```
function wiggle(){}.bind(this)
```

uncaught syntaxerror unexpected identifier '.'

download the zip from `repl` and build it then open the `dist/index.html` , you could find this error.

Could you please tell me how can I avoid this

### Expected Behavior
```
var wiggle = function wiggle(){}.bind(this)
```
### Actual Behavior

```
function wiggle(){}.bind(this)
```

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3950

### Description
See #3950 
When simplifying assignments, it was possible that invalid code was generated. https://rollupjs.org/repl/?version=2.38.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwdW51c2VkMSUyMCUzRCUyMGZ1bmN0aW9uKCklN0IlN0Quc29tZUZ1bmN0aW9uKCklM0IlNUNuY29uc3QlMjB1bnVzZWQyJTIwJTNEJTIwY2xhc3MlN0IlN0Quc29tZUZ1bmN0aW9uKCklM0IlNUNuY29uc3QlMjB1bnVzZWQzJTIwJTNEJTIwJTdCJTdELnNvbWVGdW5jdGlvbigpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

This is fixed in this PR by wrapping expressions in parentheses if necessary:
https://rollupjs.org/repl/?circleci=14200&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwdW51c2VkMSUyMCUzRCUyMGZ1bmN0aW9uKCklN0IlN0Quc29tZUZ1bmN0aW9uKCklM0IlNUNuY29uc3QlMjB1bnVzZWQyJTIwJTNEJTIwY2xhc3MlN0IlN0Quc29tZUZ1bmN0aW9uKCklM0IlNUNuY29uc3QlMjB1bnVzZWQzJTIwJTNEJTIwJTdCJTdELnNvbWVGdW5jdGlvbigpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Additionally this PR slightly improves white-space rendering when simplifying certain expressions and also prevents an ASI issue when simplifying assignments:
https://rollupjs.org/repl/?version=2.38.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwdGVzdCgpJTIwJTdCJTVDbiUyMCUyMHZhciUyMHglM0IlNUNuJTVDdHJldHVybiUyMHglMjAlM0QlMjAlMkYqJTIwY29tbWVudCUyMColMkYlNUNuJTVDdCU1Q3Q0MiUzQiU1Q24lN0QlNUNuY29uc29sZS5sb2codGVzdCgpKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=
Fixed:
https://rollupjs.org/repl/?circleci=14200&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwdGVzdCgpJTIwJTdCJTVDbiUyMCUyMHZhciUyMHglM0IlNUNuJTVDdHJldHVybiUyMHglMjAlM0QlMjAlMkYqJTIwY29tbWVudCUyMColMkYlNUNuJTVDdCU1Q3Q0MiUzQiU1Q24lN0QlNUNuY29uc29sZS5sb2codGVzdCgpKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### CODE REVIEW

File: test/form/samples/builtin-prototypes/object-expression/_expected.js [hunk 1]
```diff
@@ -1,11 +1,11 @@
 const object = {};
 object.propertyIsEnumerable( 'toString' );
-{}.propertyIsEnumerable( 'toString' );
-{}.propertyIsEnumerable( 'toString' ).valueOf();
+({}).propertyIsEnumerable( 'toString' );
+({}).propertyIsEnumerable( 'toString' ).valueOf();
```
Comment (kzc) [inline test/form/samples/builtin-prototypes/object-expression/_expected.js:4]: @lukastaegert If all test output is reparsed with acorn in the test framework then issues like this one could be caught earlier in the future. Please ignore if this PR already implemented this suggestion, but I did not see it.

For example, using the previous version of this file:
```
$ rollup test/form/samples/builtin-prototypes/object-expression/_expected.js --silent
[!] Error: Unexpected token
test/form/samples/builtin-prototypes/object-expression/_expected.js (3:2)
1: const object = {};
2: object.propertyIsEnumerable( 'toString' );
3: {}.propertyIsEnumerable( 'toString' );
     ^
4: {}.propertyIsEnumerable( 'toString' ).valueOf();
Error: Unexpected token
```

Comment (kzc) [reply test/form/samples/builtin-prototypes/object-expression/_expected.js:4]: With 574050be1f3a7197945b8adb2624a10f496af693:

```
$ rollup --silent < test/form/samples/system-export-compact/_expected.js
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
- (3:8)
1: System.register([],function(exports){'use strict';return{execute:function(){exports({a:void 0,b:void 0,c:void 0});let a, b;
2: 
3: function(v){return exports({a:a}),v}([{ b: a = (exports('a',a-1),a--) }] = { b: function(v){return exports({b:v,c:v}),v}(--b) });}}});
           ^
```
```
$ rollup --silent < test/form/samples/system-multiple-export-bindings/_expected.js 
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
- (47:12)
45: 
46:       // Update Expression
47:       function (v) { return exports({ a: v, a2: v }), v; }(++a), (exports('b', b + 1), b++), (++c, exports({ c: c, c2: c }), c);
                   ^
```

**Comment by kzc** [comment]
The following patch finds the above errors in `test/form` by running each test's output through acorn. It does not significantly slow down `npm test`. Something similar could be done to catch possible ill-formed expected output in `test/chunking-form/index.js` and `test/cli/index.js`.

```patch
diff --git a/test/form/index.js b/test/form/index.js
index 4e329c4..2734cfc 100644
--- a/test/form/index.js
+++ b/test/form/index.js
@@ -13,34 +13,48 @@ runTestSuiteWithSamples('form', path.resolve(__dirname, 'samples'), (dir, config
     path.basename(dir) + ': ' + config.description,
     () => {
       let bundle;
+      let parse;
       const runRollupTest = async (inputFile, bundleFile, defaultFormat) => {
         if (config.before) config.before();
         try {
           process.chdir(dir);
-          bundle =
-            bundle ||
-            (await rollup.rollup(
-              Object.assign(
-                {
-                  input: dir + '/main.js',
-                  onwarn: warning => {
-                    if (
-                      !(
-                        config.expectedWarnings &&
-                        config.expectedWarnings.indexOf(warning.code) >= 0
-                      )
-                    ) {
-                      throw new Error(
-                        `Unexpected warnings (${warning.code}): ${warning.message}\n` +
-                          'If you expect warnings, list their codes in config.expectedWarnings'
-                      );
-                    }
-                  },
-                  strictDeprecations: true
-                },
-                config.options || {}
-              )
-            ));
+          let options = Object.assign(
+            {
+              input: dir + '/main.js',
+              onwarn: warning => {
+                if (
+                  !(
+                    config.expectedWarnings &&
+                    config.expectedWarnings.indexOf(warning.code) >= 0
+                  )
+                ) {
+                  throw new Error(
+                    `Unexpected warnings (${warning.code}): ${warning.message}\n` +
+                      'If you expect warnings, list their codes in config.expectedWarnings'
+                  );
+                }
+              },
+              strictDeprecations: true,
+            },
+            config.options || {}
+          );
+
+          // Get the test specific acorn parser.
+          // Add a buildStart hook without destroying possible test plugins.
+          if (options.plugins) {
+            if (!Array.isArray(options.plugins)) {
+              options.plugins = [ options.plugins ];
+            }
+          } else {
+            options.plugins = [];
+          }
+          options.plugins.push({
+            buildStart() {
+              parse = this.parse;
+            }
+          });
+
+          bundle = bundle || await rollup.rollup(options);
           await generateAndTestBundle(
             bundle,
             Object.assign(
@@ -52,7 +66,8 @@ runTestSuiteWithSamples('form', path.resolve(__dirname, 'samples'), (dir, config
               (config.options || {}).output || {}
             ),
             bundleFile,
-            config
+            config,
+            parse
           );
         } finally {
           if (config.after) config.after();
@@ -76,7 +91,7 @@ runTestSuiteWithSamples('form', path.resolve(__dirname, 'samples'), (dir, config
   );
 });
 
-async function generateAndTestBundle(bundle, outputOptions, expectedFile, { show }) {
+async function generateAndTestBundle(bundle, outputOptions, expectedFile, { show }, parse) {
   await bundle.write(outputOptions);
   const actualCode = normaliseOutput(sander.readFileSync(outputOptions.file));
   let expectedCode;
@@ -89,6 +104,13 @@ async function generateAndTestBundle(bundle, outputOptions, expectedFile, { show
     expectedCode = 'missing file';
   }
 
+  // verify that the expected output is valid
+  try {
+    parse(expectedCode);
+  } catch (err) {
+    expectedCode = `expected code is ill-formed: ${outputOptions.file}: ${err}`;
+  }
+
   try {
     actualMap = JSON.parse(sander.readFileSync(outputOptions.file + '.map').toString());
     actualMap.sourcesContent = actualMap.sourcesContent
```

**Comment by kzc** [comment]
Ignore the patch above. A more comprehensive solution to output verification is #3952.
