### PR TITLE
Preserve empty for...of loops

### LINKED ISSUE #3126: treeshake incorrectly removes empty for..of and for await..of loops
Awesome tool! Thanks!

- Rollup Version: 1.21.4
- Operating System (or Browser): Ubuntu 16.04.6 LTS, also Firefox 69 and Electron
- Node Version: 10.16.0

### How Do We Reproduce?

Replicated in [REPL](https://rollupjs.org/repl/?version=1.21.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYXdhaXRhYmxlJTIwJTNEJTIwYXN5bmMlMjAoaXRlcmFibGUpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rmb3IlMjBhd2FpdCUyMChjb25zdCUyMHZhbHVlJTIwb2YlMjBpdGVyYWJsZSklMjAlN0IlNUNuJTVDdCU3RCU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBpcyUyMGVxdWl2YWxlbnQlMjB0byUyMHRoZSUyMGFib3ZlJTIwJ2F3YWl0YWJsZSclMjBmdW5jdGlvbi4lNUNuZXhwb3J0JTIwY29uc3QlMjBlcXVpdmFsZW50JTIwJTNEJTIwYXN5bmMlMjAoaXRlcmFibGUpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rjb25zdCUyMGl0ZXJhdG9yJTIwJTNEJTIwaXRlcmFibGUlNUJTeW1ib2wuYXN5bmNJdGVyYXRvciU1RCgpJTVDbiUyMCUyMGxldCUyMCU3QiUyMGRvbmUlMjAlN0QlMjAlM0QlMjBhd2FpdCUyMGl0ZXJhdG9yLm5leHQoKSU1Q24lMjAlMjB3aGlsZSUyMCghZG9uZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwKCU3QiUyMGRvbmUlMjAlN0QlMjAlM0QlMjBhd2FpdCUyMGl0ZXJhdG9yLm5leHQoKSklNUNuJTIwJTIwJTdEJTVDbiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwaXRlcmF0ZSUyMCUzRCUyMGl0ZXJhYmxlJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3Rmb3IlMjAoY29uc3QlMjB2YWx1ZSUyMG9mJTIwaXRlcmFibGUpJTIwJTdCJTVDbiU1Q3QlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyYW1kJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### Expected Behavior

The empty loops for sync and async for..of iteration should not be removed. They call iterator.next() multiple times, and are doing work.

### Actual Behavior

The empty loops are removed. As the REPL example shows, manually doing the iteration with a while loop and iterator.next() is a workaround.

I'm using code like this to iterate over chained async generators. For async code, it is the generators that do the work (HTTP queries, writing to DB, etc). I don't need to see the resolved values.

```javascript
export const awaitable = async (iterable) => {
   // This loop is removed, but it calls iterator.next(), which can have side-effects
  for await (const value of iterable) {
  }
}
```

### PR DESCRIPTION
**Pull request by imatlopez**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers: fixes #3126 

### Description

Since there is no proper support for Symbol.Iterator, drop the side effect (but don't remove) the algorithm such that iterators with side-effects are not omitted.

### CODE REVIEW

File: src/ast/nodes/ForOfStatement.ts [hunk 1]
```diff
@@ -27,14 +27,17 @@ export default class ForOfStatement extends StatementBase {
...
+		// Placeholder until proper Symbol.Iterator support
+		return true;
+
+		// return (
+		// 	(this.left &&
+		// 		(this.left.hasEffects(options) ||
+		// 			this.left.hasEffectsWhenAssignedAtPath(EMPTY_PATH, options))) ||
+		// 	(this.right && this.right.hasEffects(options)) ||
+		// 	this.body.hasEffects(options.setIgnoreBreakStatements())
+		// );
```
Comment (lukastaegert) [inline src/ast/nodes/ForOfStatement.ts]: Could you get rid of the commented code and commented import?

File: test/function/samples/preserve-for-of-iterable/iterables.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+        return {
+            current: 0,
+            last: 5,
+            next() {
+                const ret = this.current < this.last
+                    ? { done: false, value: this.current++ }
+                    : { done: true };
+                
+                // assert later
+                global.foo = this.current;
```
Comment (lukastaegert) [inline test/function/samples/preserve-for-of-iterable/iterables.js]: A cooler way than mutating a global and testing our test isolation would be to export a mutable `export let ...` binding and checking that.

**Comment by lukastaegert** [comment]
Also, I fear to greater part of work would be to adapt the existing test suite
