### PR TITLE
Fix large variable count numbering

### LINKED ISSUE #2241: If a project has more than 62 variables named the same thing, Rollup overwrites them
# Problem

If a bundled project has more than 62 variables named the same thing, Rollup will begin overwriting them starting with occurrence 63.

# Use Case

Nearly every module in my project brings in localization data as `var translations`. Today, I added the 63rd instance, and it overwrote the variable loaded in a prior instance.

I *could* locally rename the variables like `var module1Translations`, `var module2Translations`, etc., but this should not be necessary, as module scopes should be isolated.

It also depends on global knowledge ("you can't name more than 62 things the same thing in the entire project"), which won't scale.

# Reproduction

[GitLab Repository](https://gitlab.com/rockerest/too-many-rollup-variables).

Steps:
 1. Clone
 2. `npm install && npm run generate && npm run bundle`
 3. Examine `browser.js`

Slightly more info in the repository README.

# Assumption

My assumption in this scenario is that Rollup would maintain a list of previously used aliases and - when generating a new alias - check it first against the list. If it encounters a duplicate, it would begin appending more characters to the end instead of looping back to the first option.

### PR DESCRIPTION
**Pull request by guybedford**
Because of the special treatment of `$$` in variable deshadowing, we need to avoid outputting this as a trailer in safe import binding deshadowing. This limits the base output to 63 to avoid the use of `$` possibly creating a `$$` output.

Fixes #2241.

### CODE REVIEW

File: src/utils/base64.ts [hunk 1]
```diff
@@ -1,10 +1,11 @@
-const chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_';
+const chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_$';
 
-export function toBase64(num: number) {
+export function toBase64(num: number, base63 = false) {
```
Comment (lukastaegert) [inline src/utils/base64.ts]: Is there any reason why we should not always use base63? As far as I can see, this is only used for deshadowing anyway so there should not be any issues. But using a function `toBase64` to convert to base 63 but only in some situations seems a little weird.

**Comment by guybedford** [comment]
Variable deshadowing in combined scopes will still use base64 for what it is worth. We could certainly make both base63, just that 64 is a nice number really to keep.
