### PR TITLE
Resolve #2191: Add spaces after return and yield if necessary

### LINKED ISSUE #2191: Rollup produces invalid code (from some valid code produced by babel-minify)
Hi!
When I try to rollup this:
```javascript
global.foo=()=>{return!1,null};
```
I get this:
```javascript
'use strict';

global.foo=()=>{returnnull};

```
Which is invalid, and I would have expected something like this:
```javascript
'use strict';

global.foo=()=>{return null};

```

Here is the test case to reproduce:
https://github.com/tex0l/bug-report-rollup

The input snippet of the test case was produced by using `babel-minify@0.4.3` on this (check the commit history, I initially thought it was a problem with `rollup-plugin-babel`):
```javascript
global.foo = () => {
  const bar = {}
  if (false) {}
  return null
}

```

### PR DESCRIPTION
**Pull request by lukastaegert**
After some deliberation, this is the lowest impact fix I could come up with to resolve #2191. Basically as far as I am aware, this issue can only arise for `return` statements and `yield` expressions when there is no space between the keyword and the subsequent expression and the nested expression changes due to some simplification.

E.g. `return!1||true` -> `return true`.

For `await` expressions this is not an issue as operator precedence is different here (`await!1||true` is equivalent to `(await !1) || true`)

The solution is to insert a space if the argument of the `return` statement starts directly after the last letter of `return`, similarly for `yield`.

### CODE REVIEW

File: src/ast/nodes/YieldExpression.ts [hunk 1]
```diff
@@ -1,13 +1,26 @@
...
+			!options.ignoreReturnAwaitYield() || (this.argument && this.argument.hasEffects(options))
+		);
+	}
+
+	render(code: MagicString, options: RenderOptions) {
+		if (this.argument) {
+			this.argument.render(code, options);
+			if (this.argument.start === this.start + 5 /* 'yield'.length */) {
+				code.prependLeft(this.start + 5, ' ');
+			}
```
Comment (guybedford) [inline src/ast/nodes/YieldExpression.ts]: Should we try and preserve handling of `return!x` style cases though here?

**Comment by kzc** [comment]
> Operator precedence says it is not necessary. This situation can only occur if to the right side of the operator, there is an expression that can be simplified.

Are parens ever dropped for simplified expressions? If so, that could be an issue.

**Comment by lukastaegert** [comment]
Released as 0.59.1

**Comment by lukastaegert** [comment]
> Are parens ever dropped for simplified expressions? If so, that could be an issue

If the parent contains parens, those will always be retained. In some situations, this can lead to double parens but this is usually not an issue.
