### PR TITLE
Fix unreasonably slow bundle time on sourcemaps with long lines

### LINKED ISSUE #1553: Sourcemap true/'inline' significantly increases bundle time
Reproduction repository: https://github.com/houli/rollup-sourcemap-repro

Steps to reproduce:
1. Clone the reproduction repository
2. Run `yarn/npm install`
3. Run `rollup -c` and note short bundle time
4. Change `sourceMap` in `rollup.config.js`
5. Run `rollup -c` again and note long bundle time
screen shot 2017-08-15 at 22 59 39

The above demonstrates the time taken when using an inline sourcemap and with sourcemaps then disabled.
I initially noticed this issue when using https://github.com/jlmakes/karma-rollup-preprocessor as a way to use rollup with Karma tests. Inline sourcemaps are important for Karma tests as each test file will be transformed into one iife bundle that can be executed in the browser.

### LINKED ISSUE #1700: Build takes about 2-3 minutes
Rollup version: "^0.50.0"
OS: macOS Sierra 10.12.3

I was using Rollup on my previous project on this (the same as I have now) computer and with almost the same configuration.  Back then the build used to take about **1-2 seconds**.

Now on my new project the build takes on my computer **2-3 minutes**. On my friends Windows 10 it takes **25-60 seconds** (and I am not talking about the initial build, it does the same every build).

Is it possible to somehow build it faster? Because right now it's **unusable**...

Here is my `rollup.config.js`:

```javascript
import alias from 'rollup-plugin-alias';
import vue from 'rollup-plugin-vue2';
import buble from 'rollup-plugin-buble';
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';

const plugins = [
  alias({
    'vue': './../node_modules/vue/dist/vue.min.js',
  }),
  vue(),
  buble({ exclude: 'node_modules/**' }),
  nodeResolve({ browser: true, jsnext: true }),
  commonjs(),
];

if (process.env.NODE_ENV === 'production') {
  plugins.push(uglify());
}

if (process.env.NODE_ENV === 'development') {
}

export default {
  input: 'src/main.js',
  sourcemap: true,
  plugins,
  output: {
    file: 'dist/app.min.js',
    format: 'iife'
  }
};
```

And the file it generates looks like this (it's not even that big as the file in my last project):
https://pastebin.com/pDELSAZR

(btw it's just a beginning of the project, so it's totally incomplete and small)

### PR DESCRIPTION
**Pull request by mourner**
Fixes #1553. Fixes #1700.

For some builds like in the issues above, `traceSegment` in `collapseSourcemaps.ts` took unreasonably long time because some of the source maps contained very long lines (e.g. one example line had 50k segments), and linearly searching through them for every segment that needed tracing was too slow. This PR switches `traceSegment` to use simple binary search, fixing the issue.

Bundle times for the [repro case](https://github.com/houli/rollup-sourcemap-repro) in #1553:

- `sourceMap: false` (`master` rollup): 2.1s
- `sourceMap: true` (`master` rollup): 15.5s
- `sourceMap: true` (this branch): 2.4s

cc @lukastaegert

### CODE REVIEW

**Comment by mourner** [comment]
The tests are passing locally — looks like the [failure above for Node v8](https://travis-ci.org/rollup/rollup/jobs/385245381) is just an unlucky run with an unrelated error (NPM misbehaving):

```
npm ERR! 429 Too Many Requests: is-extglob@https://registry.npmjs.org/is-extglob/-/is-extglob-1.0.0.tgz
```

File: src/utils/collapseSourcemaps.ts [hunk 1]
```diff
@@ -110,15 +110,24 @@ class Link {
...
 				const source = this.sources[segment[1]];
 				if (!source) return null;
 
 				return source.traceSegment(segment[2], segment[3], this.names[segment[4]] || name);
 			}
+			if (segment[0] > column) {
+				j = m - 1;
+			} else {
+				i = m + 1;
+			}
```
Comment (lukastaegert) [inline src/utils/collapseSourcemaps.ts]: 👍
