### PR TITLE
handle a => a at top level

### LINKED ISSUE #403: Exception parsing arrow functions
I get an exception when using Rollup on arrow functions that return a single identifier:
```js
// main.js
const f = a => a;
console.log(f(1));
```
```
$ rollup -i main.js
Cannot read property 'type' of null
[...]
```
This also causes an exception:
```js
const a = 1;
const f = () => a;
console.log(f());
```
This works fine though:
```js
const f = (a => a);
console.log(f(1));
```

### PR DESCRIPTION
**Pull request by Rich-Harris**
Fixes #403

### CODE REVIEW

File: src/ast/isReference.js [hunk 1]
```diff
@@ -4,6 +4,8 @@ export default function isReference ( node, parent ) {
 	}
 
 	if ( node.type === 'Identifier' ) {
+		if ( !parent ) return true;
```
Comment (Victorystick) [inline src/ast/isReference.js]: Perhaps add a comment explaining why this exists? It's a special case.

Comment (eventualbuddha) [inline src/ast/isReference.js]: It's not clear from the commit code alone why there'd be no parent. Is `parent` not the node that most immediately contains `node`? If it is, then only `Program` nodes don't have parents, right?

Comment (Rich-Harris) [inline src/ast/isReference.js]: It's true that only `Program` doesn't have a parent, but as far as the enter handler goes it depends where you start the walk – in this situation we're starting at the function body. Ordinarily you couldn't reach an identifier node without first going through its parent, but there's an exception in this case, because an identifier can form the entire body of an arrow function expression. Adding a comment to the code
