### PR TITLE
Do not resolve external dynamic imports via plugins

### LINKED ISSUE #2481: Regression when resolving the module ids of externalised dynamic imports of NPM packages in rollup@0.66.2
- Rollup Version: `0.66.2`
- Operating System (or Browser): OSX
- Node Version: `10.10.0`

There seems to have been a regression between `0.64.1` and `0.66.2` in the output of externalised dynamic imports of NPM packages when also using `rollup-plugin-node-resolve`.

Previously neither static imports or dynamic imports would call `rollup-plugin-node-resolve#resolveId` on an externalised module. However, since updating `rollup` I've noticed that external dynamic imports are now inconsistent with static imports and do resolve their `module.id` into an absolute path.

This causes the production of JavaScript which can only be installed on the machine they were built on.

The bug might have been introduced within [the Plugin System Refactoring](https://github.com/rollup/rollup/pull/2382) by @guybedford or in subsequent changes.

In the short-term I am able to explicitly cause `rollup-plugin-node-resolve` to treat certain packages as being externalised by passing in a regex of `/^(?!externalised-pkg-name).*$/` into `options#only`.

### How Do We Reproduce?

Clone [`sebinsua/rollup-resolve-externalised-dynamic-imports`](https://github.com/sebinsua/rollup-resolve-externalised-dynamic-imports), run `npm install` and then run `npm run build` and look at the generated JavaScript.

### Expected Behavior

```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React = _interopDefault(require('react'));

var test = function test() {
  return React;
};

var someDynamicImport = function someDynamicImport() {
  var test = Promise.resolve(require('react'));
  return test;
};

exports.test = test;
exports.someDynamicImport = someDynamicImport;
```

### Actual Behavior

```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React = _interopDefault(require('react'));

var test = function test() {
  return React;
};

var someDynamicImport = function someDynamicImport() {
  var test = Promise.resolve({ default: require("/Users/my-username/dev/rollup-resolve-externalised-dynamic-imports/node_modules/react/index.js") });
  return test;
};

exports.test = test;
exports.someDynamicImport = someDynamicImport;
```

### LINKED ISSUE #2487: Subsequent dynamic import of the same external module result in erroneous substitution of resolution namespace
- Rollup Version: 0.66.2
- Operating System (or Browser): n/a
- Node Version: 9.11.2 and 10.9.0

### How Do We Reproduce?

Consider the following files:

```js
// app.js
export function loadPage() {
  if (someCondition()) {
    import('./some-module.js');
  }
  if (someOtherCondition) {
    import('./some-module.js');
 }
}
```
```js
// some-module.js
console.log('I have been loaded.');
```

I don't want rollup to inline any of the dynamically imported components, so I provide the fully resolved path to them in my as external option:
```bash
$ rollup app.js --output.format esm --external /resolved/path/to/some-module.js
```

### Expected Behavior

```js
// app.js
function loadPage() {
  if (someCondition()) {
    import('./some-module.js');
  }
  if (someOtherCondition) {
    import('./some-module.js');
 }
}

var app = /*#__PURE__*/Object.freeze({
  loadPage: loadPage
});

export { loadPage };
```

### Actual Behavior

The first instance of the dynamic import of `some-module.js` leaks the local path name in the rolled up result.  I think this called out by https://github.com/rollup/rollup/issues/2481

However, the second instance of the dynamic import of `some-module.js` is replaced with a promise returning the resolution namespace of `app` which is totally bogus.

```js
// app.js
function loadPage() {
  if (someCondition()) {
    import("/Users/brendanb/src/github.com/usergenic/rollup-dynamic-import-problem/some-module.js");
  }
  if (someOtherCondition) {
    Promise.resolve().then(function () { return app; });
 }
}

var app = /*#__PURE__*/Object.freeze({
  loadPage: loadPage
});

export { loadPage };
```

💔

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolve #2481 
Resolve #2487 (probably)

### Description
Before refactoring the plugin system, external ids would never be passed to plugin hooks for further resolution. This was broken for the resolution of dynamic imports.

This restores the old logic up to v0.64.1

### CODE REVIEW

File: src/utils/pluginDriver.ts [hunk 1]
```diff
@@ -104,7 +104,9 @@ export function createPluginDriver(
 			},
 			parse: graph.contextParse,
 			resolveId(id: string, parent: string) {
-				return pluginDriver.hookFirst('resolveId', [id, parent]);
+				return this.isExternal(id, parent, false)
+					? false
+					: pluginDriver.hookFirst('resolveId', [id, parent]);
```
Comment (guybedford) [inline src/utils/pluginDriver.ts]: This logic is now duplicated with https://github.com/rollup/rollup/blob/master/src/Graph.ts#L783.

I would prefer if we could keep the separation for all calls the same I think.

**Comment by lukastaegert** [comment]
@guybedford I moved the external check for dynamic imports into the default plugin handler for the resolve dynamic import hook. I guess this does make more sense though there is still some duplication between dynamic and non-dynamic import resolution. Please tell me, if this would work for you.

**Comment by lukastaegert** [comment]
Will merge this for now in its changed form as this definitely needs fixing. Feel free to add further comments to this PR if the current solution should be further improved.
