### PR TITLE
Track inclusion of entities returned by literal methods

### LINKED ISSUE #2253: Rollup JavaScript slice/push does not appear to work
Rollup's rollup.config.js processing fails to process the following JavaScript correctly.
--------------------------------------
NodeJS example:
$ cat example.js
var someArray = [ 'a' ];
var copyOfArray = someArray.slice();

someArray.push('b');
console.log('someArray = ' + someArray);

copyOfArray.push('b');
console.log('copyOfArfay = ' + copyOfArray);

$ node example.js
someArray = a,b
copyOfArfay = a,b

--------------------------------------
Rollup example:
If place the same code in a rollup.config.js file, I see incorrect results:
$ cat rollup.config.js
var someArray = [ 'a' ];
var copyOfArray = someArray.slice();

someArray.push('b');
console.log('someArray = ' + someArray);

copyOfArray.push('b');
console.log('copyOfArray = ' + copyOfArray);

$ node_modules/rollup/bin/rollup -c rollup.config.js
someArray = a,b
copyOfArray = a

copyOfArray should report a,b, not just a.

### PR DESCRIPTION
**Pull request by lukastaegert**
This resolves #2253 by internally using instances that can track their own inclusion status for return values of literal methods. E.g. in this example:

```js
const virtual = [1, 2].slice();
virtual.push(3);
const otherVirtual = virtual.slice();
console.log(virtual);
```

the line `virtual.push(3)` will be included as `virtual` itself is included due to the `console.log` statement. The third line, on the other hand, is still removed as it is no side-effect.

To be able to do that, a larger refactoring was necessary. The main issue was that in order to track the inclusion status of an entity that is not represented by an AST node, another AST node needed to take up that responsibility. In this case, the respective `CallExpression` seemed the natural choice (each call to `Array.prototype.slice` creates an independent new object).

Thus I needed to change the fundamental logic that tracks side-effects around return expressions. Instead of e.g. the call expression "asking" a function declaration if calling its return value has a side-effect, the call expression initially asks the function declaration for its return expression, stores this value and then directly performs queries on this return expression.

The only (tested) situation where this performs less optimal than before is when we call an expression that can resolve to more than one possible callable entity. In this case, we just treat the return value as "unknown".

### CODE REVIEW

**Comment by lukastaegert** [comment]
This also provides another noticeable performance boost (e.g. bundling the TypeScript compiler is now >20% faster)

**Comment by lukastaegert** [comment]
Also note the negative diff :)

File: src/ast/nodes/ObjectExpression.ts [hunk 1]
```diff
@@ -85,6 +62,34 @@ export default class ObjectExpression extends NodeBase {
...
+			EMPTY_IMMUTABLE_TRACKER
+		);
+		if (
+			path.length === 1 &&
+			typeof key === 'string' &&
+			objectMembers[key] &&
+			properties.length === 0
+		)
+			return getMemberReturnExpressionWhenCalled(objectMembers, key);
+		if (!hasCertainHit || properties.length > 1) return UNKNOWN_EXPRESSION;
```
Comment (guybedford) [inline src/ast/nodes/ObjectExpression.ts]: I look forward to `PossibleExpressionSet` :)

File: src/ast/nodes/Property.ts [hunk 2]
```diff
@@ -23,48 +21,55 @@ export default class Property extends NodeBase {
...
 	}
 
-	getLiteralValueAtPath(
+	getReturnExpressionWhenCalledAtPath(
 		path: ObjectPath,
 		recursionTracker: ImmutableEntityPathTracker
-	): LiteralValueOrUnknown {
+	): ExpressionEntity {
+		if (this.kind === 'set') {
+			return UNKNOWN_EXPRESSION;
```
Comment (guybedford) [inline src/ast/nodes/Property.ts]: Again could be nice to have `THROWS_EXPRESSION` or similar.

File: src/ast/nodes/ArrayExpression.ts [hunk 3]
```diff
@@ -2,19 +2,24 @@ import CallOptions from '../CallOptions';
...
-import { SomeReturnExpressionCallback } from './shared/Expression';
 import { ExpressionNode, NodeBase } from './shared/Node';
 import SpreadElement from './SpreadElement';
 
 export default class ArrayExpression extends NodeBase {
 	type: NodeType.tArrayExpression;
 	elements: (ExpressionNode | SpreadElement | null)[];
 
+	getReturnExpressionWhenCalledAtPath(path: ObjectPath) {
+		if (path.length !== 1) return UNKNOWN_EXPRESSION;
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/ArrayExpression.ts]: Sure we could. What is your intention here:
* documentation, or
* improved tree-shaking in certain situations?

I am a little hesitant to do this just in a few places as there are quite a lot of situations where we deoptimize because we would do something illegal and having it done in some places only could leave people falsely relying on this.

If you see some potential tree-shaking benefit, it might be worth doing it in all relevant places in a separate PR.
