### PR TITLE
fix(watch): don't use alternate screen if clearScreen is set

### LINKED ISSUE #1804: rollup --watch clears screen even though it's configured not to
Following up on the comment in the PR #1688 . I have the same issue as @futuris88. I run rollup on fish using the stock Terminal app on macOS High Sierra.

I tried to turn off the `clearScreen` feature by configuration, but was not successful. The output on my screen still gets reset.

I tried to update the source to not do this, but had to destructively change a *lot* to make this work. This is also why I haven't provided a PR yet.

My `rollup.config.js` looks roughly like this:
```js
export default {
  name: '...',
  input: './built/src/app/client.js',
  output: {
    file:   './public/client.js',
    exports: 'named',
    format: 'iife'
  },
  watch: {
    clearScreen: false
  },
  plugins
}
```

I'd appreciate any pointers towards a possible PR or a different solution.

### PR DESCRIPTION
**Pull request by gkatsev**
Fixes #1804

This is the beginning of a PR to fixes #1804 based on some of the work that people did in that thread with minimal changes. Thanks @evocateur and @JimPanic

I think the changes are good but there's one thing that I'm not sure if there are any side-effects for but would love to get this merged in.

### CODE REVIEW

File: bin/src/run/watch.ts [hunk 1]
```diff
@@ -37,19 +37,20 @@ export default function watch(
...
 	const isTTY = Boolean(process.stderr.isTTY);
 
-	const screen = alternateScreen(isTTY);
-	screen.open();
-
 	const warnings = batchWarnings();
 
+	const initialConfigs = processConfigs(configs);
+
+	const clearScreen = initialConfigs.some(config => config.watch.clearScreen);
```
Comment (gkatsev) [inline bin/src/run/watch.ts]: just realized this iterator isn't quite right.

File: bin/src/run/watch.ts [hunk 2]
```diff
@@ -37,19 +37,20 @@ export default function watch(
...
+
 	let watcher: Watcher;
 	let configWatcher: Watcher;
 
-	function start(configs: RollupWatchOptions[]) {
-		screen.reset(chalk.underline(`rollup v${rollup.VERSION}`));
-
-		let screenWriter = screen.reset;
-		configs = configs.map(options => {
+	function processConfigs(configs: RollupWatchOptions[]): RollupWatchOptions[] {
```
Comment (gkatsev) [inline bin/src/run/watch.ts]: `processConfigs` was previously inside of `start`

File: bin/src/run/watch.ts [hunk 3]
```diff
@@ -71,15 +72,14 @@ export default function watch(
 					code: 'UNKNOWN_OPTION'
 				});
 
-			if (
```
Comment (gkatsev) [inline bin/src/run/watch.ts]: I'm not sure what potential side-effects are for this removal.

**Comment by gkatsev** [comment]
Also, I'm not really sure how to add a test for this, any guidance would be appreciated.

**Comment by gkatsev** [comment]
Hi, what needs to be done to get this merged?
Thanks.

**Comment by lukastaegert** [comment]
Hi @gkatsev, sorry for letting you wait that long. I just had another look through your PR and I must admit I have no idea how to add a test myself without adding some kind of mocking framework.

From the code side I think this looks good. Even though it goes against my convictions I would actually be willing to merge this as it is without a test considering it is also a rather small change. Any objections from @guybedford ?

File: bin/src/run/watch.ts (hunk 3 above)
Comment (gkatsev) [reply bin/src/run/watch.ts]: because `processConfigs` was pulled out of the `start` method, it no longer has access to the  `screenWriter` variable, especially since that also happens later on.
I may be able to store it in some other variable and then reset it to stderr in the start method when it gets called.

Comment (guybedford) [reply bin/src/run/watch.ts]: Ah I see, if you can keep the existing behaviour it may be best not to remove something that seems so intentional, especially given this is untested code.

Comment (gkatsev) [reply bin/src/run/watch.ts]: Makes sense. Let me update the PR then.

**Comment by gkatsev** [comment]
@guybedford updated to keep `screenWriter` set to stderr instead of `screen.reset()` if clearScreen === false.

**Comment by gkatsev** [comment]
@lukastaegert also, no worries, stuff happens and things fall through the cracks.
If this ends up breaking down the line after we merge, feel free to ping me and I'll try and take a look.
