### PR TITLE
fix: RollupLog cause allow unknown

### LINKED ISSUE #4754: `warn` parameter is not compatible with `Error` anymore
### Expected Behavior / Situation

I need to update one of my plugins from Vite 3 to 4 and therefore the underlying Rollup version was migrated to v3

Previously it was possible to pass an error to a Rollup `warn` call.

https://github.com/Shinigami92/vite-plugin-time-reporter/pull/26/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R43

Now this is not the case anymore :slightly_frowning_face: 

### Actual Behavior / Situation

There was a change that changed the `RollupLog['name']` property to `names`

https://github.com/rollup/rollup/blob/e315ffce28fb013d6ce88f9ded581b4abe28d3f0/src/rollup/types.d.ts#L35

https://github.com/rollup/rollup/pull/4579/files#diff-2651238122dc82e0e84b4e3cb1499b8cbd4c01a21a36c9c2fae5812e95cd8ec8L35-R26

This might result in that `RollupLog` is now not anymore _compatible_ with the `Error` interface	

### Modification Proposal

Could we change it back to accept `Error` for `warn` calls?
This could help in that many Vite plugins out there that are just "simple" can just support Vite 2, 3 and 4 without any runtime changes and therefore don't need to introduce a breaking change just for a warn call.

### PR DESCRIPTION
**Pull request by Shinigami92**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

resolves #4754

### CODE REVIEW

File: src/rollup/types.d.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export type RollupWarning = RollupLog;
 
 export interface RollupLog {
 	binding?: string;
-	cause?: Error;
+	cause?: Error | unknown;
```
Comment (lukastaegert) [inline src/rollup/types.d.ts:22]: Just change it to `unknown`. `Error | unknown` is equivalent, just more complicated.

Comment (Shinigami92) [reply src/rollup/types.d.ts:22]: Okay I can do this, but as the tests are failing I need to spin up my dev environment and look into it what needs to be fixed

**Review by lukastaegert — APPROVED** [review]

**Comment by Shinigami92** [comment]
@lukastaegert it works 👍 
I released new version of my plugin that is compatible with Vite 2, 3 and 4
