### PR TITLE
Fix reassignment tracking performance issues

### LINKED ISSUE #2210: LocalVariable.prototype.reassignPath run into a endless loop with rxjs.
LocalVariable.prototype.reassignPath run into a endless loop with rxjs.

- rollup v. 0.59.2
- rxjs v. 6.1.0

that is a insight in my rollup.config.js
```js
const main = {
    input: index.ts,
    output: {
        banner: '',
        file: './dist/index.js',
        dir: './dist/',
        name: 'app',
        format: 'umd',
        sourcemap: true,
        exports: 'none',
        amd: { id: 'app' },
    })),
    context: 'this',
    external: [],
    plugins: [
        nodeResolve( {
                    include: path.join(_pkg.project.workspace, 'node_modules/**'),
                    extensions: ['.json', '.ts', '.html', '.css', '.scss'],
                    modulesOnly: false,
                    modules: true,
                    main: true,
                    jsnext: true,
                    preserveSymlinks: true,
                    customResolveOptions: {
                        preserveSymlinks: true
                    }
                }),
        commonjs({
                    include: path.join(_pkg.project.workspace, 'node_modules/**')
                }),
        typescript2({
                    useTsconfigDeclarationDir: true,
                    cacheRoot: _pkg.project.cache,
                    tsconfigOverride: {
                        compilerOptions: { declaration: _configureation.includes('debug') }
                    }
                }),
        sass(),
        sizes()
    ]
};
```

### LINKED ISSUE #2212: Rollup didn't finish over 30 minutes.
Repro: https://github.com/mysticatea/rollup-issue

I tried to rollup the typescript language service (this will be run in a WebWorker) in [MonacoEditor] library, but it didn't finish in over 30 minutes.

I suspected it might dive into infinite looping because it was using a CPU core heavily with no warnings.

The configuration file is simple:

```js
export default {
    input: require.resolve("monaco-editor/esm/vs/language/typescript/ts.worker.js"),
    output: {
        file: "dist/ts.worker.js",
        format: "iife",
        name: "tsWorker",
    }
}
```

Also, I tried some options:

- `perf: true`, but it didn't affect -- console output is not changed.
- `treeshake: false`, but it didn't affect -- rollup still doesn't finish.

[MonacoEditor]: https://github.com/Microsoft/monaco-editor

### PR DESCRIPTION
**Pull request by lukastaegert**
Resolves #2212
Resolves #2210 (not checked explicitly, please confirm!)

As outlined here: https://github.com/rollup/rollup/issues/2212#issuecomment-391598332, this PR fixes a potential source of performance degradation when there are functions with many return statements by treating them as returning an "unknown" value.

There is also a second change included: Previously, both variable and object path reassignments were tracked in the `LocalVariable` objects. Tracking the latter, however, was rather complicated and did not reflect the real situation where path reassignments are mutations of the original literal. To that end, I moved the path tracking to the actual object expressions. This will help us a lot when we start implementing object path tree-shaking.

### CODE REVIEW

File: src/ast/nodes/shared/FunctionNode.ts [hunk 1]
```diff
@@ -83,12 +74,14 @@ export default class FunctionNode extends NodeBase {
...
 	initialise() {
 		this.included = false;
+		this.isPrototypeReassigned = false;
 		if (this.id !== null) {
 			this.id.declare('function', this);
 		}
 		for (const param of this.params) {
 			param.declare('parameter', null);
 		}
+		this.body.addImplicitReturnExpressionToScope();
```
[the remark this answers is not in the document]
Comment (guybedford) [reply src/ast/nodes/shared/FunctionNode.ts]: It seems here's an example case that is invalided by this change:

```js
function x () {}
function y () {}
function f () {
  if (Math.random() > 0.5)
    return y;
  return x;
}
f()();
```

that would otherwise be tree-shaken.

It doesn't seem a huge loss to me though as it is really hypothetical.

I wonder though if we could not treat the whole function itself as having a "single type" (set from the first return), and only opt-out only if we find that a return value doesn't follow that type rule? That might stop the deep loops while still retaining the basic functionality here? Just a thought.

[the remark this answers is not in the document]
Comment (guybedford) [reply src/ast/nodes/shared/FunctionNode.ts]: I guess you wouldn't know that `x` and `y` are the same without the full deep analysis though... so yeah. But perhaps having a type like `f: PURE_FUNCTION` or `f: STRING_LITERAL` would be useful?

File: src/ast/nodes/ObjectExpression.ts [hunk 2]
```diff
@@ -38,25 +43,29 @@ export default class ObjectExpression extends NodeBase {
...
-					options
-				);
-			}
+		for (const property of properties) {
+			property.forEachReturnExpressionWhenCalledAtPath(
+				path.slice(1),
+				callOptions,
+				callback,
+				options
+			);
```
Comment (guybedford) [inline src/ast/nodes/ObjectExpression.ts]: In theory `hasCertainHit` should have caught this case:

```js
var x = {
	a () {
	},
	[unknown] () {
  }
};
x.a();
```

but it seems it wasn't applying to such a thing anyway so that removing this is fine.

That said, if we extend this type of logic to deal with progressive property sets within reduced control flows like:

```js
var exports = {};

exports.a = function () {
}

exports.a();
```

then we may want to be detecting this again.

File: src/ast/nodes/ObjectExpression.ts [hunk 3]
```diff
@@ -159,29 +202,45 @@ export default class ObjectExpression extends NodeBase {
...
+		const key = path[0];
+		if (
+			path.length === 0 ||
+			this.hasUnknownReassignedProperty ||
+			(typeof key === 'string' && this.reassignedPaths[key])
+		)
+			return true;
+
+		if (path.length === 1 && typeof key === 'string' && objectMembers[key]) {
+			return predicateFunction(options, objectMembers[key].returns);
```
Comment (guybedford) [inline src/ast/nodes/ObjectExpression.ts]: I wasn't able to come up with any test that checks this behaviour. Any ideas? Would be nice to capture as much of this as possible through coverage.

File: src/ast/nodes/BlockStatement.ts [hunk 4]
```diff
@@ -15,7 +15,7 @@ export default class BlockStatement extends StatementBase {
 	type: NodeType.tBlockStatement;
 	body: StatementNode[];
 
-	bindImplicitReturnExpressionToScope() {
+	addImplicitReturnExpressionToScope() {
 		const lastStatement = this.body[this.body.length - 1];
 		if (!lastStatement || lastStatement.type !== NodeType.ReturnStatement) {
 			this.scope.addReturnExpression(UNKNOWN_EXPRESSION);
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/BlockStatement.ts]: There originally was an `UNDEFINED_EXPRESSION` but it turned out to be equivalent to `UNKNOWN_EXPRESSION` so I dropped it. With the new literal value tracking, re-introducing it would actually make sense. Since this is intended to be a bug-fix, I would postpone this for a PR explicitly addressing #2223.

File: src/ast/nodes/ObjectExpression.ts (hunk 2 above)
Comment (lukastaegert) [reply src/ast/nodes/ObjectExpression.ts]: > in theory hasCertainHit should have caught this case

Not 100% sure what you mean by "caught" as I do not see any side-effects to be detected. In general one thing this algorithm tries to capture is that when two properties with the same name appear in a literal, the second overwrites the first. Thus when we access `.a` and an unknown property appears after `a`, both need to be considered while any unknown properties before `a` can be safely ignored. When there are only unknown properties, calling a property is always a side-effect: [REPL](https://rollupjs.org/repl?version=0.59.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMHJlbW92ZWQlNUNudmFyJTIweCUyMCUzRCUyMCU3QiU1Q24lNUN0JTVCdW5rbm93biU1RCUyMCgpJTIwJTdCJTVDbiU1Q3QlNUN0Y29uc29sZS5sb2coMSklNUNuJTIwJTIwJTdEJTJDJTVDbiU1Q3RhJTIwKCklMjAlN0IlN0QlNUNuJTdEJTNCJTVDbnguYSgpJTNCJTVDbiU1Q24lMkYlMkYlMjByZXRhaW5lZCUyMGJlY2F1c2UlMjBvbmUlMjBwb3NzaWJsZSUyMGhpdCUyMHdpdGglMjBzaWRlLWVmZmVjdHMlNUNudmFyJTIweSUyMCUzRCUyMCU3QiU1Q24lNUN0YSUyMCgpJTIwJTdCJTdEJTJDJTVDbiU1Q3QlNUJ1bmtub3duJTVEJTIwKCklMjAlN0IlNUNuJTVDdCU1Q3Rjb25zb2xlLmxvZygxKSU1Q24lMjAlMjAlN0QlMkMlNUNuJTdEJTNCJTVDbnkuYSgpJTNCJTVDbiU1Q24lMkYlMkYlMjByZXRhaW5lZCUyMGJlY2F1c2UlMjBubyUyMGNlcnRhaW4lMjBoaXQlNUNudmFyJTIweiUyMCUzRCUyMCU3QiU1Q24lNUN0JTVCdW5rbm93biU1RCUyMCgpJTIwJTdCJTdEJTVDbiU3RCUzQiU1Q256LmEoKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

> That said, if we extend this type of logic to deal with progressive property sets 

Yes, these cases should certainly still be considered. I think there should already be some tests for this. I have thought a little about how an SSA form could be extended to handle property reassignments. One concept that comes to my mind is considering object expressions to be like "scopes" where the properties are the "variables" that are duplicated:

```javascript
// code
const x = {a: false};
const y = x;
x.a = true;
if (y.a) console.log('properly tracked');

// "SSA form"
// the object expression OE on the right side keeps track of its properties
const x1 = {a1: false};
const y1 = x1;

// we define version 2 of property a; the actual representation will probably be different
// note that this does NOT define a new x2 as x still refers to the same object reference OE
x1.a2 = true;

// as we know that y1 refers to OE, we know we need to use version 2 here
if (y1.a2) console.log('properly tracked');

// tree-shaken result
console.log('properly tracked');
```

You can already see that something like this needs very sophisticated analysis and for the first attempt at SSA I would not include property assignments but focus on actual variable reassignments.

File: src/ast/nodes/ObjectExpression.ts (hunk 3 above)
Comment (lukastaegert) [reply src/ast/nodes/ObjectExpression.ts]: You are very right. I added some tests around these lines and also discovered a bug while doing so...

File: src/ast/nodes/shared/FunctionNode.ts [hunk 5]
```diff
@@ -45,20 +42,14 @@ export default class FunctionNode extends NodeBase {
 		if (path.length <= 1) {
 			return false;
 		}
-		if (path[0] === 'prototype') {
-			return path.length > 2;
-		}
-		return true;
+		return path.length > 2 || path[0] !== 'prototype' || this.isPrototypeReassigned;
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/shared/FunctionNode.ts]: This is about the not-so-deep reassignments. More specifically, this very important situation that is often part of initialization code is not a side-effect:
```javascript
function X(){};
X.prototype.myMethod = function() { console.log('hello'); }
```

while this is:
```javascript
function X(){};
X.doesNotExist.myMethod = function() { console.log('hello'); }
```

Note that if `X` is included for whatever reason, all prototype assignments will be included as well. I think as long as we do not have proper flow tracking, a simple flag to take care of the prototype should be enough to handle situations such as this:
```javascript
function X(){}
X.prototype.myMethod = function() {}

function Y(){}
Y.prototype = X.prototype; // this will mark the prototype of `Y` as reassigned
Y.prototype.myMethod = function() { console.log('hello'); } //  this mutation needs to be retained

const x = new X();
x.myMethod();
```

File: src/ast/nodes/shared/FunctionNode.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/nodes/shared/FunctionNode.ts]: It might be but it would also mean creating a whole new analysis step and another layer of types. I would rather wait for us to have some basic SSA going and use this as a base for much better analysis. Otherwise I would not take action unless there are some situations in important libraries for which this change would provide important gains.

As related to your first comment, rollup also does not yet detect unreachable code after return, break or throw statements. So this would be treated as "unknown" as well:
```javascript
function x() {
  return false;
  const unimportant = false;
}

if (x()) console.log('not removed');
```

File: src/ast/variables/LocalVariable.ts [hunk 6]
```diff
@@ -43,10 +40,10 @@ export default class LocalVariable extends Variable {
 		options: ExecutionPathOptions
 	) {
 		if (
+			!this.isReassigned &&
```
[the remark this answers is not in the document]
Comment (lukastaegert) [reply src/ast/variables/LocalVariable.ts]: Basically the logic has moved to object expression. Which makes much more sense IMO as
* this goes much better with the notion of mutations of object references
* different types react different to mutations. E.g. a number will throw an error when properties are mutated (in strict mode) and itself not be mutated.

**Comment by lukastaegert** [comment]
Thanks for the thorough review, I have added some more tests + fixed some ordering issue in object expression.

File: src/ast/nodes/shared/FunctionNode.ts [hunk 7]
```diff
@@ -100,6 +93,12 @@ export default class FunctionNode extends NodeBase {
 		super.parseNode(esTreeNode);
 	}
 
+	reassignPath(path: ObjectPath) {
+		if (path.length === 1 && path[0] === 'prototype') {
+			this.isPrototypeReassigned = true;
+		}
+	}
```
Comment (guybedford) [inline src/ast/nodes/shared/FunctionNode.ts]: To follow-on the comment about the prototype, ideally would it not be the job of `reassignPath` to track all reassignments to fully distinguish SSA-analyzable paths from non-SSA-analyzable paths?

Further, ideally `reassignPath` should be the same here for both objects and functions surely, apart from some core opt-outs like `length` which would throw on reassignment?

File: src/ast/nodes/shared/FunctionNode.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (guybedford) [reply src/ast/nodes/shared/FunctionNode.ts]: Thanks for the clear explanation that makes complete sense. To continue to help aid my understanding I added a further question about more generic path reassignment checking below, which seems like it is related here.

File: src/ast/nodes/shared/FunctionNode.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (guybedford) [reply src/ast/nodes/shared/FunctionNode.ts]: Sure, as I say these certainly seem suitable compromises to me.

File: src/ast/nodes/ObjectExpression.ts (hunk 2 above)
Comment (guybedford) [reply src/ast/nodes/ObjectExpression.ts]: In theory, `unknown` could be equal to `'a'`, which would then take precedence meaning it is not a certain hit even though there is an explicit `'a'` defined. certainHit logic has precedence logic in it (loop in reverse order), yet doesn't quite go all the way in taking these concepts to their complete conclusions.

We lose the ability to go back on this here, but yes it's a super edge case. I'm mentioning because we are so close to handling the edge case, and now moving away from it. Projects that get massive traction need to be watertight - that is a big difference between a useful software project, and a massively supported and used project.

Comment (guybedford) [reply src/ast/nodes/ObjectExpression.ts]: Very interesting object interpretation of SSA.

Somewhat unrelated, but I've long wanted to have the available analysis to form the following optimization:

```js
var x = 'asdf';
var z = 'g';

export function y () {
  console.log(z);
}

export function p() {
  console.log(x);
}
```

If one module uses just `y` and another module uses just `p`, we don't need to keep the definitions of y and p in the same chunk necessarily and can actually split the above module into two separate modules:

```js
var x = 'asdf';
export function p() {
  console.log(x);
}
```

```js
var z = 'g';
export function y () {
  console.log(z);
}
```

This is a super complex long-term code splitting optimization I've wanted to implement for a while, and likely won't be able to implement for a while - but mentioning here as it would usefully piggy-back off similar analysis.

File: src/ast/nodes/shared/FunctionNode.ts (hunk 7 above)
Comment (lukastaegert) [reply src/ast/nodes/shared/FunctionNode.ts]: Yes and no. At the moment, all paths of a function except the `prototype` are treated as "unknown". So tracking reassignments here would just mean an "unknown" gets replaced by another "unknown" so there is no use doing more analysis.

I thought about adding more logic here but I think it only makes sense if there are at least a few more `function` properties that are known to rollup. Until then, a single flag for the prototype seemed like enough logic.

File: src/ast/nodes/ObjectExpression.ts (hunk 2 above)
Comment (lukastaegert) [reply src/ast/nodes/ObjectExpression.ts]: > In theory, unknown could be equal to 'a', which would then take precedence meaning it is not a certain hit even though there is an explicit 'a' defined. certainHit logic has precedence logic in it (loop in reverse order), yet doesn't quite go all the way in taking these concepts to their complete conclusions

Actually as far as I know, it does go all the way 😜 Let me elaborate:
`hasCertainHit` means "we are certain there is a property of the given name". It does *not* mean we are certain which one it is! And in fact it is only used in the negative: When we are *not* certain there is a property of the given name, calling it must always be a side-effect.

If we *are* certain on the other hand, we check a whole array of properties for side-effects. Cf. this example: [REPL](https://rollupjs.org/repl?version=0.59.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIweCUyMCUzRCUyMCU3QiU1Q24lNUN0YSgpJTIwJTdCJTVDbiU1Q3QlMjAlMjB0cmlnZ2VyZWQlMjAlM0QlMjB0cnVlJTIwJTJGJTJGJTIwdGhpcyUyMHNpZGUtZWZmZWN0JTIwaXMlMjBjb21wbGV0ZWx5JTIwaWdub3JlZCU1Q24lNUN0JTdEJTJDJTVDbiU1Q3RhKCklMjAlN0IlN0QlMkMlNUNuJTVDdCU1QnVua25vd24lNUQoKSUyMCU3QiU1Q24lNUN0JTVDdHRyaWdnZXJlZCUyMCUzRCUyMHRydWUlM0IlMjAlMkYlMkYlMjB0cnklMjByZW1vdmluZyUyMHRoaXMlMjBzaWRlLWVmZmVjdCElNUNuJTVDdCU3RCU1Q24lN0QlM0IlNUNuJTVDbmxldCUyMHRyaWdnZXJlZCUyMCUzRCUyMGZhbHNlJTNCJTVDbnguYSgpJTNCJTVDbmFzc2VydC5vayh0cmlnZ2VyZWQpJTNCJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

Here we do have a certain hit; the algorithm, however, does not only check the last method 
 with name `"a"` for side-effects but also all computed properties after it.

I have added this example + some variations as a function test to make sure this works even after the update and keeps working in the future.

> Somewhat unrelated, but I've long wanted to have the available analysis to form the following optimization

Doing this in an arbitrary way might be difficult if the right hand side of the declaration itself depends on other variables. Something simpler that might be able to solve this problem in some situations and that I would consider quite doable would be inlining variables that are only used in one place (if they are used in more places, you would loose the reference identity). If done right i.e. in a way that "a variable can be inlined if it is only used once or only depends on other variables that can be inlined", then  this would inline .e.g `z` into `y` and move both into the chunk where they are used

Comment (guybedford) [reply src/ast/nodes/ObjectExpression.ts]: What I mean by being inconsistent is that the example is tree-shaken - https://rollupjs.org/repl?version=0.59.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjAlN0IlNUNuJTVDdGElMjAoKSUyMCU3QiU1Q24lNUN0JTdEJTJDJTVDbiU1Q3QlNUJ1bmtub3duJTVEJTIwKCklMjAlN0IlNUNuJTIwJTIwJTdEJTVDbiU3RCUzQiU1Q254LmEoKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA== when in theory it shouldn't necessarily be.

> Doing this in an arbitrary way might be difficult if the right hand side of the declaration itself depends on other variables. Something simpler that might be able to solve this problem in some situations and that I would consider quite doable would be inlining variables that are only used in one place (if they are used in more places, you would loose the reference identity). If done right i.e. in a way that "a variable can be inlined if it is only used once or only depends on other variables that can be inlined", then this would inline .e.g z into y and move both into the chunk where they are used

I feel quite strongly on this one that "gathering related branches" is an important part of the module splitting process.

Comment (lukastaegert) [reply src/ast/nodes/ObjectExpression.ts]: > when in theory it shouldn't necessarily be

In which theory? Add a side-effect and it will not be removed. Do you want the algorithm to be dumber in this place? Why?
