### PR TITLE
Return UnknownValue if getLiteralValueAtPath is called recursively within logical expressions

### LINKED ISSUE #5815: Typescript enum: TypeError: Cannot set properties of undefined
### Rollup Version

4.29.0

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://stackblitz.com/edit/vitejs-vite-p16j6dke?file=package.json

### Expected Behaviour

Rendered output should be: "MyEnum.foo: FOO" and no errors in console.

### Actual Behaviour

Outputs an empty page and web-console throws this error:
`Uncaught TypeError: Cannot set properties of undefined (setting 'foo')`

I know this might not be a direct bug of rollup, since it's only installed here as a dependency of vite.
When running "npm start" with rollup v4.29.0 we get the error as setup in the example.
But when changing the overrides to rollup "v4.28.1" everything is fine. (need to re-run "npm start" manually in stackblitz)

Running "npm run dev" is also fine, regardless of the rollup version.
So it is only happening if we build the project while also instrumenting the code using istanbul.
However, it was already determined that [vite-plugin-istanbul](https://github.com/iFaxity/vite-plugin-istanbul) is not responsible here.

Any ideas?

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
resolves #5815

### CODE REVIEW

File: src/ast/nodes/LogicalExpression.ts [hunk 1]
```diff
@@ -103,6 +103,7 @@ export default class LogicalExpression extends NodeBase implements Deoptimizable
 		recursionTracker: PathTracker,
 		origin: DeoptimizableEntity
 	): LiteralValueOrUnknown {
+		if (origin === this) return UnknownValue;
```
Comment (lukastaegert) [inline src/ast/nodes/LogicalExpression.ts:106]: Actually a good idea. Alternatively, one could have used the recursionTracker, but this is of course also correct. Makes me wonder, though, if there are more situations where this could happen. But considering the bug at hand, this looks good to me.

File: test/function/samples/logical-expressions-literal-value/main.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+var MyEnum =
+	(unknownGlobal,
+	(MyEnum2 => {
+		MyEnum2['foo'] = 'FOO';
+		MyEnum2['bar'] = 'BAR';
+		return MyEnum2;
+	})(MyEnum || {}));
```
Comment (lukastaegert) [inline test/function/samples/logical-expressions-literal-value/main.js:7]: How about adding an assertion at the end

```ts
assert.strictEqual(MyEnum.foo, 'FOO');
```

Then we definitely have the property access, and this does not change anything about the original bug.

File: src/ast/nodes/LogicalExpression.ts (hunk 1 above)
Comment (TrickyPi) [reply src/ast/nodes/LogicalExpression.ts:106]: > Makes me wonder, though, if there are more situations where this could happen, i.e. where handling "getLiteralValue" might profit from an `origin` check.

Yeah, but it might be hard to find those situations without issue reports.

**Review by lukastaegert — APPROVED** [review]
