### PR TITLE
fix: introduce UnknownFalsyValue for enhancing if statement tree-shaking

### LINKED ISSUE #5744: Order of logical `typeof` operands breaks tree-shaking
### Rollup Version

4.27.4

### Operating System (or Browser)

Safari

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://rollupjs.org/repl/?version=4.27.4&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmlmJTIwKHR5cGVvZiUyMHBhcnNlSW50JTIwJTNEJTNEJTNEJTIwJTVDJTIyZnVuY3Rpb24lNUMlMjIlMjAlMjYlMjYlMjAlNUMlMjJhJTVDJTIyJTIwJTNEJTNEJTNEJTIwJTVDJTIyYiU1QyUyMiklMjAlN0IlNUNuJTIwJTIwY29uc29sZS5sb2coJTVDJTIydHlwZW9mJTIwZmlyc3QlNUMlMjIpJTNCJTVDbiU3RCU1Q24lNUNuaWYlMjAoJTVDJTIyYSU1QyUyMiUyMCUzRCUzRCUzRCUyMCU1QyUyMmIlNUMlMjIlMjAlMjYlMjYlMjB0eXBlb2YlMjBwYXJzZUludCUyMCUzRCUzRCUzRCUyMCU1QyUyMmZ1bmN0aW9uJTVDJTIyKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyglNUMlMjJ0eXBlb2YlMjBzZWNvbmQlNUMlMjIpJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0ElMjJzbWFsbGVzdCUyMiU3RCU3RA==

### Expected Behaviour

For test input:

```js
if (typeof parseInt === "function" && "a" === "b") {
  console.log("typeof first");
}

if ("a" === "b" && typeof parseInt === "function") {
  console.log("typeof second");
}
```

All of this should be removed. This may be related to #3117, but IIUC, then `typeof parseInt` shouldn't be considered a side-affect.

### Actual Behaviour

Only the second `if` is removed.

```js
if (typeof parseInt === "function" && "a" === "b") {
  console.log("typeof first");
}
```

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
resolves #5744

### CODE REVIEW

File: src/ast/nodes/IfStatement.ts [hunk 1]
```diff
@@ -124,11 +124,12 @@ export default class IfStatement extends StatementBase implements DeoptimizableE
...
-				EMPTY_PATH,
-				SHARED_RECURSION_TRACKER,
-				this
-			));
+			const testValue = this.test.getLiteralValueAtPath(EMPTY_PATH, SHARED_RECURSION_TRACKER, this);
+			if (testValue === UnknownFalsyValue) {
+				this.testValue = false;
+			} else {
+				this.testValue = testValue;
+			}
```
Comment (lukastaegert) [inline src/ast/nodes/IfStatement.ts:132]: Nice idea. Why not take it to the next level by writing a general helper method `tryCastLiteralValueToBoolean` that maps `UnknownFalsyValue` to `false`, but also `UnknownTruthyValue` to `true` and other symbol values to `UnknownValue`? And then we use the method in three places:

1. here
```suggestion
  		const testValue = tryCastLiteralValueToBoolean(getLiteralValueAtPath(EMPTY_PATH, SHARED_RECURSION_TRACKER, this));
```
2. In ConditionalExpression
3. In LogicalExpression

This will also ensure that objects are "truthy". And having a central helper for all places where we test a literal value for its boolean value ensures that the logic can be easily improved in a central place.

File: test/function/samples/tree-shaking-within-if-statement/_config.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+module.exports = defineTest({
```
Comment (lukastaegert) [inline test/function/samples/tree-shaking-within-if-statement/_config.js:1]: This should probably be a form test so that we can actually see what is removed?

File: src/ast/nodes/IfStatement.ts (hunk 1 above)
Comment (TrickyPi) [reply src/ast/nodes/IfStatement.ts:132]: Hahaha, I was actually planning to update `ConditionalExpression` and `LogicalExpression ` in a follow-up PR.

Yeah, introducing `tryCastLiteralValueToBoolean` method is definitely better, especially since `ConditionalExpression` and `LogicalExpression` will also use this method.

I'll make the updates as soon as possible.

File: test/function/samples/tree-shaking-within-if-statement/_config.js (hunk 2 above)
Comment (TrickyPi) [reply test/function/samples/tree-shaking-within-if-statement/_config.js:1]: That makes sense!

File: src/ast/nodes/shared/knownGlobals.ts [hunk 3]
```diff
@@ -35,33 +35,33 @@ interface GlobalDescription {
 	__proto__: null;
 }
 
-const getTruthyLiteralValue = (): LiteralValueOrUnknown => UnknownTruthyValue;
+const getUnknownValue = (): LiteralValueOrUnknown => UnknownValue;
```
Comment (TrickyPi) [inline src/ast/nodes/shared/knownGlobals.ts:38]: Now, we consider that `UnknownTruthyValue` is true in logical evaluation. To ensure some polyfill JS scripts work properly, we need to change `UnknownTruthyValue` to `UnknownValue`. Perhaps we can return `UnknownTruthyValue` if the `treeshake` option is `'smallest'`?

Comment (lukastaegert) [reply src/ast/nodes/shared/knownGlobals.ts:38]: That is probably true. But as before the PR, it did not have an effect, it would not affect anyone if we changed that. I am not sure we can easily read the tree shaking option here, your solution is perfect for now IMO.

**Review by lukastaegert — APPROVED** [review]
Looks good from my side, let me know when you are ready to merge.

**Comment by TrickyPi** [comment]
No more changes from me. Feel free to merge!
