### PR TITLE
Avoid invalid code when "else" branch is simplified

### LINKED ISSUE #3419: Else without braces and spaces gets concatenated to function names
- Rollup Version: 1.32.0 (also for 1.10.1, didn't try others)
- Operating System (or Browser): Windows (WSL: Ubuntu), Chrome
- Node Version (if applicable): 13.5.0
- Link to reproduction (IMPORTANT, read below): https://rollupjs.org/repl/?version=1.32.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwc29tZXRoaW5nJTIwJTNEJTIwKCklMjAlM0QlM0UlMjBjb25zb2xlLmxvZyglNUMlMjJ0aGluZyU1QyUyMiklMjAlMkYlMkYlMjBzaWRlJTIwZWZmZWN0JTIwdG8lMjBrZWVwJTIwdGhlJTIwbWV0aG9kJTIwbmFtZSU1Q24lNUNuaWYlMjAobWF0aC5yYW5kKDAlMkMlMjAxKSUyMCUzRCUzRCUzRCUyMDAuNSklMjAlN0IlMjAlMkYlMkYlMjBub25zZW5zaWNhbCUyMHRvJTIwc2ltcGx5JTIwa2VlcCUyMHRoZSUyMGlmJTJGZWxzZSU1Q24lN0QlMjBlbHNlJTVDJTIycHJvZHVjdGlvbiU1QyUyMiElM0QlM0QlNUMlMjJsb2NhbCU1QyUyMiUzRnNvbWV0aGluZygpJTNBdm9pZCUyMDAlM0IlMjAlMkYlMkYlMjBub3RpY2UlMjB0aGUlMjAlNUMlMjJlbHNlc29tZXRoaW5nJTVDJTIyJTIwcmVzdWx0JTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior
`else` and following function name should be separated by a space.

### Actual Behavior
`else` is combined with the function name.

### Context
This is found in the npm `history` module in file `history.js` of the v5 beta (in the installed module; I can't find it on GitHub). As such, I cannot modify it on my own. The file looks to have been previously minimized, and is valid until Rollup is run on it in my project.

The code as it appears is as follows (edited for brevity):
```js
if(null!=e){/* ... */}else"production"!==process.env.NODE_ENV?x(!1,"You are trying to block a POP navigation ..."):void 0;else u("POP")
```

My config uses `@rollup/plugin-replace` to replace `process.env.NODE_ENV` with, in this case, a non-`"production"` string, which then results in the following code after Rollup completes:

```js
if(null!=e){/* ... */}elsex$2(!1,"You are trying to block a POP navigation ...");else u("POP");
```

The resulting error is `Uncaught SyntaxError: Unexpected token 'else'`, which is pointing to the `else u("POP");` part of the code, since the previous `else` was converted to `elsex$2`.

### PR DESCRIPTION
**Pull request by lukastaegert**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:
Resolves #3419

### Description
This ensures that in a situation such as #3419, there is always whitespace or a similar separator between the "else" keyword and the following branch so that the expression can be transformed freely. This is a similar fix as was previously implemented for for..in and for..of statements.

### CODE REVIEW

File: src/ast/nodes/IfStatement.ts [hunk 1]
```diff
@@ -82,6 +82,9 @@ export default class IfStatement extends StatementBase implements DeoptimizableE
 			}
 			if (this.alternate !== null) {
 				if (this.alternate.included) {
+					if (code.original.charCodeAt(this.alternate.start - 1) === 101 /* f */) {
```
Comment (kzc) [inline src/ast/nodes/IfStatement.ts]: I'm always up for a good puzzle... What's the significance of `f`? Or is it `e`?
```
$ node -p 'String.fromCharCode(101)'
e
$ node -p 'String.fromCharCode(102)'
f
```

Comment (lukastaegert) [reply src/ast/nodes/IfStatement.ts]: The beauty of comments. I definitely did NOT copy this code from for..of loop 😉
