### PR TITLE
Refine reexport test cases

### LINKED ISSUE #1951: Named Imports Incorrectly removed if import * is also used
If I `import * as whatever from 'foo'` and reference `foo` itself, rather than `foo.bar`, any named imports from 'foo' are removed but do not get transformed to use the whatever variable. 

```js
import * as foo from 'foo';
import {blah, bar} from 'foo'; //removed in the final build without changing the console.logs below

console.log(foo)
console.log(blah);
console.log(bar);

```

[Here is the reproduction on the REPL](https://rollupjs.org/repl?version=0.55.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZvbyUyMGZyb20lMjAnZm9vJyUzQiU1Q25pbXBvcnQlMjAlN0JibGFoJTJDJTIwYmFyJTdEJTIwZnJvbSUyMCdmb28nJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhmb28pJTVDbmNvbnNvbGUubG9nKGJsYWgpJTNCJTVDbmNvbnNvbGUubG9nKGJhciklM0IlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

### PR DESCRIPTION
**Pull request by guybedford**
This refines some more cases around reexport boundaries, specifically supporting #1675 case of reexporting an imported external namespace, and also further cases around tracing `import { x } export { x }` scenarios identically to other re-exports in the boundaries.

It feels like we're finally getting close to complete on these scenarios, although there may still be a few surprises to discover.

Edit: Also fixed #1951

### CODE REVIEW

File: src/finalisers/shared/getExportBlock.ts [hunk 1]
```diff
@@ -37,18 +37,29 @@ export default function getExportBlock (
...
-				if (specifier.imported === '*') {
+				if (specifier.reexported === '*') {
 					exportBlock += `${exportBlock ? '\n' : ''}Object.keys(${name}).forEach(function (key) { exports[key] = ${name}[key]; });`;
 				}
 			});
 		}
 	});
 
-	dependencies.forEach(({ name, reexports }) => {
+	dependencies.forEach(({ name, imports, reexports }) => {
```
Comment (lukastaegert) [inline src/finalisers/shared/getExportBlock.ts]: I know these two loops have previously been separate but it seems they can easily be combined into one loop which will remove one iteration + remove one if statement + make sure in a hard-coded way no reexport is handled twice.

File: src/finalisers/es.ts [hunk 2]
```diff
@@ -35,16 +35,27 @@ export default function es (chunk: Chunk, magicString: MagicStringBundle, { getP
 			}
 		}
 		if (reexports) {
+			if (imports)
+				output += '\n';
 			const starExport = reexports.find(specifier => specifier.reexported === '*');
+			const nsReexport = reexports.find(specifier => specifier.imported === '*' && specifier.reexported !== '*');
```
Comment (lukastaegert) [inline src/finalisers/es.ts]: I would love a longer name here, e.g. `nonStarReexport` as with the shortened name, you have no chance of knowing what it means further down without reading the declaration.

File: test/form/samples/export-default-import/_expected/es.js [hunk 3]
```diff
@@ -1,5 +1,2 @@
 import x from 'x';
```
[the remark this answers is not in the document]
Comment (guybedford) [reply test/form/samples/export-default-import/_expected/es.js]: Yes exactly, if we could track per-chunk usage then this can change, but until then the import statements are never pruned. These statements are well-merged though so it typically doesn't result in any bloat.

File: src/finalisers/shared/getExportBlock.ts (hunk 1 above)
Comment (guybedford) [reply src/finalisers/shared/getExportBlock.ts]: The reason for this separation is to ensure that the star exports come first in the output, which is important to the export ordering as star exports get overridden by reexports get overridden by exact name exports.

Comment (lukastaegert) [reply src/finalisers/shared/getExportBlock.ts]: Ah, I see, thanks.

File: src/Chunk.ts [hunk 4]
```diff
@@ -245,26 +245,7 @@ export default class Chunk {
...
-				if (tracedExport.name === '*') {
-					Object.keys((<NamespaceVariable>variable).originals || (<ExternalVariable>variable).module.declarations).forEach(importName => {
-						const original = ((<NamespaceVariable>variable).originals || (<ExternalVariable>variable).module.declarations)[importName];
-						this.populateImport(original, tracedExport);
-					});
-					return;
-				}
-
-				this.populateImport(variable, tracedExport);
+				this.traceImport(declaration.module, declaration.name);
```
Comment (lukastaegert) [inline src/Chunk.ts]: Ah, I totally overlooked this one. So extraction actually removed a code duplication 👍

Comment (guybedford) [reply src/Chunk.ts]: Yup!
