### PR TITLE
fix: mark some known globals or their functions as impure

### LINKED ISSUE #4282: Rollup deletes code with side effects due to incorrect pure annotations
### Rollup Version

2.60.1

### Operating System (or Browser)

Chrome 96

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://rollupjs.org/repl/?version=2.60.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIweCUyMCUzRCUyMG5ldyUyME1hcCglN0IlNUNuJTIwJTIwJTVCU3ltYm9sLml0ZXJhdG9yJTVEKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG5leHQoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygnc2lkZSUyMGVmZmVjdCcpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU3QiUyMGRvbmUlM0ElMjB0cnVlJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTVDbiU3RCklNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

### Expected Behaviour

Here's the input code from the link above:

```js
const x = new Map({
  [Symbol.iterator]() {
    return {
      next() {
        console.log('side effect')
        return { done: true }
      }
    }
  }
})
```

The code generated by Rollup should print `side effect`.

### Actual Behaviour

The code generated by Rollup is incorrectly empty, and so prints nothing.

The context for this is that someone wanted esbuild to do what Rollup does here: https://github.com/evanw/esbuild/issues/1791. However, what Rollup does here seems to be incorrect, so I reported a bug here instead. I don't need this to be fixed myself so feel free to do what you want with this bug report.

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

resolves #4282

### Description
Currently I mark Map is impure as a temporary resolution. I noticed that there are some issues related to the tree-shaking to the `iterator`, this #4282 issue is also similar.

### CODE REVIEW

**Comment by TrickyPi** [comment]
After implementing #3127, we can further improve the tree-shaking of Map.

File: test/function/samples/tree-shake-map-constructor/main.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+assert.ok(
```
Comment (lukastaegert) [inline test/function/samples/tree-shake-map-constructor/main.js:1]: This test was already working in current Rollup: 
https://rollupjs.org/repl/?version=3.20.7&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmFzc2VydC5vayglNUNuJTVDdG5ldyUyME1hcCglN0IlNUNuJTVDdCU1Q3QlNUJTeW1ib2wuaXRlcmF0b3IlNUQoKSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3RyZXR1cm4lMjAlN0IlNUNuJTVDdCU1Q3QlNUN0JTVDdG5leHQoKSUyMCU3QiU1Q24lNUN0JTVDdCU1Q3QlNUN0JTVDdGNvbnNvbGUubG9nKCdzaWRlJTIwZWZmZWN0JyklM0IlNUNuJTVDdCU1Q3QlNUN0JTVDdCU1Q3RyZXR1cm4lMjAlN0IlMjBkb25lJTNBJTIwdHJ1ZSUyMCU3RCUzQiU1Q24lNUN0JTVDdCU1Q3QlNUN0JTdEJTVDbiU1Q3QlNUN0JTVDdCU3RCUzQiU1Q24lNUN0JTVDdCU3RCU1Q24lNUN0JTdEKSU1Q24pJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCU3RCU3RA==

Also, you should not `console.log` in a `function` test as it produces unwanted output on the console when the tests are executed.
This would be a slightly modified version that your change should fix:
https://rollupjs.org/repl/?version=3.20.7&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmxldCUyMGVmZmVjdCUyMCUzRCUyMGZhbHNlJTNCJTVDbiU1Q25uZXclMjBNYXAoJTdCJTVDbiU1Q3QlNUJTeW1ib2wuaXRlcmF0b3IlNUQoKSUyMCU3QiU1Q24lNUN0JTVDdHJldHVybiUyMCU3QiU1Q24lNUN0JTVDdCU1Q3RuZXh0KCklMjAlN0IlNUNuJTVDdCU1Q3QlNUN0JTVDdGVmZmVjdCUyMCUzRCUyMHRydWUlM0IlNUNuJTVDdCU1Q3QlNUN0JTVDdHJldHVybiUyMCU3QiUyMGRvbmUlM0ElMjB0cnVlJTIwJTdEJTNCJTVDbiU1Q3QlNUN0JTVDdCU3RCU1Q24lNUN0JTVDdCU3RCUzQiU1Q24lNUN0JTdEJTVDbiU3RCklM0IlNUNuJTVDbmFzc2VydC5vayhlZmZlY3QpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCU3RCU3RA==

**Review by lukastaegert — COMMENTED** [review]
Looks good to me, but the test case should be modified so that it breaks with current Rollup.

File: test/function/samples/tree-shake-map-constructor/main.js (hunk 1 above)
Comment (TrickyPi) [reply test/function/samples/tree-shake-map-constructor/main.js]: Thanks for your review! I corrected this test.

**Comment by dnalborczyk** [comment]
wouldn't this apply to `Set`, `WeakMap`, `WeakSet` and other static methods consuming `Iterables` such as `Object.fromEntries` as well?

**Comment by TrickyPi** [comment]
Thanks for your review! we should apply this to what you mentioned, I marked more known globals or their methods as impure.

File: test/function/samples/tree-shake-iterable/main.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+			}
+		};
+	}
+};
+
+new Map(iterable);
+new Set(iterable);
+new WeakMap(iterable);
+new WeakSet(iterable);
+Float32Array.from(iterable);
```
Comment (dnalborczyk) [inline test/function/samples/tree-shake-iterable/main.js:18]:
```suggestion
Array.from(iterable);
```

File: test/function/samples/tree-shake-iterable/main.js [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+Float64Array.from(iterable);
+Int16Array.from(iterable);
+Int32Array.from(iterable);
+Int8Array.from(iterable);
+Uint16Array.from(iterable);
+Uint32Array.from(iterable);
+Uint8Array.from(iterable);
+Uint8ClampedArray.from(iterable);
```
Comment (dnalborczyk) [inline test/function/samples/tree-shake-iterable/main.js:26]: we could add `Array.from`, `BigInt64Array.from`, `BigUint64Array.from` as well.

Comment (TrickyPi) [reply test/function/samples/tree-shake-iterable/main.js:29]: Oh, I didn't take this into account. I have changed it now.

**Review by lukastaegert — APPROVED** [review]
Thanks a lot!
