### PR TITLE
fix(native-loader): safely handle report.getReport() on Termux/Android

### LINKED ISSUE #6119: Latest update broke Bun
### Rollup Version

v4.52.0

### Operating System (or Browser)

Windows 11

### Node Version (if applicable)

_No response_

### Link To Reproduction

Not needed

### Expected Behaviour

Would expect rollup to not throw any errors

### Actual Behaviour

When starting development, rollup\dist\native.js throws a TypeError: undefined is not an object (evaluating 'report.getReport().header.osName')

This is because process.report.getReport is not implemented on Bun / Windows: https://github.com/oven-sh/bun/issues/11992

An easy fix would be to change the line from

> base: report.getReport().header.osName.startsWith('MINGW32_NT')

to

> base: report.getReport().header?.osName.startsWith('MINGW32_NT')

### PR DESCRIPTION
**Pull request by Jobians**
On Termux/Android, `report.getReport()` crashes because CPU information is not available in the environment, causing the native Rollup loader to throw `Failed to get cpu info`.

This change wraps calls to `report.getReport()` in try/catch:

- `isMusl()` now returns `false` if report information is unavailable, allowing Rollup to continue loading native bindings.
- Windows MINGW detection (`isMingw32()`) is also safely wrapped.

These changes are non-breaking and maintain existing behavior on supported platforms. They ensure Rollup can run on Termux/Android without crashing while preserving all existing bindings and error handling.

No other logic is modified; this strictly improves environment robustness.

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

List any relevant issue numbers:

### Description

- resolves #6119

### CODE REVIEW

File: native.js [hunk 1]
```diff
@@ -2,7 +2,21 @@ const { existsSync } = require('node:fs');
 const path = require('node:path');
 const { platform, arch, report } = require('node:process');
 
-const isMusl = () => !report.getReport().header.glibcVersionRuntime;
+const isMusl = () => {
+  try {
+    return !report.getReport().header.glibcVersionRuntime;
+  } catch (_e) {
```
Comment (lukastaegert) [inline native.js]: JavaScript does indeed support catch without argument [since Node 10](https://node.green/#ES2019-misc-optional-catch-binding)


```suggestion
  } catch {
```

File: native.js [hunk 2]
```diff
@@ -2,7 +2,21 @@ const { existsSync } = require('node:fs');
...
+    return false;
+  }
+};
+
+const isMingw32 = () => {
+  try {
+    return report.getReport().header.osName.startsWith('MINGW32_NT');
+  } catch (_e) {
```
Comment (lukastaegert) [inline native.js]:
```suggestion
  } catch {
```

**Review by lukastaegert — COMMENTED** [review]
Thanks! Just minor comments, but this sounds like a good improvement.

**Review by lukastaegert — APPROVED** [review]
