### PR TITLE
Reapply object tree-shaking

### LINKED ISSUE #5734: Failed to build using version 4.27.0.
### Rollup Version

4.27.2

### Operating System (or Browser)

window/linux

### Node Version (if applicable)

v18

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-mgajrx?file=package.json

### Expected Behaviour

I use vite to build js code,  it's can't work.  i found the vite dependece rollup,  when i use rollup@4.26.0 can build success. but can't work on rollup@4.27.0.  Maybe there is some issue when import js worker.  

### Actual Behaviour

image

### LINKED ISSUE #5735: Object tree shaking removes properties that are being used
### Rollup Version

4.27.2

### Operating System (or Browser)

MacOS 14.3

### Node Version (if applicable)

21.6.0

### Link To Reproduction

https://rollupjs.org/repl/?version=4.27.2&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBnZXRCdWlsZGVyJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjB2YXJpYW50U2hhcGVJZCUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBlcnJvcnMlM0ElMjAxbiUyQyU1Q24lMjAlMjAlMjAlMjBldmVudHMlM0ElMjAybiUyQyU1Q24lMjAlMjAlMjAlMjBjYWxscyUzQSUyMDNuJTJDJTVDbiUyMCUyMCU3RCUzQiU1Q24lNUNuJTIwJTIwY29uc3QlMjBidWlsZFZhcmlhbnQlMjAlM0QlMjAodmFyaWFudFR5cGUpJTIwJTNEJTNFJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwdHJ5JTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHZhcmlhbnRTaGFwZUlkJTVCdmFyaWFudFR5cGUlNUQlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTIwY2F0Y2glMjAoXyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwbnVsbCUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTNCJTVDbiU1Q24lMjAlMjByZXR1cm4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwYnVpbGRDYWxsJTNBJTIwYnVpbGRWYXJpYW50KCU1QyUyMmNhbGxzJTVDJTIyKSUyQyU1Q24lMjAlMjAlMjAlMjBidWlsZEV2ZW50JTNBJTIwYnVpbGRWYXJpYW50KCU1QyUyMmV2ZW50cyU1QyUyMiklMkMlNUNuJTIwJTIwJTIwJTIwYnVpbGRFcnJvciUzQSUyMGJ1aWxkVmFyaWFudCglNUMlMjJlcnJvcnMlNUMlMjIpJTJDJTVDbiUyMCUyMCU3RCUzQiU1Q24lN0QlM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=

```js
export const getBuilder = () => {
  const variantShapeId = {
    errors: 1n,
    events: 2n,
    calls: 3n,
  };

  const buildVariant = (variantType) => () => {
    try {
      return variantShapeId[variantType];
    } catch (_) {
      return null;
    }
  };

  return {
    buildCall: buildVariant("calls"),
    buildEvent: buildVariant("events"),
    buildError: buildVariant("errors"),
  };
};
```

### Expected Behaviour

The object `variantShapeId` should be left as-is, since it's being indexed by an external parameter.

### Actual Behaviour

The object tree-shaking removes properties from `variantShapeId` that should be accessible.

In this specific example, this only happens when wrapping the statement that accesses the object with a try-catch.

### Additional context

This is a regression introduced in 4.27, related to #5420 

The example is the minimum reproduction case based on [existing code of our library](https://github.com/polkadot-api/polkadot-api/blob/5888a34218a6f117f25318791a7b288a508dc392/packages/metadata-builders/src/checksum-builder.ts#L446).

CC @carlosala @lukastaegert @TrickyPi

### LINKED ISSUE #5739: Object Tree Shaking: Incorrect handling of variadic arguments
### Rollup Version

4.27.2

### Operating System (or Browser)

Linux on WSL2

### Node Version (if applicable)

_No response_

### Link To Reproduction

https://rollupjs.org/repl/?version=4.27.2&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZ2V0QXJnc0luZm8lMjAlM0QlMjAoLi4uYXJncyklMjAlM0QlM0UlMjAlN0IlNUNuJTVDdGlmJTIwKGFyZ3MubGVuZ3RoJTIwJTNEJTNEJTNEJTIwMCklMjAlN0IlNUNuJTVDdCU1Q3RyZXR1cm4lMjAnbm8lMjBhcmdzJyU1Q24lNUN0JTdEJTVDbiU1Q3RyZXR1cm4lMjAnaGFzJTIwYXJncyclNUNuJTdEJTVDbiU1Q25jb25zdCUyMGNhbGwxJTIwJTNEJTIwZ2V0QXJnc0luZm8oKSU1Q25jb25zdCUyMGNhbGwyJTIwJTNEJTIwZ2V0QXJnc0luZm8oMSklNUNuJTVDbmNvbnNvbGUubG9nKGNhbGwxJTJDJTIwY2FsbDIpJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE

### Expected Behaviour

Rollup should not remove IF-block body

### Actual Behaviour

- If the first call to getArgsInfo has no arguments, Rollup incorrectly removes the return 'no args'; statement in the if block.
- The issue disappears if the order of calls is reversed (i.e., the first call has arguments).

I am aware that object tree-shaking was reverted in Rollup 4.27.3, but this issue should be addressed before it is reintroduced in PR #5737.

### PR DESCRIPTION
**Pull request by lukastaegert**
This reverts commit 10bc15096ffe3c155fe5e81f1e474f208adbc667.

This PR contains:

- [ ] bugfix
- [x] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
- resolves #5735 
- resolves #5739
- resolves #5734

### Description
This re-applies #5420 when we have fixes for #5733, #5734, #5735, https://github.com/rollup/rollup/issues/5480#issuecomment-2482179159 and some improvement for #5729

### CODE REVIEW

**Comment by lukastaegert** [comment]
I added a fix for #5735. What I found is that for MemberExpressions, we dynamically determine the value of computed properties not only when determining their "literal value" or their "return value", but also when deciding what to include or deoptimize. For the latter two cases, we do not have a mechanism to handle the case where we discover that the property value is reassigned later, which is also the case when a function is called more than once with different values.
I solved this by using a much more conservative strategy in those cases that only relies on static or literal property values that can never change.

**Comment by lukastaegert** [comment]
I added another fix for #5739. There was indeed a severe issue here: If the first call to a function with rest arguments did not supply any parameter value that would make it into the rest argument, then the logic would wrongly assume the value to be `undefined` as an exception for rest parameters was missing in this part of the logic.

**Comment by TrickyPi** [comment]
👍Awesome! The "Maximum call stack size exceeded" error is fixed in commit [40e2447](https://github.com/rollup/rollup/pull/5737/commits/40e2447b38d2337c594eea6c03a10606eba218da)!

**Comment by lukastaegert** [comment]
But it is noticeably slower now. So this is what the problem was: Because we replaced `include` with `includePath` and called the latter directly on the initializers of included variables (to include the necessary paths), we eagerly included much more in the bundle in the first run. This is why the logic needed much fewer runs for the same result. However, this resulted in extremely deep recursions. Technically, a single "includePath" could step through the entire code base sequentially before returning. And this without any infinite resolutions happening, just on normal operations. What I did is that I separated `includePath` into `include`, which would happen on each pass, and `includePath`, which would only include paths that are actually needed. These path inclusions would happen in `includeNode`, which is something only happening the very first time a node is included. Thus as `includePath` is no longer including everything but just what is relevant to include a given path, this breaks the long recursions.
Now let's see if this can be speeded up. The main issue is that we are now back to the original number of passes, but each pass is a little slower...

**Comment by lukastaegert** [comment]
I added an improvement to mimic the previous "eager inclusion" behavior by collecting all variables that are included for the first time and then after each tree-shaking pass to separately include their variable inits (with deduplication). This brings us back down to 5 passes and performance in the same range as before. I will release a new beta version for testing.

File: src/ast/nodes/MemberExpression.ts [hunk 1]
```diff
@@ -218,20 +232,17 @@ export default class MemberExpression
 		if (this.isUndefined) {
 			return undefined;
 		}
-		if (this.propertyKey !== UnknownKey && path.length < MAX_PATH_DEPTH) {
+		const propertyKey = this.getDynamicPropertyKey();
+		if (propertyKey !== UnknownKey && path.length < MAX_PATH_DEPTH) {
 			this.expressionsToBeDeoptimized.push(origin);
```
Comment (sapphi-red) [inline src/ast/nodes/MemberExpression.ts:237]: I tried `4.29.0-0` out and got `TypeError: Cannot add property 0, object is not extensible` error at this line. 
If I replace this line to `this.expressionsToBeDeoptimized = [...EMPTY_ARRAY]`, the error doesn't happen.
https://github.com/rollup/rollup/pull/5737/files#diff-7421c7a9da2cb68b551f48a8bd91f00c376f93e0a07b86f4563b1aab964c64a3R198

The way to reproduce is to clone https://github.com/vitejs/vite and upgrade rollup in `packages/vite/package.json` and run `pnpm build` in `packages/vite`. Let me know if I should trim it down.

Comment (lukastaegert) [reply src/ast/nodes/MemberExpression.ts:237]: Great catch, will have a deeper look by tomorrow. Maybe we just need to use a fresh empty array rather than the shared and (for good reasons) frozen empty array, or maybe there is a wrong assumption somewhere.

Comment (lukastaegert) [reply src/ast/nodes/MemberExpression.ts:237]: I see. I changed the logic im MemberExpressions to not deoptimize fully but only to its statically resolvable value if that is knowable, but there are places in the logic that still assume we always deoptimize to "unknown". Will likely draw up a fix tomorrow. In the meantime, here is a minimal reproduction that I managed to distill from the Vite code
https://rollup-eztxif0az-rollup-js.vercel.app/repl/?pr=5737&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwdGVzdCh4KSUyMCU3QiU1Q24lMjAlMjBpZiUyMCh4JTNGLnkueiklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ29rJyklNUNuJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNudGVzdCglN0J5JTNBJTIwdHJ1ZSU3RCklM0IlNUNudGVzdCglN0J5JTNBJTIwZmFsc2UlN0QpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: Thanks! The build and tests in the vite repo now passes 👍

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: May I ask for a new pre-release? I'd like to try it out on vite-ecosystem-ci. I tried to run it with a patch but it didn't work easily.

Comment (lukastaegert) [reply src/ast/nodes/MemberExpression.ts]: Should be there in 20-30 minutes

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: analogjs, nuxt, qwik, sveltekit, vitest didn't pass the ecosystem-ci (but was passing with previous rollup versions).
I digged down nuxt and made a minimal reproduction:
https://rollup-eztxif0az-rollup-js.vercel.app/repl/?pr=5737&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwa2V5cyUyMCUzRCUyMCU3QiU1Q24lMjAlMjBuYW1lJTNBJTIwJ25hbWUnJTJDJTVDbiUyMCUyMG9yZGVyJTNBJTIwJ29yZGVyJyUyQyU1Q24lMjAlMjBlbmZvcmNlJTNBJTIwJ2VuZm9yY2UnJTJDJTVDbiUyMCUyMGRlcGVuZHNPbiUzQSUyMCdkZXBlbmRzT24nJTJDJTVDbiU3RCU1Q25mdW5jdGlvbiUyMGlzTWV0YWRhdGFLZXklMjAoa2V5KSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBrZXklMjBpbiUyMGtleXMlNUNuJTdEJTVDbiU1Q25jb25zb2xlLmxvZyhpc01ldGFkYXRhS2V5KCduYW1lJykpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=

I'll take a look at others whether it's a bug in rollup.

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: It seems Vitest's failure is also caused by a bug.
Steps to reproduce the vitest's error:

1. clone https://github.com/vitest-dev/vitest
1. change this line https://github.com/vitest-dev/vitest/blob/5ba49475dc1efe10a4d43443f70c683b9fde8720/package.json#L75 to `"rollup": "4.29.0-1"`
1. run `pnpm i && pnpm build`
1. at `../../packages/vitest/dist/chunks/resolveConfig.DCdQOwtR.js:6791:33`, `getConfig` has no argument passed. but it should have `project` (https://github.com/vitest-dev/vitest/blob/5ba49475dc1efe10a4d43443f70c683b9fde8720/packages/vitest/src/node/pools/forks.ts#L217).

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: I made  a minimal reproduction for qwik: https://rollup-eztxif0az-rollup-js.vercel.app/repl/?pr=5737&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwc2FmZUNhbGwlMjAlM0QlMjAoY2FsbCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwdHJ5JTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMGNhbGwoKSUzQiU1Q24lMjAlMjAlN0QlMjBjYXRjaCUyMChlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB0aHJvdyUyMGUlNUNuJTIwJTIwJTdEJTVDbiU3RCUzQiU1Q24lNUNuY29uc3QlMjBmb28lMjAlM0QlMjAxJTVDbmNvbnN0JTIwb3B0cyUyMCUzRCUyMCU3QiUyMGZvbyUyMCU3RCU1Q25zYWZlQ2FsbCgoKSUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKG9wdHMpKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTdEJTdE

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: Sveltekit failed locally with and without upgrading rollup, so probably that one is not related.

Comment (lukastaegert) [reply src/ast/nodes/MemberExpression.ts]: I resolved the two issues you created the two reproductions for in 4.29.0. I think this also fixed Vitest. Will need to have a look at analog tomorrow.

Comment (lukastaegert) [reply src/ast/nodes/MemberExpression.ts]: And thank you so much, ecosystem CI is really pure gold here. In the future, can I trigger this some way from my side for "risky" releases, e.g. by creating a draft PR against the Vite repo with a beta version?

Comment (lukastaegert) [reply src/ast/nodes/MemberExpression.ts]: It seems to me that analog runs with 4.29.0-2 with similar performance as before.

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: Thanks for the fixes. It seems analog and storybook is failing now (others are passing 🎉). I'll take a look tomorrow.

> In the future, can I trigger this some way from my side for "risky" releases, e.g. by creating a draft PR against the Vite repo with a beta version?

Yes 👍 I'll make a PR tomorrow so that you can run it.

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: Made a reproduction for storybook (probably analog has the same root cause).
https://stackblitz.com/edit/rollup-repro-cqidpdk2?file=package.json,src%2Fmain.js,src%2Ffoo.js,rollup.config.js
(need to be downloaded and run locally as it doesn't work in stackblitz)

Also I found a related regression. There was a case that the code was removed before but now not removed ([4.29.1 REPL](https://rollupjs.org/repl/?version=4.29.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbW9kdWxlXzEuanMnJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJ2YXIlMjBldmVudHMlMjAlM0QlMjAlMkYqJTIwJTQwX19QVVJFX18lMjAqJTJGJTIwKChldmVudHMyKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBldmVudHMyJTVCJTVDJTIyQ0hBTk5FTF9XU19ESVNDT05ORUNUJTVDJTIyJTVEJTIwJTNEJTIwJTVDJTIyY2hhbm5lbFdTRGlzY29ubmVjdCU1QyUyMiUzQiU1Q24lMjAlMjBldmVudHMyJTVCJTVDJTIyQ0hBTk5FTF9DUkVBVEVEJTVDJTIyJTVEJTIwJTNEJTIwJTVDJTIyY2hhbm5lbENyZWF0ZWQlNUMlMjIlM0IlNUNuJTIwJTIwcmV0dXJuJTIwZXZlbnRzMiUzQiU1Q24lN0QpKGV2ZW50cyUyMCU3QyU3QyUyMCU3QiU3RCklM0IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGV2ZW50cyUzQiU1Q25leHBvcnQlMjBjb25zdCUyMCU3QiU1Q24lMjAlMjBDSEFOTkVMX1dTX0RJU0NPTk5FQ1QlMkMlNUNuJTIwJTIwQ0hBTk5FTF9DUkVBVEVEJTVDbiU3RCUyMCUzRCUyMGV2ZW50cyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMS5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=), 
[4.30.1 REPL](https://rollup-eztxif0az-rollup-js.vercel.app/repl/?pr=5737&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbW9kdWxlXzEuanMnJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJ2YXIlMjBldmVudHMlMjAlM0QlMjAlMkYqJTIwJTQwX19QVVJFX18lMjAqJTJGJTIwKChldmVudHMyKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBldmVudHMyJTVCJTVDJTIyQ0hBTk5FTF9XU19ESVNDT05ORUNUJTVDJTIyJTVEJTIwJTNEJTIwJTVDJTIyY2hhbm5lbFdTRGlzY29ubmVjdCU1QyUyMiUzQiU1Q24lMjAlMjBldmVudHMyJTVCJTVDJTIyQ0hBTk5FTF9DUkVBVEVEJTVDJTIyJTVEJTIwJTNEJTIwJTVDJTIyY2hhbm5lbENyZWF0ZWQlNUMlMjIlM0IlNUNuJTIwJTIwcmV0dXJuJTIwZXZlbnRzMiUzQiU1Q24lN0QpKGV2ZW50cyUyMCU3QyU3QyUyMCU3QiU3RCklM0IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGV2ZW50cyUzQiU1Q25leHBvcnQlMjBjb25zdCUyMCU3QiU1Q24lMjAlMjBDSEFOTkVMX1dTX0RJU0NPTk5FQ1QlMkMlNUNuJTIwJTIwQ0hBTk5FTF9DUkVBVEVEJTVDbiU3RCUyMCUzRCUyMGV2ZW50cyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJtb2R1bGVfMS5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlN0QlN0Q=)).

Comment (sapphi-red) [reply src/ast/nodes/MemberExpression.ts]: > > In the future, can I trigger this some way from my side for "risky" releases, e.g. by creating a draft PR against the Vite repo with a beta version?
> 
> Yes 👍 I'll make a PR tomorrow so that you can run it.

This PR has been merged. You should be able to run it by the following steps:

1. Make a draft PR against the Vite repo with the new rollup version.
2. Comment `/ecosystem-ci run` on that PR.

Let me know if it does not work for have any questions about the results of ecosystem-ci. 🙂

**Comment by printfn** [comment]
I believe this has just broken my build, I'm getting errors with rollup 4.34. My application uses webassembly (https://github.com/bytecodealliance/jco and the wasi-p2 shim), triggering an exception "TypeError: invalid variant tag value `undefined` (received `[object Object]`) specified for `StreamError`".

I can try and make a minimal reproduction and open an issue for this later.

**Comment by lukastaegert** [comment]
Thank you to the quick reproduction. Let me know if `rollup@4.34.1` will resolve this issue.

**Comment by dgreensp** [comment]
And I would love to see this extended to assigned properties, as in:

```ts
function foo() {}
foo.bar = function() {}
foo.baz = function() {}

console.log(foo.bar()); // only retains bar
```

**Comment by lukastaegert** [comment]
At the moment, the property tree-shaking logic is quite conservative and, as you see, does not include properties that are added later. One big complexity comes from the fact that any assignment could trigger a setter that again modifies the entire object (admittedly, this also applies to getters...). Also, a method call can modify the object via this. I assume the issues come from some deoptimizations in this area. We plan on adding further optimizations, but at the moment we focus on making sure that no bugs crept in.
