### PR TITLE
fix: improve error for manualChunks' modules that are resolved as an external module

### LINKED ISSUE #4633: Improve error when manualChunks includes external modules
### Expected Behavior / Situation

When `manualChunks` includes modules externalized by a plugin.

#### Reproduction
```js
import nodeResolve from '@rollup/plugin-node-resolve';

export default {
  input: 'src/main.js',
  external: ['react'],
  output: {
    dir: 'dist',
    format: 'esm',
    exports: 'auto',
    manualChunks: {
      react: ['react'],
    },
  },
  plugins: [
    nodeResolve(),
    {
      name: 'externalizer',
      resolveId(source, importer, options) {
        if (source === 'react') {
          return { external: true };
        }
      },
    },
  ],
};
```
[stackblitz](https://stackblitz.com/edit/rollup-template-whqurg?file=rollup.config.js)

In a real world situation, this happens when bundling for SSR with Vite (Vite sets `external` in a plugin).

### Actual Behavior / Situation

Currently rollup outputs the following error:

> [!] Error: Entry module cannot be external (react).

I know it's wrong to include externalized modules to `manualChunks`. But I feel this is a bit difficult to understand.
(My understanding is: `manualChunks` makes each specified module as an entry module, so `react` is an entry module.)

### Modification Proposal

Output an error like:

> [!] Error: Manual chunks includes an externalized module (react).

or

> [!] Error: Externalized module (react) should not be included in `manualChunks`.

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

resolves #4633 

### Description
extend `loadEntryModule` and `addAdditionalModules` functions to know if it is a load for the manualChunks' module, then we can throw a correct error based on flag `isLoadForManualChunks`.

### CODE REVIEW

File: src/utils/logs.ts [hunk 1]
```diff
@@ -926,6 +928,13 @@ export function logEntryCannotBeExternal(unresolvedId: string): RollupLog {
 	};
 }
 
+export function logExternalizedModulesCannotBeIncludedInManualChunks(source: string) {
+	return {
+		code: EXTERNALIZED_MODULES_CANNOT_BE_INCLUDED_IN_MANUAL_CHUNKS,
+		message: `"${source}" cannot be included in manualChunks, because it is resolved as an external module by plugins`
```
Comment (lukastaegert) [inline src/utils/logs.ts:934]: Nice! Question: can this only happen when plugins make the module external, or could this also happen when a user uses the "external" option? Then maybe we should adjust the message:
 
 `"${source}" cannot be included in manualChunks, because it is resolved as an external module by the "external" option or plugins.`

Also note that error message usually end with a "." But this is just tiny details, nice work overall!

Comment (TrickyPi) [reply src/utils/logs.ts:934]: > could this also happen when a user uses the "external" option?

Ok, I will give it a try.

File: test/function/samples/manual-chunks-include-external-modules3/_config.js
Comment (TrickyPi) [inline test/function/samples/manual-chunks-include-external-modules3/_config.js:1]: If the type of 'manualChunks' is `object`, it includes an external module that will be resolved as a module in this function
https://github.com/rollup/rollup/blob/1b62c336b8e927e846cd2c04563ae0868a5d5832/src/Bundle.ts#L105-L121
I suspect it is unexpected, so I throw an new error from here
https://github.com/rollup/rollup/pull/5050/files#diff-1d2d86a9be3305dbb026a6b14b2179c8fcbb04c9861873f70f2ed6447a286ac6R388-R391

File: src/utils/logs.ts (hunk 1 above)
Comment (TrickyPi) [reply src/utils/logs.ts]: done

File: src/utils/logs.ts [hunk 2]
```diff
@@ -926,6 +930,20 @@ export function logEntryCannotBeExternal(unresolvedId: string): RollupLog {
 	};
 }
 
+export function logExternalModulesCannotBeIncludedInManualChunks(source: string): RollupLog {
+	return {
+		code: EXTERNAL_MODULES_CANNOT_BE_INCLUDED_IN_MANUAL_CHUNKS,
+		message: `"${source}" cannot be included in manualChunks, because it is resolved as an external module by the "external" option or plugins.`
```
Comment (lukastaegert) [inline src/utils/logs.ts:936]:
```suggestion
		message: `"${source}" cannot be included in manualChunks because it is resolved as an external module by the "external" option or plugins.`
```

File: src/utils/logs.ts [hunk 3]
```diff
@@ -926,6 +930,20 @@ export function logEntryCannotBeExternal(unresolvedId: string): RollupLog {
...
+	};
+}
+
+export function logExternalModulesCannotBeTransformedToModules(source: string): RollupLog {
+	return {
+		code: EXTERNAL_MODULES_CANNOT_BE_TRANSFORMED_TO_MODULES,
+		message: `${source} is resolved as an module now, but it was an external module before. Please check whether there are conflicts in your Rollup options "external" and "manualChunks", manualChunks cannot include external modules.`
```
Comment (lukastaegert) [inline src/utils/logs.ts:943]:
```suggestion
		message: `${source} is resolved as a module now, but it was an external module before. Please check whether there are conflicts in your Rollup options "external" and "manualChunks", manualChunks cannot include external modules.`
```

**Review by lukastaegert — COMMENTED** [review]
Looks great, just two minor stylistic issues I found, otherwise the code looks fine!

File: src/ModuleLoader.ts [hunk 4]
```diff
@@ -95,9 +97,16 @@ export class ModuleLoader {
 			: () => true;
 	}
 
-	async addAdditionalModules(unresolvedModules: readonly string[]): Promise<Module[]> {
+	async addAdditionalModules(
+		unresolvedModules: readonly string[],
+		isAddForManualChunks = false
```
Comment (lukastaegert) [inline src/ModuleLoader.ts:102]: This fallback is never used and thus messes up coverage

Comment (TrickyPi) [reply src/ModuleLoader.ts]: removed this fallback

**Review by lukastaegert — APPROVED** [review]
