### PR TITLE
Handle external reassignments

### LINKED ISSUE #2237: Rollup v59 breaks application logic
Hi

Rollup v59+ removes function calls from object literals that are used by external code.

I have created small piece of code to reproduce the problem.
[Rollup v59](https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmNyZWF0ZURldlRvb2xzQnJpZGdlJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMnJTNCJTVDbiU1Q253aW5kb3cuZGV2dG9vbHMlMjAlM0QlMjBjcmVhdGVEZXZUb29sc0JyaWRnZSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3JlYXRlRGV2VG9vbHNCcmlkZ2UoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBNb3VudCUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBfaW5zdGFuY2VzQnlSZWFjdFJvb3RJRCUzQSUyMCU1QiU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkYlMjB0c2xpbnQlM0FkaXNhYmxlLW5leHQtbGluZSUzQW5vLWVtcHR5JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMF9yZW5kZXJOZXdSb290Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjBfcmVuZGVyTmV3Um9vdENvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCUyMHZhciUyMFJlY29uY2lsZXIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBtb3VudENvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwbW91bnRDb21wb25lbnQoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcGVyZm9ybVVwZGF0ZUlmTmVjZXNzYXJ5JTNBJTIwZnVuY3Rpb24lMjBwZXJmb3JtVXBkYXRlSWZOZWNlc3NhcnkoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmVjZWl2ZUNvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwcmVjZWl2ZUNvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB1bm1vdW50Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjB1bm1vdW50Q29tcG9uZW50KGluc3RhbmNlKSUyMCU3QiUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwJTJGKiolMjBOb3RpZnklMjBkZXZ0b29scyUyMHRoYXQlMjBhJTIwbmV3JTIwY29tcG9uZW50JTIwaW5zdGFuY2UlMjBoYXMlMjBiZWVuJTIwbW91bnRlZCUyMGludG8lMjB0aGUlMjBET00uJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBjb21wb25lbnRBZGRlZCUyMCUzRCUyMGZ1bmN0aW9uJTIwKHZOb2RlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBpbnN0YW5jZSUyMCUzRCUyMHVwZGF0ZVJlYWN0Q29tcG9uZW50KHZOb2RlJTJDJTIwbnVsbCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaXNSb290Vk5vZGUodk5vZGUpKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpbnN0YW5jZS5fcm9vdElEJTIwJTNEJTIwbmV4dFJvb3RLZXkocm9vdHMpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcm9vdHMlNUJpbnN0YW5jZS5fcm9vdElEJTVEJTIwJTNEJTIwaW5zdGFuY2UlM0IlNUNuJTVDdCU1Q3QlNUN0JTVDdCU1Q3QlMkYlMkYlMjBUaGlzJTIwY29tbWVudCUyMGlzJTIwYWxzbyUyMHJlbW92ZWQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQuX3JlbmRlck5ld1Jvb3RDb21wb25lbnQoaW5zdGFuY2UpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZpc2l0Tm9uQ29tcG9zaXRlQ2hpbGRyZW4oaW5zdGFuY2UlMkMlMjBmdW5jdGlvbiUyMChjaGlsZEluc3QpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNoaWxkSW5zdC5faW5EZXZUb29scyUyMCUzRCUyMHRydWUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChjaGlsZEluc3QpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChpbnN0YW5jZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwQ29tcG9uZW50VHJlZSUzQSUyMENvbXBvbmVudFRyZWUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQlM0ElMjBNb3VudCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBSZWNvbmNpbGVyJTNBJTIwUmVjb25jaWxlciUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb21wb25lbnRBZGRlZCUzQSUyMGNvbXBvbmVudEFkZGVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFJlbW92ZWQlM0ElMjBjb21wb25lbnRSZW1vdmVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFVwZGF0ZWQlM0ElMjBjb21wb25lbnRVcGRhdGVkJTVDbiUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

And in v58 this is working correctly [LINK](https://rollupjs.org/repl?version=0.58.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmNyZWF0ZURldlRvb2xzQnJpZGdlJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMnJTNCJTVDbiU1Q253aW5kb3cuZGV2dG9vbHMlMjAlM0QlMjBjcmVhdGVEZXZUb29sc0JyaWRnZSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3JlYXRlRGV2VG9vbHNCcmlkZ2UoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBNb3VudCUyMCUzRCUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBfaW5zdGFuY2VzQnlSZWFjdFJvb3RJRCUzQSUyMCU1QiU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMkYlMkYlMjB0c2xpbnQlM0FkaXNhYmxlLW5leHQtbGluZSUzQW5vLWVtcHR5JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMF9yZW5kZXJOZXdSb290Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjBfcmVuZGVyTmV3Um9vdENvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCUyMHZhciUyMFJlY29uY2lsZXIlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBtb3VudENvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwbW91bnRDb21wb25lbnQoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcGVyZm9ybVVwZGF0ZUlmTmVjZXNzYXJ5JTNBJTIwZnVuY3Rpb24lMjBwZXJmb3JtVXBkYXRlSWZOZWNlc3NhcnkoaW5zdGFuY2UpJTIwJTdCJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiUyMHRzbGludCUzQWRpc2FibGUtbmV4dC1saW5lJTNBbm8tZW1wdHklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmVjZWl2ZUNvbXBvbmVudCUzQSUyMGZ1bmN0aW9uJTIwcmVjZWl2ZUNvbXBvbmVudChpbnN0YW5jZSklMjAlN0IlMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTIwdHNsaW50JTNBZGlzYWJsZS1uZXh0LWxpbmUlM0Fuby1lbXB0eSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB1bm1vdW50Q29tcG9uZW50JTNBJTIwZnVuY3Rpb24lMjB1bm1vdW50Q29tcG9uZW50KGluc3RhbmNlKSUyMCU3QiUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwJTJGKiolMjBOb3RpZnklMjBkZXZ0b29scyUyMHRoYXQlMjBhJTIwbmV3JTIwY29tcG9uZW50JTIwaW5zdGFuY2UlMjBoYXMlMjBiZWVuJTIwbW91bnRlZCUyMGludG8lMjB0aGUlMjBET00uJTIwKiUyRiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBjb21wb25lbnRBZGRlZCUyMCUzRCUyMGZ1bmN0aW9uJTIwKHZOb2RlKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YXIlMjBpbnN0YW5jZSUyMCUzRCUyMHVwZGF0ZVJlYWN0Q29tcG9uZW50KHZOb2RlJTJDJTIwbnVsbCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoaXNSb290Vk5vZGUodk5vZGUpKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpbnN0YW5jZS5fcm9vdElEJTIwJTNEJTIwbmV4dFJvb3RLZXkocm9vdHMpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDElNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcm9vdHMlNUJpbnN0YW5jZS5fcm9vdElEJTVEJTIwJTNEJTIwaW5zdGFuY2UlM0IlNUNuJTVDdCU1Q3QlNUN0JTVDdCU1Q3QlMkYlMkYlMjBUaGlzJTIwY29tbWVudCUyMGlzJTIwYWxzbyUyMHJlbW92ZWQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQuX3JlbmRlck5ld1Jvb3RDb21wb25lbnQoaW5zdGFuY2UpJTNCJTVDbiU1Q3QlNUN0JTVDdCU1Q3QlNUN0JTJGJTJGJTIwQ29tbWVudDIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZpc2l0Tm9uQ29tcG9zaXRlQ2hpbGRyZW4oaW5zdGFuY2UlMkMlMjBmdW5jdGlvbiUyMChjaGlsZEluc3QpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNoaWxkSW5zdC5faW5EZXZUb29scyUyMCUzRCUyMHRydWUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChjaGlsZEluc3QpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwUmVjb25jaWxlci5tb3VudENvbXBvbmVudChpbnN0YW5jZSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiUyMCUyMCUyMCU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwQ29tcG9uZW50VHJlZSUzQSUyMENvbXBvbmVudFRyZWUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwTW91bnQlM0ElMjBNb3VudCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBSZWNvbmNpbGVyJTNBJTIwUmVjb25jaWxlciUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb21wb25lbnRBZGRlZCUzQSUyMGNvbXBvbmVudEFkZGVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFJlbW92ZWQlM0ElMjBjb21wb25lbnRSZW1vdmVkJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbXBvbmVudFVwZGF0ZWQlM0ElMjBjb21wb25lbnRVcGRhdGVkJTVDbiUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

See how valid code gets removed inside `componentAdded` method

### PR DESCRIPTION
**Pull request by lukastaegert**
Resolves #2237

As it turns out, there was nothing to do for objects attached to globals as the global variable handling has always been very conservative here. Added a regression test nonetheless.

External exports are now properly marked as reassigned.

### CODE REVIEW

File: src/Module.ts [hunk 1]
```diff
@@ -431,11 +433,12 @@ export default class Module {
 		return makeLegal(ext ? base.slice(0, -ext.length) : base);
 	}
 
-	markExports() {
+	markPublicExports() {
 		for (const exportName of this.getExports()) {
 			const variable = this.traceExport(exportName);
 
 			variable.exportName = exportName;
+			variable.reassignPath(UNKNOWN_PATH, NEW_EXECUTION_PATH);
```
Comment (guybedford) [inline src/Module.ts]: Just wondering, if we are going to support object truthiness in future like:

```js
var obj = {};
if (!obj || typeof obj !== 'object')
  console.log('treeshaken');
```

Then would it make sense to have a form of `reassignPath` that can treat the object as still an object, but with unknown properties?

So the following optimization could still work:

```js
const obj = {
	reassigned() {},
	test() {
		obj.reassigned();
	}
};

export default obj;

if (!obj)
  console.log('treeshaken');
```

Comment (lukastaegert) [reply src/Module.ts]: This would be supported by the current approach. `UNKNOWN_PATH` might be a sub-optimal variable name as it is actually an "unknown path of length one". Thus the object is still recognized as an object but we no longer have any reliable information about the values of its fields.
