### PR TITLE
fix(deconflictChunk): Deconflict multiple `index` imports for ES format using nested export star statements

### LINKED ISSUE #3365: Duplicate import identifier when re-exporting with export star when preserveModules is true
- Rollup Version: 1.31.0-2.0.3
- Operating System (or Browser): Mac OS Mojave
- Node Version: v12.14.1

Search terms: export star, reexport, re-export, nested modules, preserveModules

When using `preserveModules`, we're seeing an issue handling nested module re-exporting using `export *` as shown below.

### How Do We Reproduce?

Minimal reproduction: https://github.com/kamranayub/rollup-bug-reexporting-preserveModules

1. You can view the output in `dist/index.js`
1. You can also run `yarn` and `yarn build` to rebuild the output

### Expected Behavior

We'd expect Rollup to de-dupe the import alias similar to how it behaves with `preserveModules: false` (e.g. `index$1`)

```
import * as index from './module-a/v1/index.js';
export { index as ModuleA_V1 };
import * as index$1 from './module-b/v1/index.js';
export { index$1 as ModuleB_V1 };
```

### Actual Behavior

Rollup generates a duplicate import alias:

```js
import * as index from './module-a/v1/index.js';
export { index as ModuleA_V1 };
import * as index from './module-b/v1/index.js';
export { index as ModuleB_V1 };
```

This will result in an error when consumed:

```
Identifier 'index' has already been declared
```

See: https://github.com/kamranayub/rollup-bug-reexporting-preserveModules/blob/master/dist/index.js

### PR DESCRIPTION
**Pull request by kamranayub**
This PR contains:
- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?
- [x] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers: Fixes #3365

### Description

This is my proposed fix with a test showing the unexpected output of using `preserveModules: true` with ES output and exporting multiple index aliases within `main.js` which reproduces the issue #3365 

I modified `deconflictImportsEsm` because what seemed to be happening was the `index` variables weren't being detected as `usedNames` on the root `index.js` file, so they were not being deconflicted. This is OK with System output but not with ES output.

I moved the `dependencies` logic from `deconflictImportsOther` into `deconflictImportsEsm` which fixed the issue. However, I wrapped it in a condition to only apply when the variable name is `index` as without that it seemed to be renaming a lot of variables unecessarily.

To be honest, I don't know what other implications this has so I'm leaning on the expertise of the team to provide feedback on this.

### CODE REVIEW

File: src/utils/deconflictChunk.ts [hunk 1]
```diff
@@ -51,9 +51,18 @@ export function deconflictChunk(
 function deconflictImportsEsm(
 	usedNames: Set<string>,
 	imports: Set<Variable>,
-	_dependencies: Set<ExternalModule | Chunk>,
+	dependencies: Set<ExternalModule | Chunk>,
 	interop: boolean
 ) {
+	for (const chunkOrExternalModule of dependencies) {
```
Comment (kamranayub) [inline src/utils/deconflictChunk.ts]: Moved this logic from `deconflictImportsOther` and only applied with the `index` variable name to account for `export * from './inner'` statements. However, I don't know what other implications this has! 🤔

File: test/chunking-form/samples/preserve-modules-nested-barrel-es-export/_expected/es/main.js [hunk 2]
```diff
@@ -0,0 +1,4 @@
+import * as index from './module-a/v1/index.js';
+export { index as ModuleA_V1 };
+import * as index$1 from './module-b/v1/index.js';
```
Comment (kamranayub) [inline test/chunking-form/samples/preserve-modules-nested-barrel-es-export/_expected/es/main.js]: This is the main goal of this PR, to deconflict the `index` imports.

File: src/utils/deconflictChunk.ts (hunk 1 above)
Comment (lukastaegert) [reply src/utils/deconflictChunk.ts]: I'll have a look, thanks already for your work!

Comment (lukastaegert) [reply src/utils/deconflictChunk.ts]: Your proposed fix will only work for your example as the variable is only called "index" because your file is called "index". A general fix would be to run this for ALL dependencies, however this will cause a lot of test regressions (as you  may have noticed) due to a lot of unnecessary renames. The core of the problem is that reexporting a namespace is rendered (in `es.ts`) as importing the namespace as some variable and then exporting this variable, and this variable is not considered for deconflicting. A "nice" fix would be much more involved, but maybe this extends the scope of the bug fix. A simple hot "blanket" fix with only few regressions would be to  unconditionally deconflict the chunk variable names for all dependencies, but only do it if we are preserving modules. Maybe you could do that and add a comment what is fixed here and that this solution is not yet ideal (so that it is not forgotten)?

Comment (lukastaegert) [reply src/utils/deconflictChunk.ts]: The reason it is only necessary for preserveModules is that these kinds of reexports will not occur for other formats. Basically this line is responsible: https://github.com/rollup/rollup/blob/3ef6f073e4b54da2b2e61de5e3fd66f9f7352bca/src/Chunk.ts#L387

Comment (kamranayub) [reply src/utils/deconflictChunk.ts]: Awesome, I will do that and can update the specs to see what that impacts.

Comment (kamranayub) [reply src/utils/deconflictChunk.ts]: What I did was only apply this logic for `es` and `preserveModules: true` which lessens the impact so it doesn't impact current SystemJS behavior. Am I right in assuming this shouldn't really take effect for SystemJS? Otherwise it was affecting a lot more tests (56 vs. <10).

**Comment by kamranayub** [comment]
Thanks @lukastaegert, updated per your guidance.

Implications for consumers that I see right now:

- Slightly increased bundle sizes due to the extra characters generated
- Impact to code that might be diving into generated output

File: src/utils/deconflictChunk.ts [hunk 3]
```diff
@@ -49,6 +49,29 @@ export function deconflictChunk(
...
+	if (preserveModules) {
+		for (const chunkOrExternalModule of dependencies) {
+			chunkOrExternalModule.variableName = getSafeName(
+				chunkOrExternalModule.variableName,
+				usedNames
+			);
+		}
+	}
+	deconflictImportsEsmOrSystem(usedNames, imports, dependencies, interop);
+}
```
Comment (lukastaegert) [inline src/utils/deconflictChunk.ts]: Looks good, and easy to get back to for a deeper fix 👍
